// Generated by cheese wayland-scanner
// Source: /nix/store/rzqijc65iirn6q2pxkbfyd5dk9j0gc0i-wayland-scanner-1.24.0/share/wayland/wayland.xml
//
// wayland Protocol Copyright:
// Copyright © 2008-2011 Kristian Høgsberg
// Copyright © 2010-2011 Intel Corporation
// Copyright © 2012-2013 Collabora, Ltd.
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
// The above copyright notice and this permission notice (including the
// next paragraph) shall be included in all copies or substantial
// portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
// BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package client

import (
	"golang.org/x/sys/unix"
)

// WlDisplay: core global object
type WlDisplay struct {
	BaseProxy
}

// NewWlDisplay creates a new WlDisplay
func NewWlDisplay(ctx *Context) *WlDisplay {
	o := &WlDisplay{}
	ctx.Register(o)
	return o
}

// WlDisplayError: global error values
type WlDisplayError uint32

const (
	WlDisplayErrorInvalidObject  WlDisplayError = 0
	WlDisplayErrorInvalidMethod  WlDisplayError = 1
	WlDisplayErrorNoMemory       WlDisplayError = 2
	WlDisplayErrorImplementation WlDisplayError = 3
)

// Sync: asynchronous roundtrip
func (i *WlDisplay) Sync() (*WlCallback, error) {
	callback := NewWlCallback(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], callback.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return callback, err
}

// GetRegistry: get global registry object
func (i *WlDisplay) GetRegistry() (*WlRegistry, error) {
	registry := NewWlRegistry(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], registry.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return registry, err
}

// WlDisplayErrorEvent: fatal error event
type WlDisplayErrorEvent struct {
	ObjectId Proxy
	Code     uint32
	Message  string
}

type WlDisplayErrorHandler func(WlDisplayErrorEvent)

// WlDisplayDeleteIdEvent: acknowledge object ID deletion
type WlDisplayDeleteIdEvent struct {
	Id uint32
}

type WlDisplayDeleteIdHandler func(WlDisplayDeleteIdEvent)

// WlRegistry: global registry object
type WlRegistry struct {
	BaseProxy
}

// NewWlRegistry creates a new WlRegistry
func NewWlRegistry(ctx *Context) *WlRegistry {
	o := &WlRegistry{}
	ctx.Register(o)
	return o
}

// Bind: bind an object to the display
func (i *WlRegistry) Bind(name uint32, iface string, version uint32, id Proxy) error {
	const opcode = 0
	ifaceLen := PaddedLen(len(iface) + 1)
	_reqBufLen := 8 + 4 + (4 + ifaceLen) + 4 + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(name))
	l += 4
	PutString(_reqBuf[l:l+(4+ifaceLen)], iface, ifaceLen)
	l += (4 + ifaceLen)
	PutUint32(_reqBuf[l:l+4], uint32(version))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// WlRegistryGlobalEvent: announce global object
type WlRegistryGlobalEvent struct {
	Name      uint32
	Interface string
	Version   uint32
}

type WlRegistryGlobalHandler func(WlRegistryGlobalEvent)

// WlRegistryGlobalRemoveEvent: announce removal of global object
type WlRegistryGlobalRemoveEvent struct {
	Name uint32
}

type WlRegistryGlobalRemoveHandler func(WlRegistryGlobalRemoveEvent)

// WlCallback: callback object
type WlCallback struct {
	BaseProxy
}

// NewWlCallback creates a new WlCallback
func NewWlCallback(ctx *Context) *WlCallback {
	o := &WlCallback{}
	ctx.Register(o)
	return o
}

// WlCallbackDoneEvent: done event
type WlCallbackDoneEvent struct {
	CallbackData uint32
}

type WlCallbackDoneHandler func(WlCallbackDoneEvent)

// WlCompositor: the compositor singleton
type WlCompositor struct {
	BaseProxy
}

// NewWlCompositor creates a new WlCompositor
func NewWlCompositor(ctx *Context) *WlCompositor {
	o := &WlCompositor{}
	ctx.Register(o)
	return o
}

// CreateSurface: create new surface
func (i *WlCompositor) CreateSurface() (*WlSurface, error) {
	id := NewWlSurface(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// CreateRegion: create new region
func (i *WlCompositor) CreateRegion() (*WlRegion, error) {
	id := NewWlRegion(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WlShmPool: a shared memory pool
type WlShmPool struct {
	BaseProxy
}

// NewWlShmPool creates a new WlShmPool
func NewWlShmPool(ctx *Context) *WlShmPool {
	o := &WlShmPool{}
	ctx.Register(o)
	return o
}

// CreateBuffer: create a buffer from the pool
func (i *WlShmPool) CreateBuffer(offset int32, width int32, height int32, stride int32, format uint32) (*WlBuffer, error) {
	id := NewWlBuffer(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(offset))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(stride))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(format))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Destroy: destroy the pool
func (i *WlShmPool) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Resize: change the size of the pool mapping
func (i *WlShmPool) Resize(size int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(size))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlShm: shared memory support
type WlShm struct {
	BaseProxy
}

// NewWlShm creates a new WlShm
func NewWlShm(ctx *Context) *WlShm {
	o := &WlShm{}
	ctx.Register(o)
	return o
}

// WlShmError: wl_shm error values
type WlShmError uint32

const (
	WlShmErrorInvalidFormat WlShmError = 0
	WlShmErrorInvalidStride WlShmError = 1
	WlShmErrorInvalidFd     WlShmError = 2
)

// WlShmFormat: pixel formats
type WlShmFormat uint32

const (
	WlShmFormatArgb8888             WlShmFormat = 0
	WlShmFormatXrgb8888             WlShmFormat = 1
	WlShmFormatC8                   WlShmFormat = 0x20203843
	WlShmFormatRgb332               WlShmFormat = 0x38424752
	WlShmFormatBgr233               WlShmFormat = 0x38524742
	WlShmFormatXrgb4444             WlShmFormat = 0x32315258
	WlShmFormatXbgr4444             WlShmFormat = 0x32314258
	WlShmFormatRgbx4444             WlShmFormat = 0x32315852
	WlShmFormatBgrx4444             WlShmFormat = 0x32315842
	WlShmFormatArgb4444             WlShmFormat = 0x32315241
	WlShmFormatAbgr4444             WlShmFormat = 0x32314241
	WlShmFormatRgba4444             WlShmFormat = 0x32314152
	WlShmFormatBgra4444             WlShmFormat = 0x32314142
	WlShmFormatXrgb1555             WlShmFormat = 0x35315258
	WlShmFormatXbgr1555             WlShmFormat = 0x35314258
	WlShmFormatRgbx5551             WlShmFormat = 0x35315852
	WlShmFormatBgrx5551             WlShmFormat = 0x35315842
	WlShmFormatArgb1555             WlShmFormat = 0x35315241
	WlShmFormatAbgr1555             WlShmFormat = 0x35314241
	WlShmFormatRgba5551             WlShmFormat = 0x35314152
	WlShmFormatBgra5551             WlShmFormat = 0x35314142
	WlShmFormatRgb565               WlShmFormat = 0x36314752
	WlShmFormatBgr565               WlShmFormat = 0x36314742
	WlShmFormatRgb888               WlShmFormat = 0x34324752
	WlShmFormatBgr888               WlShmFormat = 0x34324742
	WlShmFormatXbgr8888             WlShmFormat = 0x34324258
	WlShmFormatRgbx8888             WlShmFormat = 0x34325852
	WlShmFormatBgrx8888             WlShmFormat = 0x34325842
	WlShmFormatAbgr8888             WlShmFormat = 0x34324241
	WlShmFormatRgba8888             WlShmFormat = 0x34324152
	WlShmFormatBgra8888             WlShmFormat = 0x34324142
	WlShmFormatXrgb2101010          WlShmFormat = 0x30335258
	WlShmFormatXbgr2101010          WlShmFormat = 0x30334258
	WlShmFormatRgbx1010102          WlShmFormat = 0x30335852
	WlShmFormatBgrx1010102          WlShmFormat = 0x30335842
	WlShmFormatArgb2101010          WlShmFormat = 0x30335241
	WlShmFormatAbgr2101010          WlShmFormat = 0x30334241
	WlShmFormatRgba1010102          WlShmFormat = 0x30334152
	WlShmFormatBgra1010102          WlShmFormat = 0x30334142
	WlShmFormatYuyv                 WlShmFormat = 0x56595559
	WlShmFormatYvyu                 WlShmFormat = 0x55595659
	WlShmFormatUyvy                 WlShmFormat = 0x59565955
	WlShmFormatVyuy                 WlShmFormat = 0x59555956
	WlShmFormatAyuv                 WlShmFormat = 0x56555941
	WlShmFormatNv12                 WlShmFormat = 0x3231564e
	WlShmFormatNv21                 WlShmFormat = 0x3132564e
	WlShmFormatNv16                 WlShmFormat = 0x3631564e
	WlShmFormatNv61                 WlShmFormat = 0x3136564e
	WlShmFormatYuv410               WlShmFormat = 0x39565559
	WlShmFormatYvu410               WlShmFormat = 0x39555659
	WlShmFormatYuv411               WlShmFormat = 0x31315559
	WlShmFormatYvu411               WlShmFormat = 0x31315659
	WlShmFormatYuv420               WlShmFormat = 0x32315559
	WlShmFormatYvu420               WlShmFormat = 0x32315659
	WlShmFormatYuv422               WlShmFormat = 0x36315559
	WlShmFormatYvu422               WlShmFormat = 0x36315659
	WlShmFormatYuv444               WlShmFormat = 0x34325559
	WlShmFormatYvu444               WlShmFormat = 0x34325659
	WlShmFormatR8                   WlShmFormat = 0x20203852
	WlShmFormatR16                  WlShmFormat = 0x20363152
	WlShmFormatRg88                 WlShmFormat = 0x38384752
	WlShmFormatGr88                 WlShmFormat = 0x38385247
	WlShmFormatRg1616               WlShmFormat = 0x32334752
	WlShmFormatGr1616               WlShmFormat = 0x32335247
	WlShmFormatXrgb16161616F        WlShmFormat = 0x48345258
	WlShmFormatXbgr16161616F        WlShmFormat = 0x48344258
	WlShmFormatArgb16161616F        WlShmFormat = 0x48345241
	WlShmFormatAbgr16161616F        WlShmFormat = 0x48344241
	WlShmFormatXyuv8888             WlShmFormat = 0x56555958
	WlShmFormatVuy888               WlShmFormat = 0x34325556
	WlShmFormatVuy101010            WlShmFormat = 0x30335556
	WlShmFormatY210                 WlShmFormat = 0x30313259
	WlShmFormatY212                 WlShmFormat = 0x32313259
	WlShmFormatY216                 WlShmFormat = 0x36313259
	WlShmFormatY410                 WlShmFormat = 0x30313459
	WlShmFormatY412                 WlShmFormat = 0x32313459
	WlShmFormatY416                 WlShmFormat = 0x36313459
	WlShmFormatXvyu2101010          WlShmFormat = 0x30335658
	WlShmFormatXvyu1216161616       WlShmFormat = 0x36335658
	WlShmFormatXvyu16161616         WlShmFormat = 0x38345658
	WlShmFormatY0L0                 WlShmFormat = 0x304c3059
	WlShmFormatX0L0                 WlShmFormat = 0x304c3058
	WlShmFormatY0L2                 WlShmFormat = 0x324c3059
	WlShmFormatX0L2                 WlShmFormat = 0x324c3058
	WlShmFormatYuv4208Bit           WlShmFormat = 0x38305559
	WlShmFormatYuv42010Bit          WlShmFormat = 0x30315559
	WlShmFormatXrgb8888A8           WlShmFormat = 0x38415258
	WlShmFormatXbgr8888A8           WlShmFormat = 0x38414258
	WlShmFormatRgbx8888A8           WlShmFormat = 0x38415852
	WlShmFormatBgrx8888A8           WlShmFormat = 0x38415842
	WlShmFormatRgb888A8             WlShmFormat = 0x38413852
	WlShmFormatBgr888A8             WlShmFormat = 0x38413842
	WlShmFormatRgb565A8             WlShmFormat = 0x38413552
	WlShmFormatBgr565A8             WlShmFormat = 0x38413542
	WlShmFormatNv24                 WlShmFormat = 0x3432564e
	WlShmFormatNv42                 WlShmFormat = 0x3234564e
	WlShmFormatP210                 WlShmFormat = 0x30313250
	WlShmFormatP010                 WlShmFormat = 0x30313050
	WlShmFormatP012                 WlShmFormat = 0x32313050
	WlShmFormatP016                 WlShmFormat = 0x36313050
	WlShmFormatAxbxgxrx106106106106 WlShmFormat = 0x30314241
	WlShmFormatNv15                 WlShmFormat = 0x3531564e
	WlShmFormatQ410                 WlShmFormat = 0x30313451
	WlShmFormatQ401                 WlShmFormat = 0x31303451
	WlShmFormatXrgb16161616         WlShmFormat = 0x38345258
	WlShmFormatXbgr16161616         WlShmFormat = 0x38344258
	WlShmFormatArgb16161616         WlShmFormat = 0x38345241
	WlShmFormatAbgr16161616         WlShmFormat = 0x38344241
	WlShmFormatC1                   WlShmFormat = 0x20203143
	WlShmFormatC2                   WlShmFormat = 0x20203243
	WlShmFormatC4                   WlShmFormat = 0x20203443
	WlShmFormatD1                   WlShmFormat = 0x20203144
	WlShmFormatD2                   WlShmFormat = 0x20203244
	WlShmFormatD4                   WlShmFormat = 0x20203444
	WlShmFormatD8                   WlShmFormat = 0x20203844
	WlShmFormatR1                   WlShmFormat = 0x20203152
	WlShmFormatR2                   WlShmFormat = 0x20203252
	WlShmFormatR4                   WlShmFormat = 0x20203452
	WlShmFormatR10                  WlShmFormat = 0x20303152
	WlShmFormatR12                  WlShmFormat = 0x20323152
	WlShmFormatAvuy8888             WlShmFormat = 0x59555641
	WlShmFormatXvuy8888             WlShmFormat = 0x59555658
	WlShmFormatP030                 WlShmFormat = 0x30333050
)

// CreatePool: create a shm pool
func (i *WlShm) CreatePool(fd uintptr, size int32) (*WlShmPool, error) {
	id := NewWlShmPool(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(size))
	l += 4
	oob := unix.UnixRights(int(fd))
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return id, err
}

// Release: release the shm object
func (i *WlShm) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlShmFormatEvent: pixel format description
type WlShmFormatEvent struct {
	Format uint32
}

type WlShmFormatHandler func(WlShmFormatEvent)

// WlBuffer: content for a wl_surface
type WlBuffer struct {
	BaseProxy
}

// NewWlBuffer creates a new WlBuffer
func NewWlBuffer(ctx *Context) *WlBuffer {
	o := &WlBuffer{}
	ctx.Register(o)
	return o
}

// Destroy: destroy a buffer
func (i *WlBuffer) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlBufferReleaseEvent: compositor releases buffer
type WlBufferReleaseEvent struct {
}

type WlBufferReleaseHandler func(WlBufferReleaseEvent)

// WlDataOffer: offer to transfer data
type WlDataOffer struct {
	BaseProxy
}

// NewWlDataOffer creates a new WlDataOffer
func NewWlDataOffer(ctx *Context) *WlDataOffer {
	o := &WlDataOffer{}
	ctx.Register(o)
	return o
}

type WlDataOfferError uint32

const (
	WlDataOfferErrorInvalidFinish     WlDataOfferError = 0
	WlDataOfferErrorInvalidActionMask WlDataOfferError = 1
	WlDataOfferErrorInvalidAction     WlDataOfferError = 2
	WlDataOfferErrorInvalidOffer      WlDataOfferError = 3
)

// Accept: accept one of the offered mime types
func (i *WlDataOffer) Accept(serial uint32, mime_type *string) error {
	const opcode = 0
	var mime_typeLen int
	if mime_type != nil {
		mime_typeLen = PaddedLen(len(*mime_type) + 1)
	}
	_reqBufLen := 8 + 4 + (4 + mime_typeLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	if mime_type == nil {
		PutUint32(_reqBuf[l:l+4], 0)
	} else {
		PutString(_reqBuf[l:l+(4+mime_typeLen)], *mime_type, mime_typeLen)
	}
	l += (4 + mime_typeLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Receive: request that the data is transferred
func (i *WlDataOffer) Receive(mime_type string, fd uintptr) error {
	const opcode = 1
	mime_typeLen := PaddedLen(len(mime_type) + 1)
	_reqBufLen := 8 + (4 + mime_typeLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutString(_reqBuf[l:l+(4+mime_typeLen)], mime_type, mime_typeLen)
	l += (4 + mime_typeLen)
	oob := unix.UnixRights(int(fd))
	err := i.Context().WriteMsg(_reqBuf, oob)
	return err
}

// Destroy: destroy data offer
func (i *WlDataOffer) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Finish: the offer will no longer be used
func (i *WlDataOffer) Finish() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetActions: set the available/preferred drag-and-drop actions
func (i *WlDataOffer) SetActions(dnd_actions uint32, preferred_action uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(dnd_actions))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(preferred_action))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlDataOfferOfferEvent: advertise offered mime type
type WlDataOfferOfferEvent struct {
	MimeType string
}

type WlDataOfferOfferHandler func(WlDataOfferOfferEvent)

// WlDataOfferSourceActionsEvent: notify the source-side available actions
type WlDataOfferSourceActionsEvent struct {
	SourceActions uint32
}

type WlDataOfferSourceActionsHandler func(WlDataOfferSourceActionsEvent)

// WlDataOfferActionEvent: notify the selected action
type WlDataOfferActionEvent struct {
	DndAction uint32
}

type WlDataOfferActionHandler func(WlDataOfferActionEvent)

// WlDataSource: offer to transfer data
type WlDataSource struct {
	BaseProxy
}

// NewWlDataSource creates a new WlDataSource
func NewWlDataSource(ctx *Context) *WlDataSource {
	o := &WlDataSource{}
	ctx.Register(o)
	return o
}

type WlDataSourceError uint32

const (
	WlDataSourceErrorInvalidActionMask WlDataSourceError = 0
	WlDataSourceErrorInvalidSource     WlDataSourceError = 1
)

// Offer: add an offered mime type
func (i *WlDataSource) Offer(mime_type string) error {
	const opcode = 0
	mime_typeLen := PaddedLen(len(mime_type) + 1)
	_reqBufLen := 8 + (4 + mime_typeLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutString(_reqBuf[l:l+(4+mime_typeLen)], mime_type, mime_typeLen)
	l += (4 + mime_typeLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the data source
func (i *WlDataSource) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetActions: set the available drag-and-drop actions
func (i *WlDataSource) SetActions(dnd_actions uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(dnd_actions))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlDataSourceTargetEvent: a target accepts an offered mime type
type WlDataSourceTargetEvent struct {
	MimeType *string
}

type WlDataSourceTargetHandler func(WlDataSourceTargetEvent)

// WlDataSourceSendEvent: send the data
type WlDataSourceSendEvent struct {
	MimeType string
	Fd       uintptr
}

type WlDataSourceSendHandler func(WlDataSourceSendEvent)

// WlDataSourceCancelledEvent: selection was cancelled
type WlDataSourceCancelledEvent struct {
}

type WlDataSourceCancelledHandler func(WlDataSourceCancelledEvent)

// WlDataSourceDndDropPerformedEvent: the drag-and-drop operation physically finished
type WlDataSourceDndDropPerformedEvent struct {
}

type WlDataSourceDndDropPerformedHandler func(WlDataSourceDndDropPerformedEvent)

// WlDataSourceDndFinishedEvent: the drag-and-drop operation concluded
type WlDataSourceDndFinishedEvent struct {
}

type WlDataSourceDndFinishedHandler func(WlDataSourceDndFinishedEvent)

// WlDataSourceActionEvent: notify the selected action
type WlDataSourceActionEvent struct {
	DndAction uint32
}

type WlDataSourceActionHandler func(WlDataSourceActionEvent)

// WlDataDevice: data transfer device
type WlDataDevice struct {
	BaseProxy
}

// NewWlDataDevice creates a new WlDataDevice
func NewWlDataDevice(ctx *Context) *WlDataDevice {
	o := &WlDataDevice{}
	ctx.Register(o)
	return o
}

type WlDataDeviceError uint32

const (
	WlDataDeviceErrorRole       WlDataDeviceError = 0
	WlDataDeviceErrorUsedSource WlDataDeviceError = 1
)

// StartDrag: start drag-and-drop operation
func (i *WlDataDevice) StartDrag(source *WlDataSource, origin *WlSurface, icon *WlSurface, serial uint32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if source == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], source.ID())
		l += 4
	}
	PutUint32(_reqBuf[l:l+4], origin.ID())
	l += 4
	if icon == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], icon.ID())
		l += 4
	}
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSelection: copy data to the selection
func (i *WlDataDevice) SetSelection(source *WlDataSource, serial uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if source == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], source.ID())
		l += 4
	}
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Release: destroy data device
func (i *WlDataDevice) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlDataDeviceDataOfferEvent: introduce a new wl_data_offer
type WlDataDeviceDataOfferEvent struct {
	Id *WlDataOffer
}

type WlDataDeviceDataOfferHandler func(WlDataDeviceDataOfferEvent)

// WlDataDeviceEnterEvent: initiate drag-and-drop session
type WlDataDeviceEnterEvent struct {
	Serial  uint32
	Surface *WlSurface
	X       float64
	Y       float64
	Id      *WlDataOffer
}

type WlDataDeviceEnterHandler func(WlDataDeviceEnterEvent)

// WlDataDeviceLeaveEvent: end drag-and-drop session
type WlDataDeviceLeaveEvent struct {
}

type WlDataDeviceLeaveHandler func(WlDataDeviceLeaveEvent)

// WlDataDeviceMotionEvent: drag-and-drop session motion
type WlDataDeviceMotionEvent struct {
	Time uint32
	X    float64
	Y    float64
}

type WlDataDeviceMotionHandler func(WlDataDeviceMotionEvent)

// WlDataDeviceDropEvent: end drag-and-drop session successfully
type WlDataDeviceDropEvent struct {
}

type WlDataDeviceDropHandler func(WlDataDeviceDropEvent)

// WlDataDeviceSelectionEvent: advertise new selection
type WlDataDeviceSelectionEvent struct {
	Id *WlDataOffer
}

type WlDataDeviceSelectionHandler func(WlDataDeviceSelectionEvent)

// WlDataDeviceManager: data transfer interface
type WlDataDeviceManager struct {
	BaseProxy
}

// NewWlDataDeviceManager creates a new WlDataDeviceManager
func NewWlDataDeviceManager(ctx *Context) *WlDataDeviceManager {
	o := &WlDataDeviceManager{}
	ctx.Register(o)
	return o
}

// WlDataDeviceManagerDndAction: drag and drop actions
type WlDataDeviceManagerDndAction uint32

const (
	WlDataDeviceManagerDndActionNone WlDataDeviceManagerDndAction = 0
	WlDataDeviceManagerDndActionCopy WlDataDeviceManagerDndAction = 1
	WlDataDeviceManagerDndActionMove WlDataDeviceManagerDndAction = 2
	WlDataDeviceManagerDndActionAsk  WlDataDeviceManagerDndAction = 4
)

// CreateDataSource: create a new data source
func (i *WlDataDeviceManager) CreateDataSource() (*WlDataSource, error) {
	id := NewWlDataSource(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetDataDevice: create a new data device
func (i *WlDataDeviceManager) GetDataDevice(seat *WlSeat) (*WlDataDevice, error) {
	id := NewWlDataDevice(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WlShell: create desktop-style surfaces
type WlShell struct {
	BaseProxy
}

// NewWlShell creates a new WlShell
func NewWlShell(ctx *Context) *WlShell {
	o := &WlShell{}
	ctx.Register(o)
	return o
}

type WlShellError uint32

const (
	WlShellErrorRole WlShellError = 0
)

// GetShellSurface: create a shell surface from a surface
func (i *WlShell) GetShellSurface(surface *WlSurface) (*WlShellSurface, error) {
	id := NewWlShellSurface(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WlShellSurface: desktop-style metadata interface
type WlShellSurface struct {
	BaseProxy
}

// NewWlShellSurface creates a new WlShellSurface
func NewWlShellSurface(ctx *Context) *WlShellSurface {
	o := &WlShellSurface{}
	ctx.Register(o)
	return o
}

// WlShellSurfaceResize: edge values for resizing
type WlShellSurfaceResize uint32

const (
	WlShellSurfaceResizeNone        WlShellSurfaceResize = 0
	WlShellSurfaceResizeTop         WlShellSurfaceResize = 1
	WlShellSurfaceResizeBottom      WlShellSurfaceResize = 2
	WlShellSurfaceResizeLeft        WlShellSurfaceResize = 4
	WlShellSurfaceResizeTopLeft     WlShellSurfaceResize = 5
	WlShellSurfaceResizeBottomLeft  WlShellSurfaceResize = 6
	WlShellSurfaceResizeRight       WlShellSurfaceResize = 8
	WlShellSurfaceResizeTopRight    WlShellSurfaceResize = 9
	WlShellSurfaceResizeBottomRight WlShellSurfaceResize = 10
)

// WlShellSurfaceTransient: details of transient behaviour
type WlShellSurfaceTransient uint32

const (
	WlShellSurfaceTransientInactive WlShellSurfaceTransient = 0x1
)

// WlShellSurfaceFullscreenMethod: different method to set the surface fullscreen
type WlShellSurfaceFullscreenMethod uint32

const (
	WlShellSurfaceFullscreenMethodDefault WlShellSurfaceFullscreenMethod = 0
	WlShellSurfaceFullscreenMethodScale   WlShellSurfaceFullscreenMethod = 1
	WlShellSurfaceFullscreenMethodDriver  WlShellSurfaceFullscreenMethod = 2
	WlShellSurfaceFullscreenMethodFill    WlShellSurfaceFullscreenMethod = 3
)

// Pong: respond to a ping event
func (i *WlShellSurface) Pong(serial uint32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Move: start an interactive move
func (i *WlShellSurface) Move(seat *WlSeat, serial uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Resize: start an interactive resize
func (i *WlShellSurface) Resize(seat *WlSeat, serial uint32, edges uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(edges))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetToplevel: make the surface a toplevel surface
func (i *WlShellSurface) SetToplevel() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTransient: make the surface a transient surface
func (i *WlShellSurface) SetTransient(parent *WlSurface, x int32, y int32, flags uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], parent.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(flags))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetFullscreen: make the surface a fullscreen surface
func (i *WlShellSurface) SetFullscreen(method uint32, framerate uint32, output *WlOutput) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(method))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(framerate))
	l += 4
	if output == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], output.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPopup: make the surface a popup surface
func (i *WlShellSurface) SetPopup(seat *WlSeat, serial uint32, parent *WlSurface, x int32, y int32, flags uint32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	PutUint32(_reqBuf[l:l+4], parent.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(flags))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaximized: make the surface a maximized surface
func (i *WlShellSurface) SetMaximized(output *WlOutput) error {
	const opcode = 7
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if output == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], output.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTitle: set surface title
func (i *WlShellSurface) SetTitle(title string) error {
	const opcode = 8
	titleLen := PaddedLen(len(title) + 1)
	_reqBufLen := 8 + (4 + titleLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutString(_reqBuf[l:l+(4+titleLen)], title, titleLen)
	l += (4 + titleLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetClass: set surface class
func (i *WlShellSurface) SetClass(class_ string) error {
	const opcode = 9
	class_Len := PaddedLen(len(class_) + 1)
	_reqBufLen := 8 + (4 + class_Len)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutString(_reqBuf[l:l+(4+class_Len)], class_, class_Len)
	l += (4 + class_Len)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// WlShellSurfacePingEvent: ping client
type WlShellSurfacePingEvent struct {
	Serial uint32
}

type WlShellSurfacePingHandler func(WlShellSurfacePingEvent)

// WlShellSurfaceConfigureEvent: suggest resize
type WlShellSurfaceConfigureEvent struct {
	Edges  uint32
	Width  int32
	Height int32
}

type WlShellSurfaceConfigureHandler func(WlShellSurfaceConfigureEvent)

// WlShellSurfacePopupDoneEvent: popup interaction is done
type WlShellSurfacePopupDoneEvent struct {
}

type WlShellSurfacePopupDoneHandler func(WlShellSurfacePopupDoneEvent)

// WlSurface: an onscreen surface
type WlSurface struct {
	BaseProxy
}

// NewWlSurface creates a new WlSurface
func NewWlSurface(ctx *Context) *WlSurface {
	o := &WlSurface{}
	ctx.Register(o)
	return o
}

// WlSurfaceError: wl_surface error values
type WlSurfaceError uint32

const (
	WlSurfaceErrorInvalidScale      WlSurfaceError = 0
	WlSurfaceErrorInvalidTransform  WlSurfaceError = 1
	WlSurfaceErrorInvalidSize       WlSurfaceError = 2
	WlSurfaceErrorInvalidOffset     WlSurfaceError = 3
	WlSurfaceErrorDefunctRoleObject WlSurfaceError = 4
)

// Destroy: delete surface
func (i *WlSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Attach: set the surface contents
func (i *WlSurface) Attach(buffer *WlBuffer, x int32, y int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if buffer == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], buffer.ID())
		l += 4
	}
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Damage: mark part of the surface damaged
func (i *WlSurface) Damage(x int32, y int32, width int32, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Frame: request a frame throttling hint
func (i *WlSurface) Frame() (*WlCallback, error) {
	callback := NewWlCallback(i.Context())
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], callback.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return callback, err
}

// SetOpaqueRegion: set opaque region
func (i *WlSurface) SetOpaqueRegion(region *WlRegion) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetInputRegion: set input region
func (i *WlSurface) SetInputRegion(region *WlRegion) error {
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Commit: commit pending surface state
func (i *WlSurface) Commit() error {
	const opcode = 6
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetBufferTransform: sets the buffer transformation
func (i *WlSurface) SetBufferTransform(transform int32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(transform))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetBufferScale: sets the buffer scaling factor
func (i *WlSurface) SetBufferScale(scale int32) error {
	const opcode = 8
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(scale))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DamageBuffer: mark part of the surface damaged using buffer coordinates
func (i *WlSurface) DamageBuffer(x int32, y int32, width int32, height int32) error {
	const opcode = 9
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Offset: set the surface contents offset
func (i *WlSurface) Offset(x int32, y int32) error {
	const opcode = 10
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlSurfaceEnterEvent: surface enters an output
type WlSurfaceEnterEvent struct {
	Output *WlOutput
}

type WlSurfaceEnterHandler func(WlSurfaceEnterEvent)

// WlSurfaceLeaveEvent: surface leaves an output
type WlSurfaceLeaveEvent struct {
	Output *WlOutput
}

type WlSurfaceLeaveHandler func(WlSurfaceLeaveEvent)

// WlSurfacePreferredBufferScaleEvent: preferred buffer scale for the surface
type WlSurfacePreferredBufferScaleEvent struct {
	Factor int32
}

type WlSurfacePreferredBufferScaleHandler func(WlSurfacePreferredBufferScaleEvent)

// WlSurfacePreferredBufferTransformEvent: preferred buffer transform for the surface
type WlSurfacePreferredBufferTransformEvent struct {
	Transform uint32
}

type WlSurfacePreferredBufferTransformHandler func(WlSurfacePreferredBufferTransformEvent)

// WlSeat: group of input devices
type WlSeat struct {
	BaseProxy
}

// NewWlSeat creates a new WlSeat
func NewWlSeat(ctx *Context) *WlSeat {
	o := &WlSeat{}
	ctx.Register(o)
	return o
}

// WlSeatCapability: seat capability bitmask
type WlSeatCapability uint32

const (
	WlSeatCapabilityPointer  WlSeatCapability = 1
	WlSeatCapabilityKeyboard WlSeatCapability = 2
	WlSeatCapabilityTouch    WlSeatCapability = 4
)

// WlSeatError: wl_seat error values
type WlSeatError uint32

const (
	WlSeatErrorMissingCapability WlSeatError = 0
)

// GetPointer: return pointer object
func (i *WlSeat) GetPointer() (*WlPointer, error) {
	id := NewWlPointer(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetKeyboard: return keyboard object
func (i *WlSeat) GetKeyboard() (*WlKeyboard, error) {
	id := NewWlKeyboard(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetTouch: return touch object
func (i *WlSeat) GetTouch() (*WlTouch, error) {
	id := NewWlTouch(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Release: release the seat object
func (i *WlSeat) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlSeatCapabilitiesEvent: seat capabilities changed
type WlSeatCapabilitiesEvent struct {
	Capabilities uint32
}

type WlSeatCapabilitiesHandler func(WlSeatCapabilitiesEvent)

// WlSeatNameEvent: unique identifier for this seat
type WlSeatNameEvent struct {
	Name string
}

type WlSeatNameHandler func(WlSeatNameEvent)

// WlPointer: pointer input device
type WlPointer struct {
	BaseProxy
}

// NewWlPointer creates a new WlPointer
func NewWlPointer(ctx *Context) *WlPointer {
	o := &WlPointer{}
	ctx.Register(o)
	return o
}

type WlPointerError uint32

const (
	WlPointerErrorRole WlPointerError = 0
)

// WlPointerButtonState: physical button state
type WlPointerButtonState uint32

const (
	WlPointerButtonStateReleased WlPointerButtonState = 0
	WlPointerButtonStatePressed  WlPointerButtonState = 1
)

// WlPointerAxis: axis types
type WlPointerAxis uint32

const (
	WlPointerAxisVerticalScroll   WlPointerAxis = 0
	WlPointerAxisHorizontalScroll WlPointerAxis = 1
)

// WlPointerAxisSource: axis source types
type WlPointerAxisSource uint32

const (
	WlPointerAxisSourceWheel      WlPointerAxisSource = 0
	WlPointerAxisSourceFinger     WlPointerAxisSource = 1
	WlPointerAxisSourceContinuous WlPointerAxisSource = 2
	WlPointerAxisSourceWheelTilt  WlPointerAxisSource = 3
)

// WlPointerAxisRelativeDirection: axis relative direction
type WlPointerAxisRelativeDirection uint32

const (
	WlPointerAxisRelativeDirectionIdentical WlPointerAxisRelativeDirection = 0
	WlPointerAxisRelativeDirectionInverted  WlPointerAxisRelativeDirection = 1
)

// SetCursor: set the pointer surface
func (i *WlPointer) SetCursor(serial uint32, surface *WlSurface, hotspot_x int32, hotspot_y int32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	if surface == nil {
		PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		PutUint32(_reqBuf[l:l+4], surface.ID())
		l += 4
	}
	PutUint32(_reqBuf[l:l+4], uint32(hotspot_x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(hotspot_y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Release: release the pointer object
func (i *WlPointer) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlPointerEnterEvent: enter event
type WlPointerEnterEvent struct {
	Serial   uint32
	Surface  *WlSurface
	SurfaceX float64
	SurfaceY float64
}

type WlPointerEnterHandler func(WlPointerEnterEvent)

// WlPointerLeaveEvent: leave event
type WlPointerLeaveEvent struct {
	Serial  uint32
	Surface *WlSurface
}

type WlPointerLeaveHandler func(WlPointerLeaveEvent)

// WlPointerMotionEvent: pointer motion event
type WlPointerMotionEvent struct {
	Time     uint32
	SurfaceX float64
	SurfaceY float64
}

type WlPointerMotionHandler func(WlPointerMotionEvent)

// WlPointerButtonEvent: pointer button event
type WlPointerButtonEvent struct {
	Serial uint32
	Time   uint32
	Button uint32
	State  uint32
}

type WlPointerButtonHandler func(WlPointerButtonEvent)

// WlPointerAxisEvent: axis event
type WlPointerAxisEvent struct {
	Time  uint32
	Axis  uint32
	Value float64
}

type WlPointerAxisHandler func(WlPointerAxisEvent)

// WlPointerFrameEvent: end of a pointer event sequence
type WlPointerFrameEvent struct {
}

type WlPointerFrameHandler func(WlPointerFrameEvent)

// WlPointerAxisSourceEvent: axis source event
type WlPointerAxisSourceEvent struct {
	AxisSource uint32
}

type WlPointerAxisSourceHandler func(WlPointerAxisSourceEvent)

// WlPointerAxisStopEvent: axis stop event
type WlPointerAxisStopEvent struct {
	Time uint32
	Axis uint32
}

type WlPointerAxisStopHandler func(WlPointerAxisStopEvent)

// WlPointerAxisDiscreteEvent: axis click event
type WlPointerAxisDiscreteEvent struct {
	Axis     uint32
	Discrete int32
}

type WlPointerAxisDiscreteHandler func(WlPointerAxisDiscreteEvent)

// WlPointerAxisValue120Event: axis high-resolution scroll event
type WlPointerAxisValue120Event struct {
	Axis     uint32
	Value120 int32
}

type WlPointerAxisValue120Handler func(WlPointerAxisValue120Event)

// WlPointerAxisRelativeDirectionEvent: axis relative physical direction event
type WlPointerAxisRelativeDirectionEvent struct {
	Axis      uint32
	Direction uint32
}

type WlPointerAxisRelativeDirectionHandler func(WlPointerAxisRelativeDirectionEvent)

// WlKeyboard: keyboard input device
type WlKeyboard struct {
	BaseProxy
}

// NewWlKeyboard creates a new WlKeyboard
func NewWlKeyboard(ctx *Context) *WlKeyboard {
	o := &WlKeyboard{}
	ctx.Register(o)
	return o
}

// WlKeyboardKeymapFormat: keyboard mapping format
type WlKeyboardKeymapFormat uint32

const (
	WlKeyboardKeymapFormatNoKeymap WlKeyboardKeymapFormat = 0
	WlKeyboardKeymapFormatXkbV1    WlKeyboardKeymapFormat = 1
)

// WlKeyboardKeyState: physical key state
type WlKeyboardKeyState uint32

const (
	WlKeyboardKeyStateReleased WlKeyboardKeyState = 0
	WlKeyboardKeyStatePressed  WlKeyboardKeyState = 1
	WlKeyboardKeyStateRepeated WlKeyboardKeyState = 2
)

// Release: release the keyboard object
func (i *WlKeyboard) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlKeyboardKeymapEvent: keyboard mapping
type WlKeyboardKeymapEvent struct {
	Format uint32
	Fd     uintptr
	Size   uint32
}

type WlKeyboardKeymapHandler func(WlKeyboardKeymapEvent)

// WlKeyboardEnterEvent: enter event
type WlKeyboardEnterEvent struct {
	Serial  uint32
	Surface *WlSurface
	Keys    []byte
}

type WlKeyboardEnterHandler func(WlKeyboardEnterEvent)

// WlKeyboardLeaveEvent: leave event
type WlKeyboardLeaveEvent struct {
	Serial  uint32
	Surface *WlSurface
}

type WlKeyboardLeaveHandler func(WlKeyboardLeaveEvent)

// WlKeyboardKeyEvent: key event
type WlKeyboardKeyEvent struct {
	Serial uint32
	Time   uint32
	Key    uint32
	State  uint32
}

type WlKeyboardKeyHandler func(WlKeyboardKeyEvent)

// WlKeyboardModifiersEvent: modifier and group state
type WlKeyboardModifiersEvent struct {
	Serial        uint32
	ModsDepressed uint32
	ModsLatched   uint32
	ModsLocked    uint32
	Group         uint32
}

type WlKeyboardModifiersHandler func(WlKeyboardModifiersEvent)

// WlKeyboardRepeatInfoEvent: repeat rate and delay
type WlKeyboardRepeatInfoEvent struct {
	Rate  int32
	Delay int32
}

type WlKeyboardRepeatInfoHandler func(WlKeyboardRepeatInfoEvent)

// WlTouch: touchscreen input device
type WlTouch struct {
	BaseProxy
}

// NewWlTouch creates a new WlTouch
func NewWlTouch(ctx *Context) *WlTouch {
	o := &WlTouch{}
	ctx.Register(o)
	return o
}

// Release: release the touch object
func (i *WlTouch) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlTouchDownEvent: touch down event and beginning of a touch sequence
type WlTouchDownEvent struct {
	Serial  uint32
	Time    uint32
	Surface *WlSurface
	Id      int32
	X       float64
	Y       float64
}

type WlTouchDownHandler func(WlTouchDownEvent)

// WlTouchUpEvent: end of a touch event sequence
type WlTouchUpEvent struct {
	Serial uint32
	Time   uint32
	Id     int32
}

type WlTouchUpHandler func(WlTouchUpEvent)

// WlTouchMotionEvent: update of touch point coordinates
type WlTouchMotionEvent struct {
	Time uint32
	Id   int32
	X    float64
	Y    float64
}

type WlTouchMotionHandler func(WlTouchMotionEvent)

// WlTouchFrameEvent: end of touch frame event
type WlTouchFrameEvent struct {
}

type WlTouchFrameHandler func(WlTouchFrameEvent)

// WlTouchCancelEvent: touch session cancelled
type WlTouchCancelEvent struct {
}

type WlTouchCancelHandler func(WlTouchCancelEvent)

// WlTouchShapeEvent: update shape of touch point
type WlTouchShapeEvent struct {
	Id    int32
	Major float64
	Minor float64
}

type WlTouchShapeHandler func(WlTouchShapeEvent)

// WlTouchOrientationEvent: update orientation of touch point
type WlTouchOrientationEvent struct {
	Id          int32
	Orientation float64
}

type WlTouchOrientationHandler func(WlTouchOrientationEvent)

// WlOutput: compositor output region
type WlOutput struct {
	BaseProxy
}

// NewWlOutput creates a new WlOutput
func NewWlOutput(ctx *Context) *WlOutput {
	o := &WlOutput{}
	ctx.Register(o)
	return o
}

// WlOutputSubpixel: subpixel geometry information
type WlOutputSubpixel uint32

const (
	WlOutputSubpixelUnknown       WlOutputSubpixel = 0
	WlOutputSubpixelNone          WlOutputSubpixel = 1
	WlOutputSubpixelHorizontalRgb WlOutputSubpixel = 2
	WlOutputSubpixelHorizontalBgr WlOutputSubpixel = 3
	WlOutputSubpixelVerticalRgb   WlOutputSubpixel = 4
	WlOutputSubpixelVerticalBgr   WlOutputSubpixel = 5
)

// WlOutputTransform: transformation applied to buffer contents
type WlOutputTransform uint32

const (
	WlOutputTransformNormal     WlOutputTransform = 0
	WlOutputTransform90         WlOutputTransform = 1
	WlOutputTransform180        WlOutputTransform = 2
	WlOutputTransform270        WlOutputTransform = 3
	WlOutputTransformFlipped    WlOutputTransform = 4
	WlOutputTransformFlipped90  WlOutputTransform = 5
	WlOutputTransformFlipped180 WlOutputTransform = 6
	WlOutputTransformFlipped270 WlOutputTransform = 7
)

// WlOutputMode: mode information
type WlOutputMode uint32

const (
	WlOutputModeCurrent   WlOutputMode = 0x1
	WlOutputModePreferred WlOutputMode = 0x2
)

// Release: release the output object
func (i *WlOutput) Release() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlOutputGeometryEvent: properties of the output
type WlOutputGeometryEvent struct {
	X              int32
	Y              int32
	PhysicalWidth  int32
	PhysicalHeight int32
	Subpixel       int32
	Make           string
	Model          string
	Transform      int32
}

type WlOutputGeometryHandler func(WlOutputGeometryEvent)

// WlOutputModeEvent: advertise available modes for the output
type WlOutputModeEvent struct {
	Flags   uint32
	Width   int32
	Height  int32
	Refresh int32
}

type WlOutputModeHandler func(WlOutputModeEvent)

// WlOutputDoneEvent: sent all information about output
type WlOutputDoneEvent struct {
}

type WlOutputDoneHandler func(WlOutputDoneEvent)

// WlOutputScaleEvent: output scaling properties
type WlOutputScaleEvent struct {
	Factor int32
}

type WlOutputScaleHandler func(WlOutputScaleEvent)

// WlOutputNameEvent: name of this output
type WlOutputNameEvent struct {
	Name string
}

type WlOutputNameHandler func(WlOutputNameEvent)

// WlOutputDescriptionEvent: human-readable description of this output
type WlOutputDescriptionEvent struct {
	Description string
}

type WlOutputDescriptionHandler func(WlOutputDescriptionEvent)

// WlRegion: region interface
type WlRegion struct {
	BaseProxy
}

// NewWlRegion creates a new WlRegion
func NewWlRegion(ctx *Context) *WlRegion {
	o := &WlRegion{}
	ctx.Register(o)
	return o
}

// Destroy: destroy region
func (i *WlRegion) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Add: add rectangle to region
func (i *WlRegion) Add(x int32, y int32, width int32, height int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Subtract: subtract rectangle from region
func (i *WlRegion) Subtract(x int32, y int32, width int32, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlSubcompositor: sub-surface compositing
type WlSubcompositor struct {
	BaseProxy
}

// NewWlSubcompositor creates a new WlSubcompositor
func NewWlSubcompositor(ctx *Context) *WlSubcompositor {
	o := &WlSubcompositor{}
	ctx.Register(o)
	return o
}

type WlSubcompositorError uint32

const (
	WlSubcompositorErrorBadSurface WlSubcompositorError = 0
	WlSubcompositorErrorBadParent  WlSubcompositorError = 1
)

// Destroy: unbind from the subcompositor interface
func (i *WlSubcompositor) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSubsurface: give a surface the role sub-surface
func (i *WlSubcompositor) GetSubsurface(surface *WlSurface, parent *WlSurface) (*WlSubsurface, error) {
	id := NewWlSubsurface(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], parent.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WlSubsurface: sub-surface interface to a wl_surface
type WlSubsurface struct {
	BaseProxy
}

// NewWlSubsurface creates a new WlSubsurface
func NewWlSubsurface(ctx *Context) *WlSubsurface {
	o := &WlSubsurface{}
	ctx.Register(o)
	return o
}

type WlSubsurfaceError uint32

const (
	WlSubsurfaceErrorBadSurface WlSubsurfaceError = 0
)

// Destroy: remove sub-surface interface
func (i *WlSubsurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPosition: reposition the sub-surface
func (i *WlSubsurface) SetPosition(x int32, y int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// PlaceAbove: restack the sub-surface
func (i *WlSubsurface) PlaceAbove(sibling *WlSurface) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], sibling.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// PlaceBelow: restack the sub-surface
func (i *WlSubsurface) PlaceBelow(sibling *WlSurface) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], sibling.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSync: set sub-surface to synchronized mode
func (i *WlSubsurface) SetSync() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetDesync: set sub-surface to desynchronized mode
func (i *WlSubsurface) SetDesync() error {
	const opcode = 5
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WlFixes: wayland protocol fixes
type WlFixes struct {
	BaseProxy
}

// NewWlFixes creates a new WlFixes
func NewWlFixes(ctx *Context) *WlFixes {
	o := &WlFixes{}
	ctx.Register(o)
	return o
}

// Destroy: destroys this object
func (i *WlFixes) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DestroyRegistry: destroy a wl_registry
func (i *WlFixes) DestroyRegistry(registry *WlRegistry) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	PutUint32(_reqBuf[l:l+4], registry.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
