// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/text-input/text-input-unstable-v1.xml
//
// text_input_unstable_v1 Protocol Copyright:
// Copyright © 2012, 2013 Intel Corporation
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package text_input_unstable_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZwpTextInputV1: text input
type ZwpTextInputV1 struct {
	client.BaseProxy
}

// NewZwpTextInputV1 creates a new ZwpTextInputV1
func NewZwpTextInputV1(ctx *client.Context) *ZwpTextInputV1 {
	o := &ZwpTextInputV1{}
	ctx.Register(o)
	return o
}

// ZwpTextInputV1ContentHint: content hint
type ZwpTextInputV1ContentHint uint32

const (
	ZwpTextInputV1ContentHintNone               ZwpTextInputV1ContentHint = 0x0
	ZwpTextInputV1ContentHintDefault            ZwpTextInputV1ContentHint = 0x7
	ZwpTextInputV1ContentHintPassword           ZwpTextInputV1ContentHint = 0xc0
	ZwpTextInputV1ContentHintAutoCompletion     ZwpTextInputV1ContentHint = 0x1
	ZwpTextInputV1ContentHintAutoCorrection     ZwpTextInputV1ContentHint = 0x2
	ZwpTextInputV1ContentHintAutoCapitalization ZwpTextInputV1ContentHint = 0x4
	ZwpTextInputV1ContentHintLowercase          ZwpTextInputV1ContentHint = 0x8
	ZwpTextInputV1ContentHintUppercase          ZwpTextInputV1ContentHint = 0x10
	ZwpTextInputV1ContentHintTitlecase          ZwpTextInputV1ContentHint = 0x20
	ZwpTextInputV1ContentHintHiddenText         ZwpTextInputV1ContentHint = 0x40
	ZwpTextInputV1ContentHintSensitiveData      ZwpTextInputV1ContentHint = 0x80
	ZwpTextInputV1ContentHintLatin              ZwpTextInputV1ContentHint = 0x100
	ZwpTextInputV1ContentHintMultiline          ZwpTextInputV1ContentHint = 0x200
)

// ZwpTextInputV1ContentPurpose: content purpose
type ZwpTextInputV1ContentPurpose uint32

const (
	ZwpTextInputV1ContentPurposeNormal   ZwpTextInputV1ContentPurpose = 0
	ZwpTextInputV1ContentPurposeAlpha    ZwpTextInputV1ContentPurpose = 1
	ZwpTextInputV1ContentPurposeDigits   ZwpTextInputV1ContentPurpose = 2
	ZwpTextInputV1ContentPurposeNumber   ZwpTextInputV1ContentPurpose = 3
	ZwpTextInputV1ContentPurposePhone    ZwpTextInputV1ContentPurpose = 4
	ZwpTextInputV1ContentPurposeUrl      ZwpTextInputV1ContentPurpose = 5
	ZwpTextInputV1ContentPurposeEmail    ZwpTextInputV1ContentPurpose = 6
	ZwpTextInputV1ContentPurposeName     ZwpTextInputV1ContentPurpose = 7
	ZwpTextInputV1ContentPurposePassword ZwpTextInputV1ContentPurpose = 8
	ZwpTextInputV1ContentPurposeDate     ZwpTextInputV1ContentPurpose = 9
	ZwpTextInputV1ContentPurposeTime     ZwpTextInputV1ContentPurpose = 10
	ZwpTextInputV1ContentPurposeDatetime ZwpTextInputV1ContentPurpose = 11
	ZwpTextInputV1ContentPurposeTerminal ZwpTextInputV1ContentPurpose = 12
)

type ZwpTextInputV1PreeditStyle uint32

const (
	ZwpTextInputV1PreeditStyleDefault   ZwpTextInputV1PreeditStyle = 0
	ZwpTextInputV1PreeditStyleNone      ZwpTextInputV1PreeditStyle = 1
	ZwpTextInputV1PreeditStyleActive    ZwpTextInputV1PreeditStyle = 2
	ZwpTextInputV1PreeditStyleInactive  ZwpTextInputV1PreeditStyle = 3
	ZwpTextInputV1PreeditStyleHighlight ZwpTextInputV1PreeditStyle = 4
	ZwpTextInputV1PreeditStyleUnderline ZwpTextInputV1PreeditStyle = 5
	ZwpTextInputV1PreeditStyleSelection ZwpTextInputV1PreeditStyle = 6
	ZwpTextInputV1PreeditStyleIncorrect ZwpTextInputV1PreeditStyle = 7
)

type ZwpTextInputV1TextDirection uint32

const (
	ZwpTextInputV1TextDirectionAuto ZwpTextInputV1TextDirection = 0
	ZwpTextInputV1TextDirectionLtr  ZwpTextInputV1TextDirection = 1
	ZwpTextInputV1TextDirectionRtl  ZwpTextInputV1TextDirection = 2
)

// Activate: request activation
func (i *ZwpTextInputV1) Activate(seat *client.WlSeat, surface *client.WlSurface) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Deactivate: request deactivation
func (i *ZwpTextInputV1) Deactivate(seat *client.WlSeat) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ShowInputPanel: show input panels
func (i *ZwpTextInputV1) ShowInputPanel() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// HideInputPanel: hide input panels
func (i *ZwpTextInputV1) HideInputPanel() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Reset: reset
func (i *ZwpTextInputV1) Reset() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSurroundingText: sets the surrounding text
func (i *ZwpTextInputV1) SetSurroundingText(text string, cursor uint32, anchor uint32) error {
	const opcode = 5
	textLen := client.PaddedLen(len(text) + 1)
	_reqBufLen := 8 + (4 + textLen) + 4 + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+textLen)], text, textLen)
	l += (4 + textLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(cursor))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(anchor))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetContentType: set content purpose and hint
func (i *ZwpTextInputV1) SetContentType(hint uint32, purpose uint32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(hint))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(purpose))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

func (i *ZwpTextInputV1) SetCursorRectangle(x int32, y int32, width int32, height int32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPreferredLanguage: sets preferred language
func (i *ZwpTextInputV1) SetPreferredLanguage(language string) error {
	const opcode = 8
	languageLen := client.PaddedLen(len(language) + 1)
	_reqBufLen := 8 + (4 + languageLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+languageLen)], language, languageLen)
	l += (4 + languageLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

func (i *ZwpTextInputV1) CommitState(serial uint32) error {
	const opcode = 9
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

func (i *ZwpTextInputV1) InvokeAction(button uint32, index uint32) error {
	const opcode = 10
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(button))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(index))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTextInputV1EnterEvent: enter event
type ZwpTextInputV1EnterEvent struct {
	Surface *client.WlSurface
}

type ZwpTextInputV1EnterHandler func(ZwpTextInputV1EnterEvent)

// ZwpTextInputV1LeaveEvent: leave event
type ZwpTextInputV1LeaveEvent struct {
}

type ZwpTextInputV1LeaveHandler func(ZwpTextInputV1LeaveEvent)

// ZwpTextInputV1ModifiersMapEvent: modifiers map
type ZwpTextInputV1ModifiersMapEvent struct {
	Map []byte
}

type ZwpTextInputV1ModifiersMapHandler func(ZwpTextInputV1ModifiersMapEvent)

// ZwpTextInputV1InputPanelStateEvent: state of the input panel
type ZwpTextInputV1InputPanelStateEvent struct {
	State uint32
}

type ZwpTextInputV1InputPanelStateHandler func(ZwpTextInputV1InputPanelStateEvent)

// ZwpTextInputV1PreeditStringEvent: pre-edit
type ZwpTextInputV1PreeditStringEvent struct {
	Serial uint32
	Text   string
	Commit string
}

type ZwpTextInputV1PreeditStringHandler func(ZwpTextInputV1PreeditStringEvent)

// ZwpTextInputV1PreeditStylingEvent: pre-edit styling
type ZwpTextInputV1PreeditStylingEvent struct {
	Index  uint32
	Length uint32
	Style  uint32
}

type ZwpTextInputV1PreeditStylingHandler func(ZwpTextInputV1PreeditStylingEvent)

// ZwpTextInputV1PreeditCursorEvent: pre-edit cursor
type ZwpTextInputV1PreeditCursorEvent struct {
	Index int32
}

type ZwpTextInputV1PreeditCursorHandler func(ZwpTextInputV1PreeditCursorEvent)

// ZwpTextInputV1CommitStringEvent: commit
type ZwpTextInputV1CommitStringEvent struct {
	Serial uint32
	Text   string
}

type ZwpTextInputV1CommitStringHandler func(ZwpTextInputV1CommitStringEvent)

// ZwpTextInputV1CursorPositionEvent: set cursor to new position
type ZwpTextInputV1CursorPositionEvent struct {
	Index  int32
	Anchor int32
}

type ZwpTextInputV1CursorPositionHandler func(ZwpTextInputV1CursorPositionEvent)

// ZwpTextInputV1DeleteSurroundingTextEvent: delete surrounding text
type ZwpTextInputV1DeleteSurroundingTextEvent struct {
	Index  int32
	Length uint32
}

type ZwpTextInputV1DeleteSurroundingTextHandler func(ZwpTextInputV1DeleteSurroundingTextEvent)

// ZwpTextInputV1KeysymEvent: keysym
type ZwpTextInputV1KeysymEvent struct {
	Serial    uint32
	Time      uint32
	Sym       uint32
	State     uint32
	Modifiers uint32
}

type ZwpTextInputV1KeysymHandler func(ZwpTextInputV1KeysymEvent)

// ZwpTextInputV1LanguageEvent: language
type ZwpTextInputV1LanguageEvent struct {
	Serial   uint32
	Language string
}

type ZwpTextInputV1LanguageHandler func(ZwpTextInputV1LanguageEvent)

// ZwpTextInputV1TextDirectionEvent: text direction
type ZwpTextInputV1TextDirectionEvent struct {
	Serial    uint32
	Direction uint32
}

type ZwpTextInputV1TextDirectionHandler func(ZwpTextInputV1TextDirectionEvent)

// ZwpTextInputManagerV1: text input manager
type ZwpTextInputManagerV1 struct {
	client.BaseProxy
}

// NewZwpTextInputManagerV1 creates a new ZwpTextInputManagerV1
func NewZwpTextInputManagerV1(ctx *client.Context) *ZwpTextInputManagerV1 {
	o := &ZwpTextInputManagerV1{}
	ctx.Register(o)
	return o
}

// CreateTextInput: create text input
func (i *ZwpTextInputManagerV1) CreateTextInput() (*ZwpTextInputV1, error) {
	id := NewZwpTextInputV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}
