// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/xdg-foreign/xdg-foreign-unstable-v1.xml
//
// xdg_foreign_unstable_v1 Protocol Copyright:
// Copyright © 2015-2016 Red Hat Inc.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_foreign_unstable_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZxdgExporterV1: interface for exporting surfaces
type ZxdgExporterV1 struct {
	client.BaseProxy
}

// NewZxdgExporterV1 creates a new ZxdgExporterV1
func NewZxdgExporterV1(ctx *client.Context) *ZxdgExporterV1 {
	o := &ZxdgExporterV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the xdg_exporter object
func (i *ZxdgExporterV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Export: export a surface
func (i *ZxdgExporterV1) Export(surface *client.WlSurface) (*ZxdgExportedV1, error) {
	id := NewZxdgExportedV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ZxdgImporterV1: interface for importing surfaces
type ZxdgImporterV1 struct {
	client.BaseProxy
}

// NewZxdgImporterV1 creates a new ZxdgImporterV1
func NewZxdgImporterV1(ctx *client.Context) *ZxdgImporterV1 {
	o := &ZxdgImporterV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the xdg_importer object
func (i *ZxdgImporterV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Import: import a surface
func (i *ZxdgImporterV1) Import(handle string) (*ZxdgImportedV1, error) {
	id := NewZxdgImportedV1(i.Context())
	const opcode = 1
	handleLen := client.PaddedLen(len(handle) + 1)
	_reqBufLen := 8 + 4 + (4 + handleLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutString(_reqBuf[l:l+(4+handleLen)], handle, handleLen)
	l += (4 + handleLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return id, err
}

// ZxdgExportedV1: an exported surface handle
type ZxdgExportedV1 struct {
	client.BaseProxy
}

// NewZxdgExportedV1 creates a new ZxdgExportedV1
func NewZxdgExportedV1(ctx *client.Context) *ZxdgExportedV1 {
	o := &ZxdgExportedV1{}
	ctx.Register(o)
	return o
}

// Destroy: unexport the exported surface
func (i *ZxdgExportedV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgExportedV1HandleEvent: the exported surface handle
type ZxdgExportedV1HandleEvent struct {
	Handle string
}

type ZxdgExportedV1HandleHandler func(ZxdgExportedV1HandleEvent)

// ZxdgImportedV1: an imported surface handle
type ZxdgImportedV1 struct {
	client.BaseProxy
}

// NewZxdgImportedV1 creates a new ZxdgImportedV1
func NewZxdgImportedV1(ctx *client.Context) *ZxdgImportedV1 {
	o := &ZxdgImportedV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the xdg_imported object
func (i *ZxdgImportedV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetParentOf: set as the parent of some surface
func (i *ZxdgImportedV1) SetParentOf(surface *client.WlSurface) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgImportedV1DestroyedEvent: the imported surface handle has been destroyed
type ZxdgImportedV1DestroyedEvent struct {
}

type ZxdgImportedV1DestroyedHandler func(ZxdgImportedV1DestroyedEvent)
