// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/linux-explicit-synchronization/linux-explicit-synchronization-unstable-v1.xml
//
// zwp_linux_explicit_synchronization_unstable_v1 Protocol Copyright:
// Copyright 2016 The Chromium Authors.
// Copyright 2017 Intel Corporation
// Copyright 2018 Collabora, Ltd
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package linux_explicit_synchronization_unstable_v1

import (
	"github.com/tri2820/cheese/protocols/client"
	"golang.org/x/sys/unix"
)

// ZwpLinuxExplicitSynchronizationV1: protocol for providing explicit synchronization
type ZwpLinuxExplicitSynchronizationV1 struct {
	client.BaseProxy
}

// NewZwpLinuxExplicitSynchronizationV1 creates a new ZwpLinuxExplicitSynchronizationV1
func NewZwpLinuxExplicitSynchronizationV1(ctx *client.Context) *ZwpLinuxExplicitSynchronizationV1 {
	o := &ZwpLinuxExplicitSynchronizationV1{}
	ctx.Register(o)
	return o
}

type ZwpLinuxExplicitSynchronizationV1Error uint32

const (
	ZwpLinuxExplicitSynchronizationV1ErrorSynchronizationExists ZwpLinuxExplicitSynchronizationV1Error = 0
)

// Destroy: destroy explicit synchronization factory object
func (i *ZwpLinuxExplicitSynchronizationV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetSynchronization: extend surface interface for explicit synchronization
func (i *ZwpLinuxExplicitSynchronizationV1) GetSynchronization(surface *client.WlSurface) (*ZwpLinuxSurfaceSynchronizationV1, error) {
	id := NewZwpLinuxSurfaceSynchronizationV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ZwpLinuxSurfaceSynchronizationV1: per-surface explicit synchronization support
type ZwpLinuxSurfaceSynchronizationV1 struct {
	client.BaseProxy
}

// NewZwpLinuxSurfaceSynchronizationV1 creates a new ZwpLinuxSurfaceSynchronizationV1
func NewZwpLinuxSurfaceSynchronizationV1(ctx *client.Context) *ZwpLinuxSurfaceSynchronizationV1 {
	o := &ZwpLinuxSurfaceSynchronizationV1{}
	ctx.Register(o)
	return o
}

type ZwpLinuxSurfaceSynchronizationV1Error uint32

const (
	ZwpLinuxSurfaceSynchronizationV1ErrorInvalidFence      ZwpLinuxSurfaceSynchronizationV1Error = 0
	ZwpLinuxSurfaceSynchronizationV1ErrorDuplicateFence    ZwpLinuxSurfaceSynchronizationV1Error = 1
	ZwpLinuxSurfaceSynchronizationV1ErrorDuplicateRelease  ZwpLinuxSurfaceSynchronizationV1Error = 2
	ZwpLinuxSurfaceSynchronizationV1ErrorNoSurface         ZwpLinuxSurfaceSynchronizationV1Error = 3
	ZwpLinuxSurfaceSynchronizationV1ErrorUnsupportedBuffer ZwpLinuxSurfaceSynchronizationV1Error = 4
	ZwpLinuxSurfaceSynchronizationV1ErrorNoBuffer          ZwpLinuxSurfaceSynchronizationV1Error = 5
)

// Destroy: destroy synchronization object
func (i *ZwpLinuxSurfaceSynchronizationV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetAcquireFence: set the acquire fence
func (i *ZwpLinuxSurfaceSynchronizationV1) SetAcquireFence(fd uintptr) error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	oob := unix.UnixRights(int(fd))
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return err
}

// GetRelease: release fence for last-attached buffer
func (i *ZwpLinuxSurfaceSynchronizationV1) GetRelease() (*ZwpLinuxBufferReleaseV1, error) {
	release := NewZwpLinuxBufferReleaseV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], release.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return release, err
}

// ZwpLinuxBufferReleaseV1: buffer release explicit synchronization
type ZwpLinuxBufferReleaseV1 struct {
	client.BaseProxy
}

// NewZwpLinuxBufferReleaseV1 creates a new ZwpLinuxBufferReleaseV1
func NewZwpLinuxBufferReleaseV1(ctx *client.Context) *ZwpLinuxBufferReleaseV1 {
	o := &ZwpLinuxBufferReleaseV1{}
	ctx.Register(o)
	return o
}

// ZwpLinuxBufferReleaseV1FencedReleaseEvent: release buffer with fence
type ZwpLinuxBufferReleaseV1FencedReleaseEvent struct {
	Fence uintptr
}

type ZwpLinuxBufferReleaseV1FencedReleaseHandler func(ZwpLinuxBufferReleaseV1FencedReleaseEvent)

// ZwpLinuxBufferReleaseV1ImmediateReleaseEvent: release buffer immediately
type ZwpLinuxBufferReleaseV1ImmediateReleaseEvent struct {
}

type ZwpLinuxBufferReleaseV1ImmediateReleaseHandler func(ZwpLinuxBufferReleaseV1ImmediateReleaseEvent)
