// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/ext-image-copy-capture/ext-image-copy-capture-v1.xml
//
// ext_image_copy_capture_v1 Protocol Copyright:
// Copyright © 2021-2023 Andri Yngvason
// Copyright © 2024 Simon Ser
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package ext_image_copy_capture_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ExtImageCopyCaptureManagerV1: manager to inform clients and begin capturing
type ExtImageCopyCaptureManagerV1 struct {
	client.BaseProxy
}

// NewExtImageCopyCaptureManagerV1 creates a new ExtImageCopyCaptureManagerV1
func NewExtImageCopyCaptureManagerV1(ctx *client.Context) *ExtImageCopyCaptureManagerV1 {
	o := &ExtImageCopyCaptureManagerV1{}
	ctx.Register(o)
	return o
}

type ExtImageCopyCaptureManagerV1Error uint32

const (
	ExtImageCopyCaptureManagerV1ErrorInvalidOption ExtImageCopyCaptureManagerV1Error = 1
)

type ExtImageCopyCaptureManagerV1Options uint32

const (
	ExtImageCopyCaptureManagerV1OptionsPaintCursors ExtImageCopyCaptureManagerV1Options = 1
)

// CreateSession: capture an image capture source
func (i *ExtImageCopyCaptureManagerV1) CreateSession(source client.Proxy, options ExtImageCopyCaptureManagerV1Options) (*ExtImageCopyCaptureSessionV1, error) {
	session := NewExtImageCopyCaptureSessionV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(options))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

// CreatePointerCursorSession: capture the pointer cursor of an image capture source
func (i *ExtImageCopyCaptureManagerV1) CreatePointerCursorSession(source client.Proxy, pointer *client.WlPointer) (*ExtImageCopyCaptureCursorSessionV1, error) {
	session := NewExtImageCopyCaptureCursorSessionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

// Destroy: destroy the manager
func (i *ExtImageCopyCaptureManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtImageCopyCaptureSessionV1: image copy capture session
type ExtImageCopyCaptureSessionV1 struct {
	client.BaseProxy
	bufferSizeHandler   ExtImageCopyCaptureSessionV1BufferSizeHandler
	shmFormatHandler    ExtImageCopyCaptureSessionV1ShmFormatHandler
	dmabufDeviceHandler ExtImageCopyCaptureSessionV1DmabufDeviceHandler
	dmabufFormatHandler ExtImageCopyCaptureSessionV1DmabufFormatHandler
	doneHandler         ExtImageCopyCaptureSessionV1DoneHandler
	stoppedHandler      ExtImageCopyCaptureSessionV1StoppedHandler
}

// NewExtImageCopyCaptureSessionV1 creates a new ExtImageCopyCaptureSessionV1
func NewExtImageCopyCaptureSessionV1(ctx *client.Context) *ExtImageCopyCaptureSessionV1 {
	o := &ExtImageCopyCaptureSessionV1{}
	ctx.Register(o)
	return o
}

type ExtImageCopyCaptureSessionV1Error uint32

const (
	ExtImageCopyCaptureSessionV1ErrorDuplicateFrame ExtImageCopyCaptureSessionV1Error = 1
)

// CreateFrame: create a frame
func (i *ExtImageCopyCaptureSessionV1) CreateFrame() (*ExtImageCopyCaptureFrameV1, error) {
	frame := NewExtImageCopyCaptureFrameV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], frame.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return frame, err
}

// Destroy: delete this object
func (i *ExtImageCopyCaptureSessionV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtImageCopyCaptureSessionV1BufferSizeEvent: image capture source dimensions
type ExtImageCopyCaptureSessionV1BufferSizeEvent struct {
	Width  uint32
	Height uint32
}

type ExtImageCopyCaptureSessionV1BufferSizeHandler func(ExtImageCopyCaptureSessionV1BufferSizeEvent)

// ExtImageCopyCaptureSessionV1ShmFormatEvent: shm buffer format
type ExtImageCopyCaptureSessionV1ShmFormatEvent struct {
	Format WlShmFormat
}

type ExtImageCopyCaptureSessionV1ShmFormatHandler func(ExtImageCopyCaptureSessionV1ShmFormatEvent)

// ExtImageCopyCaptureSessionV1DmabufDeviceEvent: dma-buf device
type ExtImageCopyCaptureSessionV1DmabufDeviceEvent struct {
	Device []byte
}

type ExtImageCopyCaptureSessionV1DmabufDeviceHandler func(ExtImageCopyCaptureSessionV1DmabufDeviceEvent)

// ExtImageCopyCaptureSessionV1DmabufFormatEvent: dma-buf format
type ExtImageCopyCaptureSessionV1DmabufFormatEvent struct {
	Format    uint32
	Modifiers []byte
}

type ExtImageCopyCaptureSessionV1DmabufFormatHandler func(ExtImageCopyCaptureSessionV1DmabufFormatEvent)

// ExtImageCopyCaptureSessionV1DoneEvent: all constraints have been sent
type ExtImageCopyCaptureSessionV1DoneEvent struct {
}

type ExtImageCopyCaptureSessionV1DoneHandler func(ExtImageCopyCaptureSessionV1DoneEvent)

// ExtImageCopyCaptureSessionV1StoppedEvent: session is no longer available
type ExtImageCopyCaptureSessionV1StoppedEvent struct {
}

type ExtImageCopyCaptureSessionV1StoppedHandler func(ExtImageCopyCaptureSessionV1StoppedEvent)

// SetBufferSizeHandler sets the handler for the buffer_size event
func (i *ExtImageCopyCaptureSessionV1) SetBufferSizeHandler(f ExtImageCopyCaptureSessionV1BufferSizeHandler) {
	i.bufferSizeHandler = f
}

// SetShmFormatHandler sets the handler for the shm_format event
func (i *ExtImageCopyCaptureSessionV1) SetShmFormatHandler(f ExtImageCopyCaptureSessionV1ShmFormatHandler) {
	i.shmFormatHandler = f
}

// SetDmabufDeviceHandler sets the handler for the dmabuf_device event
func (i *ExtImageCopyCaptureSessionV1) SetDmabufDeviceHandler(f ExtImageCopyCaptureSessionV1DmabufDeviceHandler) {
	i.dmabufDeviceHandler = f
}

// SetDmabufFormatHandler sets the handler for the dmabuf_format event
func (i *ExtImageCopyCaptureSessionV1) SetDmabufFormatHandler(f ExtImageCopyCaptureSessionV1DmabufFormatHandler) {
	i.dmabufFormatHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ExtImageCopyCaptureSessionV1) SetDoneHandler(f ExtImageCopyCaptureSessionV1DoneHandler) {
	i.doneHandler = f
}

// SetStoppedHandler sets the handler for the stopped event
func (i *ExtImageCopyCaptureSessionV1) SetStoppedHandler(f ExtImageCopyCaptureSessionV1StoppedHandler) {
	i.stoppedHandler = f
}

// Dispatch handles incoming events
func (i *ExtImageCopyCaptureSessionV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // buffer_size
		if i.bufferSizeHandler != nil {
			ev := ExtImageCopyCaptureSessionV1BufferSizeEvent{}
			l := 0
			_ = fd
			ev.Width = client.Uint32(data[l : l+4])
			l += 4
			ev.Height = client.Uint32(data[l : l+4])
			l += 4
			i.bufferSizeHandler(ev)
		}
	case 1: // shm_format
		if i.shmFormatHandler != nil {
			ev := ExtImageCopyCaptureSessionV1ShmFormatEvent{}
			l := 0
			_ = fd
			ev.Format = WlShmFormat(client.Uint32(data[l : l+4]))
			l += 4
			i.shmFormatHandler(ev)
		}
	case 2: // dmabuf_device
		if i.dmabufDeviceHandler != nil {
			ev := ExtImageCopyCaptureSessionV1DmabufDeviceEvent{}
			l := 0
			_ = fd
			deviceLen := int(client.Uint32(data[l : l+4]))
			l += 4
			ev.Device = data[l : l+deviceLen]
			l += client.PaddedLen(deviceLen)
			i.dmabufDeviceHandler(ev)
		}
	case 3: // dmabuf_format
		if i.dmabufFormatHandler != nil {
			ev := ExtImageCopyCaptureSessionV1DmabufFormatEvent{}
			l := 0
			_ = fd
			ev.Format = client.Uint32(data[l : l+4])
			l += 4
			modifiersLen := int(client.Uint32(data[l : l+4]))
			l += 4
			ev.Modifiers = data[l : l+modifiersLen]
			l += client.PaddedLen(modifiersLen)
			i.dmabufFormatHandler(ev)
		}
	case 4: // done
		if i.doneHandler != nil {
			ev := ExtImageCopyCaptureSessionV1DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 5: // stopped
		if i.stoppedHandler != nil {
			ev := ExtImageCopyCaptureSessionV1StoppedEvent{}
			_ = fd
			_ = data
			i.stoppedHandler(ev)
		}
	}
}

// ExtImageCopyCaptureFrameV1: image capture frame
type ExtImageCopyCaptureFrameV1 struct {
	client.BaseProxy
	transformHandler        ExtImageCopyCaptureFrameV1TransformHandler
	damageHandler           ExtImageCopyCaptureFrameV1DamageHandler
	presentationTimeHandler ExtImageCopyCaptureFrameV1PresentationTimeHandler
	readyHandler            ExtImageCopyCaptureFrameV1ReadyHandler
	failedHandler           ExtImageCopyCaptureFrameV1FailedHandler
}

// NewExtImageCopyCaptureFrameV1 creates a new ExtImageCopyCaptureFrameV1
func NewExtImageCopyCaptureFrameV1(ctx *client.Context) *ExtImageCopyCaptureFrameV1 {
	o := &ExtImageCopyCaptureFrameV1{}
	ctx.Register(o)
	return o
}

type ExtImageCopyCaptureFrameV1Error uint32

const (
	ExtImageCopyCaptureFrameV1ErrorNoBuffer            ExtImageCopyCaptureFrameV1Error = 1
	ExtImageCopyCaptureFrameV1ErrorInvalidBufferDamage ExtImageCopyCaptureFrameV1Error = 2
	ExtImageCopyCaptureFrameV1ErrorAlreadyCaptured     ExtImageCopyCaptureFrameV1Error = 3
)

type ExtImageCopyCaptureFrameV1FailureReason uint32

const (
	ExtImageCopyCaptureFrameV1FailureReasonUnknown           ExtImageCopyCaptureFrameV1FailureReason = 0
	ExtImageCopyCaptureFrameV1FailureReasonBufferConstraints ExtImageCopyCaptureFrameV1FailureReason = 1
	ExtImageCopyCaptureFrameV1FailureReasonStopped           ExtImageCopyCaptureFrameV1FailureReason = 2
)

// Destroy: destroy this object
func (i *ExtImageCopyCaptureFrameV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AttachBuffer: attach buffer to session
func (i *ExtImageCopyCaptureFrameV1) AttachBuffer(buffer *client.WlBuffer) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DamageBuffer: damage buffer
func (i *ExtImageCopyCaptureFrameV1) DamageBuffer(x int32, y int32, width int32, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Capture: capture a frame
func (i *ExtImageCopyCaptureFrameV1) Capture() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtImageCopyCaptureFrameV1TransformEvent: buffer transform
type ExtImageCopyCaptureFrameV1TransformEvent struct {
	Transform WlOutputTransform
}

type ExtImageCopyCaptureFrameV1TransformHandler func(ExtImageCopyCaptureFrameV1TransformEvent)

// ExtImageCopyCaptureFrameV1DamageEvent: buffer damaged region
type ExtImageCopyCaptureFrameV1DamageEvent struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}

type ExtImageCopyCaptureFrameV1DamageHandler func(ExtImageCopyCaptureFrameV1DamageEvent)

// ExtImageCopyCaptureFrameV1PresentationTimeEvent: presentation time of the frame
type ExtImageCopyCaptureFrameV1PresentationTimeEvent struct {
	TvSecHi uint32
	TvSecLo uint32
	TvNsec  uint32
}

type ExtImageCopyCaptureFrameV1PresentationTimeHandler func(ExtImageCopyCaptureFrameV1PresentationTimeEvent)

// ExtImageCopyCaptureFrameV1ReadyEvent: frame is available for reading
type ExtImageCopyCaptureFrameV1ReadyEvent struct {
}

type ExtImageCopyCaptureFrameV1ReadyHandler func(ExtImageCopyCaptureFrameV1ReadyEvent)

// ExtImageCopyCaptureFrameV1FailedEvent: capture failed
type ExtImageCopyCaptureFrameV1FailedEvent struct {
	Reason ExtImageCopyCaptureFrameV1FailureReason
}

type ExtImageCopyCaptureFrameV1FailedHandler func(ExtImageCopyCaptureFrameV1FailedEvent)

// SetTransformHandler sets the handler for the transform event
func (i *ExtImageCopyCaptureFrameV1) SetTransformHandler(f ExtImageCopyCaptureFrameV1TransformHandler) {
	i.transformHandler = f
}

// SetDamageHandler sets the handler for the damage event
func (i *ExtImageCopyCaptureFrameV1) SetDamageHandler(f ExtImageCopyCaptureFrameV1DamageHandler) {
	i.damageHandler = f
}

// SetPresentationTimeHandler sets the handler for the presentation_time event
func (i *ExtImageCopyCaptureFrameV1) SetPresentationTimeHandler(f ExtImageCopyCaptureFrameV1PresentationTimeHandler) {
	i.presentationTimeHandler = f
}

// SetReadyHandler sets the handler for the ready event
func (i *ExtImageCopyCaptureFrameV1) SetReadyHandler(f ExtImageCopyCaptureFrameV1ReadyHandler) {
	i.readyHandler = f
}

// SetFailedHandler sets the handler for the failed event
func (i *ExtImageCopyCaptureFrameV1) SetFailedHandler(f ExtImageCopyCaptureFrameV1FailedHandler) {
	i.failedHandler = f
}

// Dispatch handles incoming events
func (i *ExtImageCopyCaptureFrameV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // transform
		if i.transformHandler != nil {
			ev := ExtImageCopyCaptureFrameV1TransformEvent{}
			l := 0
			_ = fd
			ev.Transform = WlOutputTransform(client.Uint32(data[l : l+4]))
			l += 4
			i.transformHandler(ev)
		}
	case 1: // damage
		if i.damageHandler != nil {
			ev := ExtImageCopyCaptureFrameV1DamageEvent{}
			l := 0
			_ = fd
			ev.X = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Y = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Width = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Height = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.damageHandler(ev)
		}
	case 2: // presentation_time
		if i.presentationTimeHandler != nil {
			ev := ExtImageCopyCaptureFrameV1PresentationTimeEvent{}
			l := 0
			_ = fd
			ev.TvSecHi = client.Uint32(data[l : l+4])
			l += 4
			ev.TvSecLo = client.Uint32(data[l : l+4])
			l += 4
			ev.TvNsec = client.Uint32(data[l : l+4])
			l += 4
			i.presentationTimeHandler(ev)
		}
	case 3: // ready
		if i.readyHandler != nil {
			ev := ExtImageCopyCaptureFrameV1ReadyEvent{}
			_ = fd
			_ = data
			i.readyHandler(ev)
		}
	case 4: // failed
		if i.failedHandler != nil {
			ev := ExtImageCopyCaptureFrameV1FailedEvent{}
			l := 0
			_ = fd
			ev.Reason = ExtImageCopyCaptureFrameV1FailureReason(client.Uint32(data[l : l+4]))
			l += 4
			i.failedHandler(ev)
		}
	}
}

// ExtImageCopyCaptureCursorSessionV1: cursor capture session
type ExtImageCopyCaptureCursorSessionV1 struct {
	client.BaseProxy
	enterHandler    ExtImageCopyCaptureCursorSessionV1EnterHandler
	leaveHandler    ExtImageCopyCaptureCursorSessionV1LeaveHandler
	positionHandler ExtImageCopyCaptureCursorSessionV1PositionHandler
	hotspotHandler  ExtImageCopyCaptureCursorSessionV1HotspotHandler
}

// NewExtImageCopyCaptureCursorSessionV1 creates a new ExtImageCopyCaptureCursorSessionV1
func NewExtImageCopyCaptureCursorSessionV1(ctx *client.Context) *ExtImageCopyCaptureCursorSessionV1 {
	o := &ExtImageCopyCaptureCursorSessionV1{}
	ctx.Register(o)
	return o
}

type ExtImageCopyCaptureCursorSessionV1Error uint32

const (
	ExtImageCopyCaptureCursorSessionV1ErrorDuplicateSession ExtImageCopyCaptureCursorSessionV1Error = 1
)

// Destroy: delete this object
func (i *ExtImageCopyCaptureCursorSessionV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetCaptureSession: get image copy capturer session
func (i *ExtImageCopyCaptureCursorSessionV1) GetCaptureSession() (*ExtImageCopyCaptureSessionV1, error) {
	session := NewExtImageCopyCaptureSessionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

// ExtImageCopyCaptureCursorSessionV1EnterEvent: cursor entered captured area
type ExtImageCopyCaptureCursorSessionV1EnterEvent struct {
}

type ExtImageCopyCaptureCursorSessionV1EnterHandler func(ExtImageCopyCaptureCursorSessionV1EnterEvent)

// ExtImageCopyCaptureCursorSessionV1LeaveEvent: cursor left captured area
type ExtImageCopyCaptureCursorSessionV1LeaveEvent struct {
}

type ExtImageCopyCaptureCursorSessionV1LeaveHandler func(ExtImageCopyCaptureCursorSessionV1LeaveEvent)

// ExtImageCopyCaptureCursorSessionV1PositionEvent: position changed
type ExtImageCopyCaptureCursorSessionV1PositionEvent struct {
	X int32
	Y int32
}

type ExtImageCopyCaptureCursorSessionV1PositionHandler func(ExtImageCopyCaptureCursorSessionV1PositionEvent)

// ExtImageCopyCaptureCursorSessionV1HotspotEvent: hotspot changed
type ExtImageCopyCaptureCursorSessionV1HotspotEvent struct {
	X int32
	Y int32
}

type ExtImageCopyCaptureCursorSessionV1HotspotHandler func(ExtImageCopyCaptureCursorSessionV1HotspotEvent)

// SetEnterHandler sets the handler for the enter event
func (i *ExtImageCopyCaptureCursorSessionV1) SetEnterHandler(f ExtImageCopyCaptureCursorSessionV1EnterHandler) {
	i.enterHandler = f
}

// SetLeaveHandler sets the handler for the leave event
func (i *ExtImageCopyCaptureCursorSessionV1) SetLeaveHandler(f ExtImageCopyCaptureCursorSessionV1LeaveHandler) {
	i.leaveHandler = f
}

// SetPositionHandler sets the handler for the position event
func (i *ExtImageCopyCaptureCursorSessionV1) SetPositionHandler(f ExtImageCopyCaptureCursorSessionV1PositionHandler) {
	i.positionHandler = f
}

// SetHotspotHandler sets the handler for the hotspot event
func (i *ExtImageCopyCaptureCursorSessionV1) SetHotspotHandler(f ExtImageCopyCaptureCursorSessionV1HotspotHandler) {
	i.hotspotHandler = f
}

// Dispatch handles incoming events
func (i *ExtImageCopyCaptureCursorSessionV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // enter
		if i.enterHandler != nil {
			ev := ExtImageCopyCaptureCursorSessionV1EnterEvent{}
			_ = fd
			_ = data
			i.enterHandler(ev)
		}
	case 1: // leave
		if i.leaveHandler != nil {
			ev := ExtImageCopyCaptureCursorSessionV1LeaveEvent{}
			_ = fd
			_ = data
			i.leaveHandler(ev)
		}
	case 2: // position
		if i.positionHandler != nil {
			ev := ExtImageCopyCaptureCursorSessionV1PositionEvent{}
			l := 0
			_ = fd
			ev.X = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Y = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.positionHandler(ev)
		}
	case 3: // hotspot
		if i.hotspotHandler != nil {
			ev := ExtImageCopyCaptureCursorSessionV1HotspotEvent{}
			l := 0
			_ = fd
			ev.X = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Y = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.hotspotHandler(ev)
		}
	}
}
