// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/ext-transient-seat/ext-transient-seat-v1.xml
//
// ext_transient_seat_v1 Protocol Copyright:
// Copyright © 2020 - 2023 Andri Yngvason
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package ext_transient_seat_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ExtTransientSeatManagerV1: transient seat manager
type ExtTransientSeatManagerV1 struct {
	client.BaseProxy
}

// NewExtTransientSeatManagerV1 creates a new ExtTransientSeatManagerV1
func NewExtTransientSeatManagerV1(ctx *client.Context) *ExtTransientSeatManagerV1 {
	o := &ExtTransientSeatManagerV1{}
	ctx.Register(o)
	return o
}

// Create: create a transient seat
func (i *ExtTransientSeatManagerV1) Create() (*ExtTransientSeatV1, error) {
	seat := NewExtTransientSeatV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return seat, err
}

// Destroy: destroy the manager
func (i *ExtTransientSeatManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtTransientSeatV1: transient seat handle
type ExtTransientSeatV1 struct {
	client.BaseProxy
	readyHandler  ExtTransientSeatV1ReadyHandler
	deniedHandler ExtTransientSeatV1DeniedHandler
}

// NewExtTransientSeatV1 creates a new ExtTransientSeatV1
func NewExtTransientSeatV1(ctx *client.Context) *ExtTransientSeatV1 {
	o := &ExtTransientSeatV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy transient seat
func (i *ExtTransientSeatV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtTransientSeatV1ReadyEvent: transient seat is ready
type ExtTransientSeatV1ReadyEvent struct {
	GlobalName uint32
}

type ExtTransientSeatV1ReadyHandler func(ExtTransientSeatV1ReadyEvent)

// ExtTransientSeatV1DeniedEvent: transient seat creation denied
type ExtTransientSeatV1DeniedEvent struct {
}

type ExtTransientSeatV1DeniedHandler func(ExtTransientSeatV1DeniedEvent)

// SetReadyHandler sets the handler for the ready event
func (i *ExtTransientSeatV1) SetReadyHandler(f ExtTransientSeatV1ReadyHandler) {
	i.readyHandler = f
}

// SetDeniedHandler sets the handler for the denied event
func (i *ExtTransientSeatV1) SetDeniedHandler(f ExtTransientSeatV1DeniedHandler) {
	i.deniedHandler = f
}

// Dispatch handles incoming events
func (i *ExtTransientSeatV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // ready
		if i.readyHandler != nil {
			ev := ExtTransientSeatV1ReadyEvent{}
			l := 0
			_ = fd
			ev.GlobalName = client.Uint32(data[l : l+4])
			l += 4
			i.readyHandler(ev)
		}
	case 1: // denied
		if i.deniedHandler != nil {
			ev := ExtTransientSeatV1DeniedEvent{}
			_ = fd
			_ = data
			i.deniedHandler(ev)
		}
	}
}
