// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/fifo/fifo-v1.xml
//
// fifo_v1 Protocol Copyright:
// Copyright © 2023 Valve Corporation
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package fifo_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// WpFifoManagerV1: protocol for fifo constraints
type WpFifoManagerV1 struct {
	client.BaseProxy
}

// NewWpFifoManagerV1 creates a new WpFifoManagerV1
func NewWpFifoManagerV1(ctx *client.Context) *WpFifoManagerV1 {
	o := &WpFifoManagerV1{}
	ctx.Register(o)
	return o
}

// WpFifoManagerV1Error: fatal presentation error
type WpFifoManagerV1Error uint32

const (
	WpFifoManagerV1ErrorAlreadyExists WpFifoManagerV1Error = 0
)

// Destroy: unbind from the manager interface
func (i *WpFifoManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetFifo: request fifo interface for surface
func (i *WpFifoManagerV1) GetFifo(surface *client.WlSurface) (*WpFifoV1, error) {
	id := NewWpFifoV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WpFifoV1: fifo interface
type WpFifoV1 struct {
	client.BaseProxy
}

// NewWpFifoV1 creates a new WpFifoV1
func NewWpFifoV1(ctx *client.Context) *WpFifoV1 {
	o := &WpFifoV1{}
	ctx.Register(o)
	return o
}

// WpFifoV1Error: fatal error
type WpFifoV1Error uint32

const (
	WpFifoV1ErrorSurfaceDestroyed WpFifoV1Error = 0
)

// SetBarrier: sets the start point for a fifo constraint
func (i *WpFifoV1) SetBarrier() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WaitBarrier: adds a fifo constraint to a content update
func (i *WpFifoV1) WaitBarrier() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy: destroy the fifo interface
func (i *WpFifoV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
