// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/xdg-shell/xdg-shell-unstable-v6.xml
//
// xdg_shell_unstable_v6 Protocol Copyright:
// Copyright © 2008-2013 Kristian Høgsberg
// Copyright © 2013      Rafael Antognolli
// Copyright © 2013      Jasper St. Pierre
// Copyright © 2010-2013 Intel Corporation
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdg_shell_unstable_v6

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZxdgShellV6: create desktop-style surfaces
type ZxdgShellV6 struct {
	client.BaseProxy
	pingHandler ZxdgShellV6PingHandler
}

// NewZxdgShellV6 creates a new ZxdgShellV6
func NewZxdgShellV6(ctx *client.Context) *ZxdgShellV6 {
	o := &ZxdgShellV6{}
	ctx.Register(o)
	return o
}

type ZxdgShellV6Error uint32

const (
	ZxdgShellV6ErrorRole                ZxdgShellV6Error = 0
	ZxdgShellV6ErrorDefunctSurfaces     ZxdgShellV6Error = 1
	ZxdgShellV6ErrorNotTheTopmostPopup  ZxdgShellV6Error = 2
	ZxdgShellV6ErrorInvalidPopupParent  ZxdgShellV6Error = 3
	ZxdgShellV6ErrorInvalidSurfaceState ZxdgShellV6Error = 4
	ZxdgShellV6ErrorInvalidPositioner   ZxdgShellV6Error = 5
)

// Destroy: destroy xdg_shell
func (i *ZxdgShellV6) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreatePositioner: create a positioner object
func (i *ZxdgShellV6) CreatePositioner() (*ZxdgPositionerV6, error) {
	id := NewZxdgPositionerV6(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetXdgSurface: create a shell surface from a surface
func (i *ZxdgShellV6) GetXdgSurface(surface *client.WlSurface) (*ZxdgSurfaceV6, error) {
	id := NewZxdgSurfaceV6(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Pong: respond to a ping event
func (i *ZxdgShellV6) Pong(serial uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgShellV6PingEvent: check if the client is alive
type ZxdgShellV6PingEvent struct {
	Serial uint32
}

type ZxdgShellV6PingHandler func(ZxdgShellV6PingEvent)

// SetPingHandler sets the handler for the ping event
func (i *ZxdgShellV6) SetPingHandler(f ZxdgShellV6PingHandler) {
	i.pingHandler = f
}

// Dispatch handles incoming events
func (i *ZxdgShellV6) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // ping
		if i.pingHandler != nil {
			ev := ZxdgShellV6PingEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			i.pingHandler(ev)
		}
	}
}

// ZxdgPositionerV6: child surface positioner
type ZxdgPositionerV6 struct {
	client.BaseProxy
}

// NewZxdgPositionerV6 creates a new ZxdgPositionerV6
func NewZxdgPositionerV6(ctx *client.Context) *ZxdgPositionerV6 {
	o := &ZxdgPositionerV6{}
	ctx.Register(o)
	return o
}

type ZxdgPositionerV6Error uint32

const (
	ZxdgPositionerV6ErrorInvalidInput ZxdgPositionerV6Error = 0
)

type ZxdgPositionerV6Anchor uint32

const (
	ZxdgPositionerV6AnchorNone   ZxdgPositionerV6Anchor = 0
	ZxdgPositionerV6AnchorTop    ZxdgPositionerV6Anchor = 1
	ZxdgPositionerV6AnchorBottom ZxdgPositionerV6Anchor = 2
	ZxdgPositionerV6AnchorLeft   ZxdgPositionerV6Anchor = 4
	ZxdgPositionerV6AnchorRight  ZxdgPositionerV6Anchor = 8
)

type ZxdgPositionerV6Gravity uint32

const (
	ZxdgPositionerV6GravityNone   ZxdgPositionerV6Gravity = 0
	ZxdgPositionerV6GravityTop    ZxdgPositionerV6Gravity = 1
	ZxdgPositionerV6GravityBottom ZxdgPositionerV6Gravity = 2
	ZxdgPositionerV6GravityLeft   ZxdgPositionerV6Gravity = 4
	ZxdgPositionerV6GravityRight  ZxdgPositionerV6Gravity = 8
)

// ZxdgPositionerV6ConstraintAdjustment: constraint adjustments
type ZxdgPositionerV6ConstraintAdjustment uint32

const (
	ZxdgPositionerV6ConstraintAdjustmentNone    ZxdgPositionerV6ConstraintAdjustment = 0
	ZxdgPositionerV6ConstraintAdjustmentSlideX  ZxdgPositionerV6ConstraintAdjustment = 1
	ZxdgPositionerV6ConstraintAdjustmentSlideY  ZxdgPositionerV6ConstraintAdjustment = 2
	ZxdgPositionerV6ConstraintAdjustmentFlipX   ZxdgPositionerV6ConstraintAdjustment = 4
	ZxdgPositionerV6ConstraintAdjustmentFlipY   ZxdgPositionerV6ConstraintAdjustment = 8
	ZxdgPositionerV6ConstraintAdjustmentResizeX ZxdgPositionerV6ConstraintAdjustment = 16
	ZxdgPositionerV6ConstraintAdjustmentResizeY ZxdgPositionerV6ConstraintAdjustment = 32
)

// Destroy: destroy the xdg_positioner object
func (i *ZxdgPositionerV6) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSize: set the size of the to-be positioned rectangle
func (i *ZxdgPositionerV6) SetSize(width int32, height int32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetAnchorRect: set the anchor rectangle within the parent surface
func (i *ZxdgPositionerV6) SetAnchorRect(x int32, y int32, width int32, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetAnchor: set anchor rectangle anchor edges
func (i *ZxdgPositionerV6) SetAnchor(anchor ZxdgPositionerV6Anchor) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(anchor))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetGravity: set child surface gravity
func (i *ZxdgPositionerV6) SetGravity(gravity ZxdgPositionerV6Gravity) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(gravity))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetConstraintAdjustment: set the adjustment to be done when constrained
func (i *ZxdgPositionerV6) SetConstraintAdjustment(constraint_adjustment uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(constraint_adjustment))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetOffset: set surface position offset
func (i *ZxdgPositionerV6) SetOffset(x int32, y int32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgSurfaceV6: desktop user interface surface base interface
type ZxdgSurfaceV6 struct {
	client.BaseProxy
	configureHandler ZxdgSurfaceV6ConfigureHandler
}

// NewZxdgSurfaceV6 creates a new ZxdgSurfaceV6
func NewZxdgSurfaceV6(ctx *client.Context) *ZxdgSurfaceV6 {
	o := &ZxdgSurfaceV6{}
	ctx.Register(o)
	return o
}

type ZxdgSurfaceV6Error uint32

const (
	ZxdgSurfaceV6ErrorNotConstructed     ZxdgSurfaceV6Error = 1
	ZxdgSurfaceV6ErrorAlreadyConstructed ZxdgSurfaceV6Error = 2
	ZxdgSurfaceV6ErrorUnconfiguredBuffer ZxdgSurfaceV6Error = 3
)

// Destroy: destroy the xdg_surface
func (i *ZxdgSurfaceV6) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetToplevel: assign the xdg_toplevel surface role
func (i *ZxdgSurfaceV6) GetToplevel() (*ZxdgToplevelV6, error) {
	id := NewZxdgToplevelV6(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetPopup: assign the xdg_popup surface role
func (i *ZxdgSurfaceV6) GetPopup(parent *ZxdgSurfaceV6, positioner *ZxdgPositionerV6) (*ZxdgPopupV6, error) {
	id := NewZxdgPopupV6(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], parent.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], positioner.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// SetWindowGeometry: set the new window geometry
func (i *ZxdgSurfaceV6) SetWindowGeometry(x int32, y int32, width int32, height int32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AckConfigure: ack a configure event
func (i *ZxdgSurfaceV6) AckConfigure(serial uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgSurfaceV6ConfigureEvent: suggest a surface change
type ZxdgSurfaceV6ConfigureEvent struct {
	Serial uint32
}

type ZxdgSurfaceV6ConfigureHandler func(ZxdgSurfaceV6ConfigureEvent)

// SetConfigureHandler sets the handler for the configure event
func (i *ZxdgSurfaceV6) SetConfigureHandler(f ZxdgSurfaceV6ConfigureHandler) {
	i.configureHandler = f
}

// Dispatch handles incoming events
func (i *ZxdgSurfaceV6) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // configure
		if i.configureHandler != nil {
			ev := ZxdgSurfaceV6ConfigureEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			i.configureHandler(ev)
		}
	}
}

// ZxdgToplevelV6: toplevel surface
type ZxdgToplevelV6 struct {
	client.BaseProxy
	configureHandler ZxdgToplevelV6ConfigureHandler
	closeHandler     ZxdgToplevelV6CloseHandler
}

// NewZxdgToplevelV6 creates a new ZxdgToplevelV6
func NewZxdgToplevelV6(ctx *client.Context) *ZxdgToplevelV6 {
	o := &ZxdgToplevelV6{}
	ctx.Register(o)
	return o
}

// ZxdgToplevelV6ResizeEdge: edge values for resizing
type ZxdgToplevelV6ResizeEdge uint32

const (
	ZxdgToplevelV6ResizeEdgeNone        ZxdgToplevelV6ResizeEdge = 0
	ZxdgToplevelV6ResizeEdgeTop         ZxdgToplevelV6ResizeEdge = 1
	ZxdgToplevelV6ResizeEdgeBottom      ZxdgToplevelV6ResizeEdge = 2
	ZxdgToplevelV6ResizeEdgeLeft        ZxdgToplevelV6ResizeEdge = 4
	ZxdgToplevelV6ResizeEdgeTopLeft     ZxdgToplevelV6ResizeEdge = 5
	ZxdgToplevelV6ResizeEdgeBottomLeft  ZxdgToplevelV6ResizeEdge = 6
	ZxdgToplevelV6ResizeEdgeRight       ZxdgToplevelV6ResizeEdge = 8
	ZxdgToplevelV6ResizeEdgeTopRight    ZxdgToplevelV6ResizeEdge = 9
	ZxdgToplevelV6ResizeEdgeBottomRight ZxdgToplevelV6ResizeEdge = 10
)

// ZxdgToplevelV6State: types of state on the surface
type ZxdgToplevelV6State uint32

const (
	ZxdgToplevelV6StateMaximized  ZxdgToplevelV6State = 1
	ZxdgToplevelV6StateFullscreen ZxdgToplevelV6State = 2
	ZxdgToplevelV6StateResizing   ZxdgToplevelV6State = 3
	ZxdgToplevelV6StateActivated  ZxdgToplevelV6State = 4
)

// Destroy: destroy the xdg_toplevel
func (i *ZxdgToplevelV6) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetParent: set the parent of this surface
func (i *ZxdgToplevelV6) SetParent(parent *ZxdgToplevelV6) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if parent == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], parent.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTitle: set surface title
func (i *ZxdgToplevelV6) SetTitle(title string) error {
	const opcode = 2
	titleLen := client.PaddedLen(len(title) + 1)
	_reqBufLen := 8 + (4 + titleLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+titleLen)], title, titleLen)
	l += (4 + titleLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetAppId: set application ID
func (i *ZxdgToplevelV6) SetAppId(app_id string) error {
	const opcode = 3
	app_idLen := client.PaddedLen(len(app_id) + 1)
	_reqBufLen := 8 + (4 + app_idLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+app_idLen)], app_id, app_idLen)
	l += (4 + app_idLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// ShowWindowMenu: show the window menu
func (i *ZxdgToplevelV6) ShowWindowMenu(seat *client.WlSeat, serial uint32, x int32, y int32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Move: start an interactive move
func (i *ZxdgToplevelV6) Move(seat *client.WlSeat, serial uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Resize: start an interactive resize
func (i *ZxdgToplevelV6) Resize(seat *client.WlSeat, serial uint32, edges uint32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(edges))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaxSize: set the maximum size
func (i *ZxdgToplevelV6) SetMaxSize(width int32, height int32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMinSize: set the minimum size
func (i *ZxdgToplevelV6) SetMinSize(width int32, height int32) error {
	const opcode = 8
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaximized: maximize the window
func (i *ZxdgToplevelV6) SetMaximized() error {
	const opcode = 9
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UnsetMaximized: unmaximize the window
func (i *ZxdgToplevelV6) UnsetMaximized() error {
	const opcode = 10
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetFullscreen: set the window as fullscreen on a monitor
func (i *ZxdgToplevelV6) SetFullscreen(output *client.WlOutput) error {
	const opcode = 11
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if output == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], output.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

func (i *ZxdgToplevelV6) UnsetFullscreen() error {
	const opcode = 12
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMinimized: set the window as minimized
func (i *ZxdgToplevelV6) SetMinimized() error {
	const opcode = 13
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgToplevelV6ConfigureEvent: suggest a surface change
type ZxdgToplevelV6ConfigureEvent struct {
	Width  int32
	Height int32
	States []byte
}

type ZxdgToplevelV6ConfigureHandler func(ZxdgToplevelV6ConfigureEvent)

// ZxdgToplevelV6CloseEvent: surface wants to be closed
type ZxdgToplevelV6CloseEvent struct {
}

type ZxdgToplevelV6CloseHandler func(ZxdgToplevelV6CloseEvent)

// SetConfigureHandler sets the handler for the configure event
func (i *ZxdgToplevelV6) SetConfigureHandler(f ZxdgToplevelV6ConfigureHandler) {
	i.configureHandler = f
}

// SetCloseHandler sets the handler for the close event
func (i *ZxdgToplevelV6) SetCloseHandler(f ZxdgToplevelV6CloseHandler) {
	i.closeHandler = f
}

// Dispatch handles incoming events
func (i *ZxdgToplevelV6) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // configure
		if i.configureHandler != nil {
			ev := ZxdgToplevelV6ConfigureEvent{}
			l := 0
			_ = fd
			ev.Width = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Height = int32(client.Uint32(data[l : l+4]))
			l += 4
			statesLen := int(client.Uint32(data[l : l+4]))
			l += 4
			ev.States = data[l : l+statesLen]
			l += client.PaddedLen(statesLen)
			i.configureHandler(ev)
		}
	case 1: // close
		if i.closeHandler != nil {
			ev := ZxdgToplevelV6CloseEvent{}
			_ = fd
			_ = data
			i.closeHandler(ev)
		}
	}
}

// ZxdgPopupV6: short-lived, popup surfaces for menus
type ZxdgPopupV6 struct {
	client.BaseProxy
	configureHandler ZxdgPopupV6ConfigureHandler
	popupDoneHandler ZxdgPopupV6PopupDoneHandler
}

// NewZxdgPopupV6 creates a new ZxdgPopupV6
func NewZxdgPopupV6(ctx *client.Context) *ZxdgPopupV6 {
	o := &ZxdgPopupV6{}
	ctx.Register(o)
	return o
}

type ZxdgPopupV6Error uint32

const (
	ZxdgPopupV6ErrorInvalidGrab ZxdgPopupV6Error = 0
)

// Destroy: remove xdg_popup interface
func (i *ZxdgPopupV6) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Grab: make the popup take an explicit grab
func (i *ZxdgPopupV6) Grab(seat *client.WlSeat, serial uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZxdgPopupV6ConfigureEvent: configure the popup surface
type ZxdgPopupV6ConfigureEvent struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}

type ZxdgPopupV6ConfigureHandler func(ZxdgPopupV6ConfigureEvent)

// ZxdgPopupV6PopupDoneEvent: popup interaction is done
type ZxdgPopupV6PopupDoneEvent struct {
}

type ZxdgPopupV6PopupDoneHandler func(ZxdgPopupV6PopupDoneEvent)

// SetConfigureHandler sets the handler for the configure event
func (i *ZxdgPopupV6) SetConfigureHandler(f ZxdgPopupV6ConfigureHandler) {
	i.configureHandler = f
}

// SetPopupDoneHandler sets the handler for the popup_done event
func (i *ZxdgPopupV6) SetPopupDoneHandler(f ZxdgPopupV6PopupDoneHandler) {
	i.popupDoneHandler = f
}

// Dispatch handles incoming events
func (i *ZxdgPopupV6) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // configure
		if i.configureHandler != nil {
			ev := ZxdgPopupV6ConfigureEvent{}
			l := 0
			_ = fd
			ev.X = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Y = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Width = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.Height = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.configureHandler(ev)
		}
	case 1: // popup_done
		if i.popupDoneHandler != nil {
			ev := ZxdgPopupV6PopupDoneEvent{}
			_ = fd
			_ = data
			i.popupDoneHandler(ev)
		}
	}
}
