package main

import (
	"bytes"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
)

var (
	inputFile   string
	outputFile  string
	packageName string
)

func init() {
	flag.StringVar(&inputFile, "i", "", "Path to protocol XML file")
	flag.StringVar(&outputFile, "o", "", "Path to output Go file")
	flag.StringVar(&packageName, "pkg", "", "Go package name")
}

// Protocol XML structure
type Protocol struct {
	XMLName    xml.Name    `xml:"protocol"`
	Name       string      `xml:"name,attr"`
	Copyright  string      `xml:"copyright"`
	Interfaces []Interface `xml:"interface"`
}

type Interface struct {
	XMLName     xml.Name    `xml:"interface"`
	Name        string      `xml:"name,attr"`
	Version     int         `xml:"version,attr"`
	Description Description `xml:"description"`
	Requests    []Request   `xml:"request"`
	Events      []Event     `xml:"event"`
	Enums       []Enum      `xml:"enum"`
}

type Request struct {
	XMLName     xml.Name    `xml:"request"`
	Name        string      `xml:"name,attr"`
	Type        string      `xml:"type,attr"`
	Description Description `xml:"description"`
	Args        []Arg       `xml:"arg"`
}

type Event struct {
	XMLName     xml.Name    `xml:"event"`
	Name        string      `xml:"name,attr"`
	Description Description `xml:"description"`
	Args        []Arg       `xml:"arg"`
}

type Enum struct {
	XMLName     xml.Name    `xml:"enum"`
	Name        string      `xml:"name,attr"`
	Description Description `xml:"description"`
	Entries     []Entry     `xml:"entry"`
	Bitfield    bool        `xml:"bitfield,attr"`
}

type Entry struct {
	XMLName xml.Name `xml:"entry"`
	Name    string   `xml:"name,attr"`
	Value   string   `xml:"value,attr"`
	Summary string   `xml:"summary,attr"`
}

type Arg struct {
	XMLName   xml.Name `xml:"arg"`
	Name      string   `xml:"name,attr"`
	Type      string   `xml:"type,attr"`
	Summary   string   `xml:"summary,attr"`
	Interface string   `xml:"interface,attr"`
	Enum      string   `xml:"enum,attr"`
	AllowNull bool     `xml:"allow-null,attr"`
}

type Description struct {
	XMLName xml.Name `xml:"description"`
	Summary string   `xml:"summary,attr"`
	Text    string   `xml:",chardata"`
}

func main() {
	flag.Parse()

	if inputFile == "" || outputFile == "" || packageName == "" {
		flag.Usage()
		log.Fatal("Missing required flags")
	}

	// Read XML
	xmlFile, err := os.Open(inputFile)
	if err != nil {
		log.Fatalf("Failed to open input file: %v", err)
	}
	defer xmlFile.Close()

	var protocol Protocol
	if err := xml.NewDecoder(xmlFile).Decode(&protocol); err != nil {
		log.Fatalf("Failed to decode XML: %v", err)
	}

	// Generate Go code
	buf := &bytes.Buffer{}
	generateCode(buf, protocol)

	// Format the output
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("Failed to format code: %v\n%s", err, buf.String())
	}

	// Write output
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		log.Fatalf("Failed to write output: %v", err)
	}

	fmt.Printf("Generated %s from %s\n", outputFile, inputFile)
}

func generateCode(w io.Writer, p Protocol) {
	// Header
	fmt.Fprintf(w, "// Generated by cheese wayland-scanner\n")
	fmt.Fprintf(w, "// Source: %s\n", inputFile)
	fmt.Fprintf(w, "//\n")
	if p.Copyright != "" {
		fmt.Fprintf(w, "// %s Protocol Copyright:\n", p.Name)
		writeCopyright(w, p.Copyright)
	}
	fmt.Fprintf(w, "\npackage %s\n\n", packageName)

	// Generate imports
	imports := []string{}
	// All protocols except client need client package
	if packageName != "client" {
		imports = append(imports, `"github.com/tri2820/cheese/protocols/client"`)
	}
	if hasFileDescriptors(p) {
		imports = append(imports, `"golang.org/x/sys/unix"`)
	}

	if len(imports) > 0 {
		sort.Strings(imports)
		fmt.Fprintf(w, "import (\n")
		for _, imp := range imports {
			fmt.Fprintf(w, "\t%s\n", imp)
		}
		fmt.Fprintf(w, ")\n\n")
	}

	// Generate interfaces
	for _, iface := range p.Interfaces {
		generateInterface(w, iface, p)
	}
}

func hasFileDescriptors(p Protocol) bool {
	for _, iface := range p.Interfaces {
		for _, req := range iface.Requests {
			for _, arg := range req.Args {
				if arg.Type == "fd" {
					return true
				}
			}
		}
	}
	return false
}

func cleanSummary(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\t", " ")
	words := strings.Fields(s)
	return strings.Join(words, " ")
}

func escapeGoKeyword(name string) string {
	goKeywords := map[string]bool{
		"break": true, "case": true, "chan": true, "const": true, "continue": true,
		"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
		"func": true, "go": true, "goto": true, "if": true, "import": true,
		"interface": true, "map": true, "package": true, "range": true, "return": true,
		"select": true, "struct": true, "switch": true, "type": true, "var": true,
	}
	if goKeywords[name] {
		return name + "_"
	}
	return name
}

// getQualifiedTypeName returns the type name for an interface
// For wl_* types: returns "client.WlXxx"
// For types in current protocol: returns "Xxx"
// For other types: returns "*client.Proxy"
func getQualifiedTypeName(ifaceName string, p Protocol) string {
	typeName := strcase.ToCamel(ifaceName)

	// wl_* types come from client package
	if strings.HasPrefix(ifaceName, "wl_") {
		return "client." + typeName
	}

	// Check if type is defined in current protocol
	for _, iface := range p.Interfaces {
		if iface.Name == ifaceName {
			return typeName
		}
	}

	// External type - use client.Proxy
	return "*client.Proxy"
}

// getNewFunctionCall returns the code to create a new instance of an interface
func getNewFunctionCall(ifaceName string, varName string, p Protocol) string {
	typeName := strcase.ToCamel(ifaceName)

	// wl_* types use client package
	if strings.HasPrefix(ifaceName, "wl_") {
		return fmt.Sprintf("%s := client.New%s(i.Context())", varName, typeName)
	}

	// Check if type is defined in current protocol
	for _, iface := range p.Interfaces {
		if iface.Name == ifaceName {
			return fmt.Sprintf("%s := New%s(i.Context())", varName, typeName)
		}
	}

	// External type - create generic proxy
	return fmt.Sprintf("%s := client.NewProxy(i.Context())", varName)
}

// mapWaylandType maps Wayland types to Go types
func mapWaylandType(wlType, iface string, allowNull bool, p Protocol) string {
	// Determine prefix for client package references
	clientPrefix := "client."
	if packageName == "client" {
		clientPrefix = ""
	}

	switch wlType {
	case "int":
		return "int32"
	case "uint":
		return "uint32"
	case "fixed":
		return "float64"
	case "string":
		if allowNull {
			return "*string"
		}
		return "string"
	case "object":
		if iface != "" {
			if strings.HasPrefix(iface, "wl_") {
				return "*" + clientPrefix + strcase.ToCamel(iface)
			}
			// Check if interface is defined in current protocol
			for _, ifc := range p.Interfaces {
				if ifc.Name == iface {
					return "*" + strcase.ToCamel(iface)
				}
			}
			// External type - use Proxy (interface, no pointer)
			return clientPrefix + "Proxy"
		}
		return clientPrefix + "Proxy"
	case "new_id":
		if iface != "" {
			if strings.HasPrefix(iface, "wl_") {
				return "*" + clientPrefix + strcase.ToCamel(iface)
			}
			// Check if interface is defined in current protocol
			for _, ifc := range p.Interfaces {
				if ifc.Name == iface {
					return "*" + strcase.ToCamel(iface)
				}
			}
			// External type - use Proxy (interface, no pointer)
			return clientPrefix + "Proxy"
		}
		return clientPrefix + "Proxy"
	case "array":
		return "[]byte"
	case "fd":
		return "uintptr"
	default:
		return "interface{}"
	}
}

func generateInterface(w io.Writer, iface Interface, p Protocol) {
	typeName := strcase.ToCamel(iface.Name)

	// Determine prefix for client package references
	clientPrefix := "client."
	if packageName == "client" {
		clientPrefix = ""
	}

	// Struct definition
	if iface.Description.Summary != "" {
		fmt.Fprintf(w, "// %s: %s\n", typeName, cleanSummary(iface.Description.Summary))
	}
	fmt.Fprintf(w, "type %s struct {\n", typeName)
	fmt.Fprintf(w, "\t%sBaseProxy\n", clientPrefix)
	fmt.Fprintf(w, "}\n\n")

	// Constructor
	fmt.Fprintf(w, "// New%s creates a new %s\n", typeName, typeName)
	fmt.Fprintf(w, "func New%s(ctx *%sContext) *%s {\n", typeName, clientPrefix, typeName)
	fmt.Fprintf(w, "\to := &%s{}\n", typeName)
	fmt.Fprintf(w, "\tctx.Register(o)\n")
	fmt.Fprintf(w, "\treturn o\n")
	fmt.Fprintf(w, "}\n\n")

	// Enums
	for _, enum := range iface.Enums {
		generateEnum(w, enum, typeName)
	}

	// Requests (methods)
	for i, req := range iface.Requests {
		generateRequest(w, req, typeName, i, p)
	}

	// Events (handlers)
	for _, event := range iface.Events {
		generateEvent(w, event, typeName, p)
	}
}

func generateEnum(w io.Writer, enum Enum, ifaceName string) {
	enumName := ifaceName + strcase.ToCamel(enum.Name)

	if enum.Description.Summary != "" {
		fmt.Fprintf(w, "// %s: %s\n", enumName, cleanSummary(enum.Description.Summary))
	}
	fmt.Fprintf(w, "type %s uint32\n\n", enumName)

	fmt.Fprintf(w, "const (\n")
	for _, entry := range enum.Entries {
		entryName := enumName + strcase.ToCamel(entry.Name)
		fmt.Fprintf(w, "\t%s %s = %s\n", entryName, enumName, entry.Value)
	}
	fmt.Fprintf(w, ")\n\n")
}

func generateRequest(w io.Writer, req Request, ifaceName string, opcode int, p Protocol) {
	methodName := strcase.ToCamel(req.Name)

	// Determine prefix for client package references
	clientPrefix := "client."
	if packageName == "client" {
		clientPrefix = ""
	}

	// Method signature
	if req.Description.Summary != "" {
		fmt.Fprintf(w, "// %s: %s\n", methodName, cleanSummary(req.Description.Summary))
	}

	// Build parameter list and return types
	params := []string{}
	returnTypes := []string{}
	for _, arg := range req.Args {
		paramName := escapeGoKeyword(arg.Name)
		if arg.Type == "new_id" && arg.Interface != "" {
			// Check if this is a wl_* type (from client package)
			if strings.HasPrefix(arg.Interface, "wl_") {
				returnTypes = append(returnTypes, "*"+clientPrefix+strcase.ToCamel(arg.Interface))
			} else {
				// Check if interface is in current protocol
				isLocal := false
				for _, iface := range p.Interfaces {
					if iface.Name == arg.Interface {
						isLocal = true
						break
					}
				}
				if isLocal {
					returnTypes = append(returnTypes, "*"+strcase.ToCamel(arg.Interface))
				} else {
					// External type - return client.Proxy (no pointer, it's an interface)
					returnTypes = append(returnTypes, clientPrefix+"Proxy")
				}
			}
		} else if arg.Type == "new_id" && arg.Interface == "" {
			params = append(params, "iface string", "version uint32", fmt.Sprintf("id %sProxy", clientPrefix))
		} else {
			goType := mapWaylandType(arg.Type, arg.Interface, arg.AllowNull, p)
			params = append(params, fmt.Sprintf("%s %s", paramName, goType))
		}
	}
	returnTypes = append(returnTypes, "error")

	// Write function signature
	fmt.Fprintf(w, "func (i *%s) %s(%s) (%s) {\n", ifaceName, methodName, strings.Join(params, ", "), strings.Join(returnTypes, ", "))

	// Add defer Unregister for destructors
	if req.Type == "destructor" {
		fmt.Fprintf(w, "\tdefer i.Context().Unregister(i)\n")
	}

	// Create new objects for new_id arguments
	newObjects := []string{}
	for _, arg := range req.Args {
		if arg.Type == "new_id" && arg.Interface != "" {
			paramName := escapeGoKeyword(arg.Name)
			// wl_* types use client.NewWlXxx()
			if strings.HasPrefix(arg.Interface, "wl_") {
				typeName := strcase.ToCamel(arg.Interface)
				fmt.Fprintf(w, "\t%s := %sNew%s(i.Context())\n", paramName, clientPrefix, typeName)
			} else {
				// Check if interface is in current protocol
				isLocal := false
				for _, iface := range p.Interfaces {
					if iface.Name == arg.Interface {
						isLocal = true
						break
					}
				}
				if isLocal {
					typeName := strcase.ToCamel(arg.Interface)
					fmt.Fprintf(w, "\t%s := New%s(i.Context())\n", paramName, typeName)
				} else {
					fmt.Fprintf(w, "\t%s := %sNewProxy(i.Context())\n", paramName, clientPrefix)
				}
			}
			newObjects = append(newObjects, paramName)
		}
	}

	// Calculate message size
	fmt.Fprintf(w, "\tconst opcode = %d\n", opcode)
	sizes := []string{"8"}
	canBeConst := true
	for _, arg := range req.Args {
		paramName := escapeGoKeyword(arg.Name)
		switch arg.Type {
		case "new_id":
			if arg.Interface != "" {
				sizes = append(sizes, "4")
			} else {
				canBeConst = false
				fmt.Fprintf(w, "\tifaceLen := %sPaddedLen(len(iface)+1)\n", clientPrefix)
				sizes = append(sizes, "(4 + ifaceLen)", "4", "4")
			}
		case "object", "int", "uint", "fixed":
			sizes = append(sizes, "4")
		case "string":
			canBeConst = false
			if arg.AllowNull {
				fmt.Fprintf(w, "\tvar %sLen int\n", paramName)
				fmt.Fprintf(w, "\tif %s != nil {\n", paramName)
				fmt.Fprintf(w, "\t\t%sLen = %sPaddedLen(len(*%s)+1)\n", paramName, clientPrefix, paramName)
				fmt.Fprintf(w, "\t}\n")
			} else {
				fmt.Fprintf(w, "\t%sLen := %sPaddedLen(len(%s)+1)\n", paramName, clientPrefix, paramName)
			}
			sizes = append(sizes, fmt.Sprintf("(4 + %sLen)", paramName))
		case "array":
			canBeConst = false
			fmt.Fprintf(w, "\t%sLen := len(%s)\n", paramName, paramName)
			sizes = append(sizes, fmt.Sprintf("%sLen", paramName))
		}
	}

	// Allocate buffer
	if canBeConst {
		fmt.Fprintf(w, "\tconst _reqBufLen = %s\n", strings.Join(sizes, "+"))
		fmt.Fprintf(w, "\tvar _reqBuf [_reqBufLen]byte\n")
	} else {
		fmt.Fprintf(w, "\t_reqBufLen := %s\n", strings.Join(sizes, "+"))
		fmt.Fprintf(w, "\t_reqBuf := make([]byte, _reqBufLen)\n")
	}

	// Generate encoding code
	fmt.Fprintf(w, "\tl := 0\n")
	fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], i.ID())\n", clientPrefix)
	fmt.Fprintf(w, "\tl += 4\n")
	fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))\n", clientPrefix)
	fmt.Fprintf(w, "\tl += 4\n")

	fdIndex := -1
	for i, arg := range req.Args {
		paramName := escapeGoKeyword(arg.Name)
		switch arg.Type {
		case "object":
			if arg.AllowNull {
				fmt.Fprintf(w, "\tif %s == nil {\n", paramName)
				fmt.Fprintf(w, "\t\t%sPutUint32(_reqBuf[l:l+4], 0)\n", clientPrefix)
				fmt.Fprintf(w, "\t\tl += 4\n")
				fmt.Fprintf(w, "\t} else {\n")
				fmt.Fprintf(w, "\t\t%sPutUint32(_reqBuf[l:l+4], %s.ID())\n", clientPrefix, paramName)
				fmt.Fprintf(w, "\t\tl += 4\n")
				fmt.Fprintf(w, "\t}\n")
			} else {
				fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], %s.ID())\n", clientPrefix, paramName)
				fmt.Fprintf(w, "\tl += 4\n")
			}
		case "new_id":
			if arg.Interface != "" {
				fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], %s.ID())\n", clientPrefix, paramName)
				fmt.Fprintf(w, "\tl += 4\n")
			} else {
				fmt.Fprintf(w, "\t%sPutString(_reqBuf[l:l+(4+ifaceLen)], iface, ifaceLen)\n", clientPrefix)
				fmt.Fprintf(w, "\tl += (4 + ifaceLen)\n")
				fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], uint32(version))\n", clientPrefix)
				fmt.Fprintf(w, "\tl += 4\n")
				fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], id.ID())\n", clientPrefix)
				fmt.Fprintf(w, "\tl += 4\n")
			}
		case "int", "uint":
			fmt.Fprintf(w, "\t%sPutUint32(_reqBuf[l:l+4], uint32(%s))\n", clientPrefix, paramName)
			fmt.Fprintf(w, "\tl += 4\n")
		case "fixed":
			fmt.Fprintf(w, "\t%sPutFixed(_reqBuf[l:l+4], %s)\n", clientPrefix, paramName)
			fmt.Fprintf(w, "\tl += 4\n")
		case "string":
			if arg.AllowNull {
				fmt.Fprintf(w, "\tif %s == nil {\n", paramName)
				fmt.Fprintf(w, "\t\t%sPutUint32(_reqBuf[l:l+4], 0)\n", clientPrefix)
				fmt.Fprintf(w, "\t} else {\n")
				fmt.Fprintf(w, "\t\t%sPutString(_reqBuf[l:l+(4+%sLen)], *%s, %sLen)\n", clientPrefix, paramName, paramName, paramName)
				fmt.Fprintf(w, "\t}\n")
			} else {
				fmt.Fprintf(w, "\t%sPutString(_reqBuf[l:l+(4+%sLen)], %s, %sLen)\n", clientPrefix, paramName, paramName, paramName)
			}
			fmt.Fprintf(w, "\tl += (4 + %sLen)\n", paramName)
		case "array":
			fmt.Fprintf(w, "\t%sPutArray(_reqBuf[l:l+(4+%sLen)], %s)\n", clientPrefix, paramName, paramName)
			fmt.Fprintf(w, "\tl += %sLen\n", paramName)
		case "fd":
			fdIndex = i
		}
	}

	// Write message
	if fdIndex != -1 {
		for _, arg := range req.Args {
			if arg.Type == "fd" {
				paramName := escapeGoKeyword(arg.Name)
				fmt.Fprintf(w, "\toob := unix.UnixRights(int(%s))\n", paramName)
				break
			}
		}
		if canBeConst {
			fmt.Fprintf(w, "\terr := i.Context().WriteMsg(_reqBuf[:], oob)\n")
		} else {
			fmt.Fprintf(w, "\terr := i.Context().WriteMsg(_reqBuf, oob)\n")
		}
	} else {
		if canBeConst {
			fmt.Fprintf(w, "\terr := i.Context().WriteMsg(_reqBuf[:], nil)\n")
		} else {
			fmt.Fprintf(w, "\terr := i.Context().WriteMsg(_reqBuf, nil)\n")
		}
	}

	// Return statement
	returnValues := append(newObjects, "err")
	fmt.Fprintf(w, "\treturn %s\n", strings.Join(returnValues, ", "))
	fmt.Fprintf(w, "}\n\n")
}

func generateEvent(w io.Writer, event Event, ifaceName string, p Protocol) {
	eventName := ifaceName + strcase.ToCamel(event.Name) + "Event"

	// Event struct
	if event.Description.Summary != "" {
		fmt.Fprintf(w, "// %s: %s\n", eventName, cleanSummary(event.Description.Summary))
	}
	fmt.Fprintf(w, "type %s struct {\n", eventName)
	for _, arg := range event.Args {
		fieldName := strcase.ToCamel(arg.Name)
		goType := mapWaylandType(arg.Type, arg.Interface, arg.AllowNull, p)
		fmt.Fprintf(w, "\t%s %s\n", fieldName, goType)
	}
	fmt.Fprintf(w, "}\n\n")

	// Handler function type
	handlerName := ifaceName + strcase.ToCamel(event.Name) + "Handler"
	fmt.Fprintf(w, "type %s func(%s)\n\n", handlerName, eventName)
}

func writeCopyright(w io.Writer, copyright string) {
	lines := strings.Split(copyright, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" {
			fmt.Fprintf(w, "// %s\n", line)
		}
	}
}
