// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/ext-workspace/ext-workspace-v1.xml
//
// ext_workspace_v1 Protocol Copyright:
// Copyright © 2019 Christopher Billington
// Copyright © 2020 Ilia Bozhinov
// Copyright © 2022 Victoria Brekenfeld
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package ext_workspace_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ExtWorkspaceManagerV1: list and control workspaces
type ExtWorkspaceManagerV1 struct {
	client.BaseProxy
	workspaceGroupHandler ExtWorkspaceManagerV1WorkspaceGroupHandler
	workspaceHandler      ExtWorkspaceManagerV1WorkspaceHandler
	doneHandler           ExtWorkspaceManagerV1DoneHandler
	finishedHandler       ExtWorkspaceManagerV1FinishedHandler
}

// NewExtWorkspaceManagerV1 creates a new ExtWorkspaceManagerV1
func NewExtWorkspaceManagerV1(ctx *client.Context) *ExtWorkspaceManagerV1 {
	o := &ExtWorkspaceManagerV1{}
	ctx.Register(o)
	return o
}

// Commit: all requests about the workspaces have been sent
func (i *ExtWorkspaceManagerV1) Commit() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Stop: stop sending events
func (i *ExtWorkspaceManagerV1) Stop() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtWorkspaceManagerV1WorkspaceGroupEvent: a workspace group has been created
type ExtWorkspaceManagerV1WorkspaceGroupEvent struct {
	WorkspaceGroup *ExtWorkspaceGroupHandleV1
}

type ExtWorkspaceManagerV1WorkspaceGroupHandler func(ExtWorkspaceManagerV1WorkspaceGroupEvent)

// ExtWorkspaceManagerV1WorkspaceEvent: workspace has been created
type ExtWorkspaceManagerV1WorkspaceEvent struct {
	Workspace *ExtWorkspaceHandleV1
}

type ExtWorkspaceManagerV1WorkspaceHandler func(ExtWorkspaceManagerV1WorkspaceEvent)

// ExtWorkspaceManagerV1DoneEvent: all information about the workspaces and workspace groups has been sent
type ExtWorkspaceManagerV1DoneEvent struct {
}

type ExtWorkspaceManagerV1DoneHandler func(ExtWorkspaceManagerV1DoneEvent)

// ExtWorkspaceManagerV1FinishedEvent: the compositor has finished with the workspace_manager
type ExtWorkspaceManagerV1FinishedEvent struct {
}

type ExtWorkspaceManagerV1FinishedHandler func(ExtWorkspaceManagerV1FinishedEvent)

// SetWorkspaceGroupHandler sets the handler for the workspace_group event
func (i *ExtWorkspaceManagerV1) SetWorkspaceGroupHandler(f ExtWorkspaceManagerV1WorkspaceGroupHandler) {
	i.workspaceGroupHandler = f
}

// SetWorkspaceHandler sets the handler for the workspace event
func (i *ExtWorkspaceManagerV1) SetWorkspaceHandler(f ExtWorkspaceManagerV1WorkspaceHandler) {
	i.workspaceHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ExtWorkspaceManagerV1) SetDoneHandler(f ExtWorkspaceManagerV1DoneHandler) {
	i.doneHandler = f
}

// SetFinishedHandler sets the handler for the finished event
func (i *ExtWorkspaceManagerV1) SetFinishedHandler(f ExtWorkspaceManagerV1FinishedHandler) {
	i.finishedHandler = f
}

// Dispatch handles incoming events
func (i *ExtWorkspaceManagerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // workspace_group
		if i.workspaceGroupHandler != nil {
			ev := ExtWorkspaceManagerV1WorkspaceGroupEvent{}
			l := 0
			_ = fd
			workspace_groupID := client.Uint32(data[l : l+4])
			l += 4
			ev.WorkspaceGroup = i.Context().GetProxy(workspace_groupID).(*ExtWorkspaceGroupHandleV1)
			i.workspaceGroupHandler(ev)
		}
	case 1: // workspace
		if i.workspaceHandler != nil {
			ev := ExtWorkspaceManagerV1WorkspaceEvent{}
			l := 0
			_ = fd
			workspaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Workspace = i.Context().GetProxy(workspaceID).(*ExtWorkspaceHandleV1)
			i.workspaceHandler(ev)
		}
	case 2: // done
		if i.doneHandler != nil {
			ev := ExtWorkspaceManagerV1DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 3: // finished
		if i.finishedHandler != nil {
			ev := ExtWorkspaceManagerV1FinishedEvent{}
			_ = fd
			_ = data
			i.finishedHandler(ev)
		}
	}
}

// ExtWorkspaceGroupHandleV1: a workspace group assigned to a set of outputs
type ExtWorkspaceGroupHandleV1 struct {
	client.BaseProxy
	capabilitiesHandler   ExtWorkspaceGroupHandleV1CapabilitiesHandler
	outputEnterHandler    ExtWorkspaceGroupHandleV1OutputEnterHandler
	outputLeaveHandler    ExtWorkspaceGroupHandleV1OutputLeaveHandler
	workspaceEnterHandler ExtWorkspaceGroupHandleV1WorkspaceEnterHandler
	workspaceLeaveHandler ExtWorkspaceGroupHandleV1WorkspaceLeaveHandler
	removedHandler        ExtWorkspaceGroupHandleV1RemovedHandler
}

// NewExtWorkspaceGroupHandleV1 creates a new ExtWorkspaceGroupHandleV1
func NewExtWorkspaceGroupHandleV1(ctx *client.Context) *ExtWorkspaceGroupHandleV1 {
	o := &ExtWorkspaceGroupHandleV1{}
	ctx.Register(o)
	return o
}

type ExtWorkspaceGroupHandleV1GroupCapabilities uint32

const (
	ExtWorkspaceGroupHandleV1GroupCapabilitiesCreateWorkspace ExtWorkspaceGroupHandleV1GroupCapabilities = 1
)

// CreateWorkspace: create a new workspace
func (i *ExtWorkspaceGroupHandleV1) CreateWorkspace(workspace string) error {
	const opcode = 0
	workspaceLen := client.PaddedLen(len(workspace) + 1)
	_reqBufLen := 8 + (4 + workspaceLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+workspaceLen)], workspace, workspaceLen)
	l += (4 + workspaceLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the ext_workspace_group_handle_v1 object
func (i *ExtWorkspaceGroupHandleV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtWorkspaceGroupHandleV1CapabilitiesEvent: compositor capabilities
type ExtWorkspaceGroupHandleV1CapabilitiesEvent struct {
	Capabilities ExtWorkspaceGroupHandleV1GroupCapabilities
}

type ExtWorkspaceGroupHandleV1CapabilitiesHandler func(ExtWorkspaceGroupHandleV1CapabilitiesEvent)

// ExtWorkspaceGroupHandleV1OutputEnterEvent: output assigned to workspace group
type ExtWorkspaceGroupHandleV1OutputEnterEvent struct {
	Output *client.WlOutput
}

type ExtWorkspaceGroupHandleV1OutputEnterHandler func(ExtWorkspaceGroupHandleV1OutputEnterEvent)

// ExtWorkspaceGroupHandleV1OutputLeaveEvent: output removed from workspace group
type ExtWorkspaceGroupHandleV1OutputLeaveEvent struct {
	Output *client.WlOutput
}

type ExtWorkspaceGroupHandleV1OutputLeaveHandler func(ExtWorkspaceGroupHandleV1OutputLeaveEvent)

// ExtWorkspaceGroupHandleV1WorkspaceEnterEvent: workspace added to workspace group
type ExtWorkspaceGroupHandleV1WorkspaceEnterEvent struct {
	Workspace *ExtWorkspaceHandleV1
}

type ExtWorkspaceGroupHandleV1WorkspaceEnterHandler func(ExtWorkspaceGroupHandleV1WorkspaceEnterEvent)

// ExtWorkspaceGroupHandleV1WorkspaceLeaveEvent: workspace removed from workspace group
type ExtWorkspaceGroupHandleV1WorkspaceLeaveEvent struct {
	Workspace *ExtWorkspaceHandleV1
}

type ExtWorkspaceGroupHandleV1WorkspaceLeaveHandler func(ExtWorkspaceGroupHandleV1WorkspaceLeaveEvent)

// ExtWorkspaceGroupHandleV1RemovedEvent: this workspace group has been removed
type ExtWorkspaceGroupHandleV1RemovedEvent struct {
}

type ExtWorkspaceGroupHandleV1RemovedHandler func(ExtWorkspaceGroupHandleV1RemovedEvent)

// SetCapabilitiesHandler sets the handler for the capabilities event
func (i *ExtWorkspaceGroupHandleV1) SetCapabilitiesHandler(f ExtWorkspaceGroupHandleV1CapabilitiesHandler) {
	i.capabilitiesHandler = f
}

// SetOutputEnterHandler sets the handler for the output_enter event
func (i *ExtWorkspaceGroupHandleV1) SetOutputEnterHandler(f ExtWorkspaceGroupHandleV1OutputEnterHandler) {
	i.outputEnterHandler = f
}

// SetOutputLeaveHandler sets the handler for the output_leave event
func (i *ExtWorkspaceGroupHandleV1) SetOutputLeaveHandler(f ExtWorkspaceGroupHandleV1OutputLeaveHandler) {
	i.outputLeaveHandler = f
}

// SetWorkspaceEnterHandler sets the handler for the workspace_enter event
func (i *ExtWorkspaceGroupHandleV1) SetWorkspaceEnterHandler(f ExtWorkspaceGroupHandleV1WorkspaceEnterHandler) {
	i.workspaceEnterHandler = f
}

// SetWorkspaceLeaveHandler sets the handler for the workspace_leave event
func (i *ExtWorkspaceGroupHandleV1) SetWorkspaceLeaveHandler(f ExtWorkspaceGroupHandleV1WorkspaceLeaveHandler) {
	i.workspaceLeaveHandler = f
}

// SetRemovedHandler sets the handler for the removed event
func (i *ExtWorkspaceGroupHandleV1) SetRemovedHandler(f ExtWorkspaceGroupHandleV1RemovedHandler) {
	i.removedHandler = f
}

// Dispatch handles incoming events
func (i *ExtWorkspaceGroupHandleV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // capabilities
		if i.capabilitiesHandler != nil {
			ev := ExtWorkspaceGroupHandleV1CapabilitiesEvent{}
			l := 0
			_ = fd
			ev.Capabilities = ExtWorkspaceGroupHandleV1GroupCapabilities(client.Uint32(data[l : l+4]))
			l += 4
			i.capabilitiesHandler(ev)
		}
	case 1: // output_enter
		if i.outputEnterHandler != nil {
			ev := ExtWorkspaceGroupHandleV1OutputEnterEvent{}
			l := 0
			_ = fd
			outputID := client.Uint32(data[l : l+4])
			l += 4
			ev.Output = i.Context().GetProxy(outputID).(*client.WlOutput)
			i.outputEnterHandler(ev)
		}
	case 2: // output_leave
		if i.outputLeaveHandler != nil {
			ev := ExtWorkspaceGroupHandleV1OutputLeaveEvent{}
			l := 0
			_ = fd
			outputID := client.Uint32(data[l : l+4])
			l += 4
			ev.Output = i.Context().GetProxy(outputID).(*client.WlOutput)
			i.outputLeaveHandler(ev)
		}
	case 3: // workspace_enter
		if i.workspaceEnterHandler != nil {
			ev := ExtWorkspaceGroupHandleV1WorkspaceEnterEvent{}
			l := 0
			_ = fd
			workspaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Workspace = i.Context().GetProxy(workspaceID).(*ExtWorkspaceHandleV1)
			i.workspaceEnterHandler(ev)
		}
	case 4: // workspace_leave
		if i.workspaceLeaveHandler != nil {
			ev := ExtWorkspaceGroupHandleV1WorkspaceLeaveEvent{}
			l := 0
			_ = fd
			workspaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Workspace = i.Context().GetProxy(workspaceID).(*ExtWorkspaceHandleV1)
			i.workspaceLeaveHandler(ev)
		}
	case 5: // removed
		if i.removedHandler != nil {
			ev := ExtWorkspaceGroupHandleV1RemovedEvent{}
			_ = fd
			_ = data
			i.removedHandler(ev)
		}
	}
}

// ExtWorkspaceHandleV1: a workspace handing a group of surfaces
type ExtWorkspaceHandleV1 struct {
	client.BaseProxy
	idHandler           ExtWorkspaceHandleV1IdHandler
	nameHandler         ExtWorkspaceHandleV1NameHandler
	coordinatesHandler  ExtWorkspaceHandleV1CoordinatesHandler
	stateHandler        ExtWorkspaceHandleV1StateHandler
	capabilitiesHandler ExtWorkspaceHandleV1CapabilitiesHandler
	removedHandler      ExtWorkspaceHandleV1RemovedHandler
}

// NewExtWorkspaceHandleV1 creates a new ExtWorkspaceHandleV1
func NewExtWorkspaceHandleV1(ctx *client.Context) *ExtWorkspaceHandleV1 {
	o := &ExtWorkspaceHandleV1{}
	ctx.Register(o)
	return o
}

// ExtWorkspaceHandleV1State: types of states on the workspace
type ExtWorkspaceHandleV1State uint32

const (
	ExtWorkspaceHandleV1StateActive ExtWorkspaceHandleV1State = 1
	ExtWorkspaceHandleV1StateUrgent ExtWorkspaceHandleV1State = 2
	ExtWorkspaceHandleV1StateHidden ExtWorkspaceHandleV1State = 4
)

type ExtWorkspaceHandleV1WorkspaceCapabilities uint32

const (
	ExtWorkspaceHandleV1WorkspaceCapabilitiesActivate   ExtWorkspaceHandleV1WorkspaceCapabilities = 1
	ExtWorkspaceHandleV1WorkspaceCapabilitiesDeactivate ExtWorkspaceHandleV1WorkspaceCapabilities = 2
	ExtWorkspaceHandleV1WorkspaceCapabilitiesRemove     ExtWorkspaceHandleV1WorkspaceCapabilities = 4
	ExtWorkspaceHandleV1WorkspaceCapabilitiesAssign     ExtWorkspaceHandleV1WorkspaceCapabilities = 8
)

// Destroy: destroy the ext_workspace_handle_v1 object
func (i *ExtWorkspaceHandleV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Activate: activate the workspace
func (i *ExtWorkspaceHandleV1) Activate() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Deactivate: deactivate the workspace
func (i *ExtWorkspaceHandleV1) Deactivate() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Assign: assign workspace to group
func (i *ExtWorkspaceHandleV1) Assign(workspace_group *ExtWorkspaceGroupHandleV1) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], workspace_group.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Remove: remove the workspace
func (i *ExtWorkspaceHandleV1) Remove() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtWorkspaceHandleV1IdEvent: workspace id
type ExtWorkspaceHandleV1IdEvent struct {
	Id string
}

type ExtWorkspaceHandleV1IdHandler func(ExtWorkspaceHandleV1IdEvent)

// ExtWorkspaceHandleV1NameEvent: workspace name changed
type ExtWorkspaceHandleV1NameEvent struct {
	Name string
}

type ExtWorkspaceHandleV1NameHandler func(ExtWorkspaceHandleV1NameEvent)

// ExtWorkspaceHandleV1CoordinatesEvent: workspace coordinates changed
type ExtWorkspaceHandleV1CoordinatesEvent struct {
	Coordinates []byte
}

type ExtWorkspaceHandleV1CoordinatesHandler func(ExtWorkspaceHandleV1CoordinatesEvent)

// ExtWorkspaceHandleV1StateEvent: the state of the workspace changed
type ExtWorkspaceHandleV1StateEvent struct {
	State ExtWorkspaceHandleV1State
}

type ExtWorkspaceHandleV1StateHandler func(ExtWorkspaceHandleV1StateEvent)

// ExtWorkspaceHandleV1CapabilitiesEvent: compositor capabilities
type ExtWorkspaceHandleV1CapabilitiesEvent struct {
	Capabilities ExtWorkspaceHandleV1WorkspaceCapabilities
}

type ExtWorkspaceHandleV1CapabilitiesHandler func(ExtWorkspaceHandleV1CapabilitiesEvent)

// ExtWorkspaceHandleV1RemovedEvent: this workspace has been removed
type ExtWorkspaceHandleV1RemovedEvent struct {
}

type ExtWorkspaceHandleV1RemovedHandler func(ExtWorkspaceHandleV1RemovedEvent)

// SetIdHandler sets the handler for the id event
func (i *ExtWorkspaceHandleV1) SetIdHandler(f ExtWorkspaceHandleV1IdHandler) {
	i.idHandler = f
}

// SetNameHandler sets the handler for the name event
func (i *ExtWorkspaceHandleV1) SetNameHandler(f ExtWorkspaceHandleV1NameHandler) {
	i.nameHandler = f
}

// SetCoordinatesHandler sets the handler for the coordinates event
func (i *ExtWorkspaceHandleV1) SetCoordinatesHandler(f ExtWorkspaceHandleV1CoordinatesHandler) {
	i.coordinatesHandler = f
}

// SetStateHandler sets the handler for the state event
func (i *ExtWorkspaceHandleV1) SetStateHandler(f ExtWorkspaceHandleV1StateHandler) {
	i.stateHandler = f
}

// SetCapabilitiesHandler sets the handler for the capabilities event
func (i *ExtWorkspaceHandleV1) SetCapabilitiesHandler(f ExtWorkspaceHandleV1CapabilitiesHandler) {
	i.capabilitiesHandler = f
}

// SetRemovedHandler sets the handler for the removed event
func (i *ExtWorkspaceHandleV1) SetRemovedHandler(f ExtWorkspaceHandleV1RemovedHandler) {
	i.removedHandler = f
}

// Dispatch handles incoming events
func (i *ExtWorkspaceHandleV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // id
		if i.idHandler != nil {
			ev := ExtWorkspaceHandleV1IdEvent{}
			l := 0
			_ = fd
			idRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			idLen := client.PaddedLen(idRawLen)
			ev.Id = client.String(data[l : l+idLen])
			l += idLen
			i.idHandler(ev)
		}
	case 1: // name
		if i.nameHandler != nil {
			ev := ExtWorkspaceHandleV1NameEvent{}
			l := 0
			_ = fd
			nameRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			nameLen := client.PaddedLen(nameRawLen)
			ev.Name = client.String(data[l : l+nameLen])
			l += nameLen
			i.nameHandler(ev)
		}
	case 2: // coordinates
		if i.coordinatesHandler != nil {
			ev := ExtWorkspaceHandleV1CoordinatesEvent{}
			l := 0
			_ = fd
			coordinatesLen := int(client.Uint32(data[l : l+4]))
			l += 4
			ev.Coordinates = data[l : l+coordinatesLen]
			l += client.PaddedLen(coordinatesLen)
			i.coordinatesHandler(ev)
		}
	case 3: // state
		if i.stateHandler != nil {
			ev := ExtWorkspaceHandleV1StateEvent{}
			l := 0
			_ = fd
			ev.State = ExtWorkspaceHandleV1State(client.Uint32(data[l : l+4]))
			l += 4
			i.stateHandler(ev)
		}
	case 4: // capabilities
		if i.capabilitiesHandler != nil {
			ev := ExtWorkspaceHandleV1CapabilitiesEvent{}
			l := 0
			_ = fd
			ev.Capabilities = ExtWorkspaceHandleV1WorkspaceCapabilities(client.Uint32(data[l : l+4]))
			l += 4
			i.capabilitiesHandler(ev)
		}
	case 5: // removed
		if i.removedHandler != nil {
			ev := ExtWorkspaceHandleV1RemovedEvent{}
			_ = fd
			_ = data
			i.removedHandler(ev)
		}
	}
}
