// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/drm-lease/drm-lease-v1.xml
//
// drm_lease_v1 Protocol Copyright:
// Copyright © 2018 NXP
// Copyright © 2019 Status Research & Development GmbH.
// Copyright © 2021 Xaver Hugl
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package drm_lease_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// WpDrmLeaseDeviceV1: lease device
type WpDrmLeaseDeviceV1 struct {
	client.BaseProxy
}

// NewWpDrmLeaseDeviceV1 creates a new WpDrmLeaseDeviceV1
func NewWpDrmLeaseDeviceV1(ctx *client.Context) *WpDrmLeaseDeviceV1 {
	o := &WpDrmLeaseDeviceV1{}
	ctx.Register(o)
	return o
}

// CreateLeaseRequest: create a lease request object
func (i *WpDrmLeaseDeviceV1) CreateLeaseRequest() (*WpDrmLeaseRequestV1, error) {
	id := NewWpDrmLeaseRequestV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// Release: release this object
func (i *WpDrmLeaseDeviceV1) Release() error {
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpDrmLeaseDeviceV1DrmFdEvent: open a non-master fd for this DRM node
type WpDrmLeaseDeviceV1DrmFdEvent struct {
	Fd uintptr
}

type WpDrmLeaseDeviceV1DrmFdHandler func(WpDrmLeaseDeviceV1DrmFdEvent)

// WpDrmLeaseDeviceV1ConnectorEvent: advertise connectors available for leases
type WpDrmLeaseDeviceV1ConnectorEvent struct {
	Id *WpDrmLeaseConnectorV1
}

type WpDrmLeaseDeviceV1ConnectorHandler func(WpDrmLeaseDeviceV1ConnectorEvent)

// WpDrmLeaseDeviceV1DoneEvent: signals grouping of connectors
type WpDrmLeaseDeviceV1DoneEvent struct {
}

type WpDrmLeaseDeviceV1DoneHandler func(WpDrmLeaseDeviceV1DoneEvent)

// WpDrmLeaseDeviceV1ReleasedEvent: the compositor has finished using the device
type WpDrmLeaseDeviceV1ReleasedEvent struct {
}

type WpDrmLeaseDeviceV1ReleasedHandler func(WpDrmLeaseDeviceV1ReleasedEvent)

// WpDrmLeaseConnectorV1: a leasable DRM connector
type WpDrmLeaseConnectorV1 struct {
	client.BaseProxy
}

// NewWpDrmLeaseConnectorV1 creates a new WpDrmLeaseConnectorV1
func NewWpDrmLeaseConnectorV1(ctx *client.Context) *WpDrmLeaseConnectorV1 {
	o := &WpDrmLeaseConnectorV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy connector
func (i *WpDrmLeaseConnectorV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpDrmLeaseConnectorV1NameEvent: name
type WpDrmLeaseConnectorV1NameEvent struct {
	Name string
}

type WpDrmLeaseConnectorV1NameHandler func(WpDrmLeaseConnectorV1NameEvent)

// WpDrmLeaseConnectorV1DescriptionEvent: description
type WpDrmLeaseConnectorV1DescriptionEvent struct {
	Description string
}

type WpDrmLeaseConnectorV1DescriptionHandler func(WpDrmLeaseConnectorV1DescriptionEvent)

// WpDrmLeaseConnectorV1ConnectorIdEvent: connector_id
type WpDrmLeaseConnectorV1ConnectorIdEvent struct {
	ConnectorId uint32
}

type WpDrmLeaseConnectorV1ConnectorIdHandler func(WpDrmLeaseConnectorV1ConnectorIdEvent)

// WpDrmLeaseConnectorV1DoneEvent: all properties have been sent
type WpDrmLeaseConnectorV1DoneEvent struct {
}

type WpDrmLeaseConnectorV1DoneHandler func(WpDrmLeaseConnectorV1DoneEvent)

// WpDrmLeaseConnectorV1WithdrawnEvent: lease offer withdrawn
type WpDrmLeaseConnectorV1WithdrawnEvent struct {
}

type WpDrmLeaseConnectorV1WithdrawnHandler func(WpDrmLeaseConnectorV1WithdrawnEvent)

// WpDrmLeaseRequestV1: DRM lease request
type WpDrmLeaseRequestV1 struct {
	client.BaseProxy
}

// NewWpDrmLeaseRequestV1 creates a new WpDrmLeaseRequestV1
func NewWpDrmLeaseRequestV1(ctx *client.Context) *WpDrmLeaseRequestV1 {
	o := &WpDrmLeaseRequestV1{}
	ctx.Register(o)
	return o
}

type WpDrmLeaseRequestV1Error uint32

const (
	WpDrmLeaseRequestV1ErrorWrongDevice        WpDrmLeaseRequestV1Error = 0
	WpDrmLeaseRequestV1ErrorDuplicateConnector WpDrmLeaseRequestV1Error = 1
	WpDrmLeaseRequestV1ErrorEmptyLease         WpDrmLeaseRequestV1Error = 2
)

// RequestConnector: request a connector for this lease
func (i *WpDrmLeaseRequestV1) RequestConnector(connector *WpDrmLeaseConnectorV1) error {
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], connector.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Submit: submit the lease request
func (i *WpDrmLeaseRequestV1) Submit() (*WpDrmLeaseV1, error) {
	defer i.Context().Unregister(i)
	id := NewWpDrmLeaseV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WpDrmLeaseV1: a DRM lease
type WpDrmLeaseV1 struct {
	client.BaseProxy
}

// NewWpDrmLeaseV1 creates a new WpDrmLeaseV1
func NewWpDrmLeaseV1(ctx *client.Context) *WpDrmLeaseV1 {
	o := &WpDrmLeaseV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroys the lease object
func (i *WpDrmLeaseV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpDrmLeaseV1LeaseFdEvent: shares the DRM file descriptor
type WpDrmLeaseV1LeaseFdEvent struct {
	LeasedFd uintptr
}

type WpDrmLeaseV1LeaseFdHandler func(WpDrmLeaseV1LeaseFdEvent)

// WpDrmLeaseV1FinishedEvent: sent when the lease has been revoked
type WpDrmLeaseV1FinishedEvent struct {
}

type WpDrmLeaseV1FinishedHandler func(WpDrmLeaseV1FinishedEvent)
