// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml
//
// pointer_constraints_unstable_v1 Protocol Copyright:
// Copyright © 2014      Jonas Ådahl
// Copyright © 2015      Red Hat Inc.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package pointer_constraints_unstable_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZwpPointerConstraintsV1: constrain the movement of a pointer
type ZwpPointerConstraintsV1 struct {
	client.BaseProxy
}

// NewZwpPointerConstraintsV1 creates a new ZwpPointerConstraintsV1
func NewZwpPointerConstraintsV1(ctx *client.Context) *ZwpPointerConstraintsV1 {
	o := &ZwpPointerConstraintsV1{}
	ctx.Register(o)
	return o
}

// ZwpPointerConstraintsV1Error: wp_pointer_constraints error values
type ZwpPointerConstraintsV1Error uint32

const (
	ZwpPointerConstraintsV1ErrorAlreadyConstrained ZwpPointerConstraintsV1Error = 1
)

// ZwpPointerConstraintsV1Lifetime: constraint lifetime
type ZwpPointerConstraintsV1Lifetime uint32

const (
	ZwpPointerConstraintsV1LifetimeOneshot    ZwpPointerConstraintsV1Lifetime = 1
	ZwpPointerConstraintsV1LifetimePersistent ZwpPointerConstraintsV1Lifetime = 2
)

// Destroy: destroy the pointer constraints manager object
func (i *ZwpPointerConstraintsV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// LockPointer: lock pointer to a position
func (i *ZwpPointerConstraintsV1) LockPointer(surface *client.WlSurface, pointer *client.WlPointer, region *client.WlRegion, lifetime uint32) (*ZwpLockedPointerV1, error) {
	id := NewZwpLockedPointerV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	client.PutUint32(_reqBuf[l:l+4], uint32(lifetime))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ConfinePointer: confine pointer to a region
func (i *ZwpPointerConstraintsV1) ConfinePointer(surface *client.WlSurface, pointer *client.WlPointer, region *client.WlRegion, lifetime uint32) (*ZwpConfinedPointerV1, error) {
	id := NewZwpConfinedPointerV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	client.PutUint32(_reqBuf[l:l+4], uint32(lifetime))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ZwpLockedPointerV1: receive relative pointer motion events
type ZwpLockedPointerV1 struct {
	client.BaseProxy
	lockedHandler   ZwpLockedPointerV1LockedHandler
	unlockedHandler ZwpLockedPointerV1UnlockedHandler
}

// NewZwpLockedPointerV1 creates a new ZwpLockedPointerV1
func NewZwpLockedPointerV1(ctx *client.Context) *ZwpLockedPointerV1 {
	o := &ZwpLockedPointerV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the locked pointer object
func (i *ZwpLockedPointerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetCursorPositionHint: set the pointer cursor position hint
func (i *ZwpLockedPointerV1) SetCursorPositionHint(surface_x float64, surface_y float64) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutFixed(_reqBuf[l:l+4], surface_x)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], surface_y)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetRegion: set a new lock region
func (i *ZwpLockedPointerV1) SetRegion(region *client.WlRegion) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpLockedPointerV1LockedEvent: lock activation event
type ZwpLockedPointerV1LockedEvent struct {
}

type ZwpLockedPointerV1LockedHandler func(ZwpLockedPointerV1LockedEvent)

// ZwpLockedPointerV1UnlockedEvent: lock deactivation event
type ZwpLockedPointerV1UnlockedEvent struct {
}

type ZwpLockedPointerV1UnlockedHandler func(ZwpLockedPointerV1UnlockedEvent)

// SetLockedHandler sets the handler for the locked event
func (i *ZwpLockedPointerV1) SetLockedHandler(f ZwpLockedPointerV1LockedHandler) {
	i.lockedHandler = f
}

// SetUnlockedHandler sets the handler for the unlocked event
func (i *ZwpLockedPointerV1) SetUnlockedHandler(f ZwpLockedPointerV1UnlockedHandler) {
	i.unlockedHandler = f
}

// Dispatch handles incoming events
func (i *ZwpLockedPointerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // locked
		if i.lockedHandler != nil {
			ev := ZwpLockedPointerV1LockedEvent{}
			_ = fd
			_ = data
			i.lockedHandler(ev)
		}
	case 1: // unlocked
		if i.unlockedHandler != nil {
			ev := ZwpLockedPointerV1UnlockedEvent{}
			_ = fd
			_ = data
			i.unlockedHandler(ev)
		}
	}
}

// ZwpConfinedPointerV1: confined pointer object
type ZwpConfinedPointerV1 struct {
	client.BaseProxy
	confinedHandler   ZwpConfinedPointerV1ConfinedHandler
	unconfinedHandler ZwpConfinedPointerV1UnconfinedHandler
}

// NewZwpConfinedPointerV1 creates a new ZwpConfinedPointerV1
func NewZwpConfinedPointerV1(ctx *client.Context) *ZwpConfinedPointerV1 {
	o := &ZwpConfinedPointerV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the confined pointer object
func (i *ZwpConfinedPointerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetRegion: set a new confine region
func (i *ZwpConfinedPointerV1) SetRegion(region *client.WlRegion) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if region == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], region.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpConfinedPointerV1ConfinedEvent: pointer confined
type ZwpConfinedPointerV1ConfinedEvent struct {
}

type ZwpConfinedPointerV1ConfinedHandler func(ZwpConfinedPointerV1ConfinedEvent)

// ZwpConfinedPointerV1UnconfinedEvent: pointer unconfined
type ZwpConfinedPointerV1UnconfinedEvent struct {
}

type ZwpConfinedPointerV1UnconfinedHandler func(ZwpConfinedPointerV1UnconfinedEvent)

// SetConfinedHandler sets the handler for the confined event
func (i *ZwpConfinedPointerV1) SetConfinedHandler(f ZwpConfinedPointerV1ConfinedHandler) {
	i.confinedHandler = f
}

// SetUnconfinedHandler sets the handler for the unconfined event
func (i *ZwpConfinedPointerV1) SetUnconfinedHandler(f ZwpConfinedPointerV1UnconfinedHandler) {
	i.unconfinedHandler = f
}

// Dispatch handles incoming events
func (i *ZwpConfinedPointerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // confined
		if i.confinedHandler != nil {
			ev := ZwpConfinedPointerV1ConfinedEvent{}
			_ = fd
			_ = data
			i.confinedHandler(ev)
		}
	case 1: // unconfined
		if i.unconfinedHandler != nil {
			ev := ZwpConfinedPointerV1UnconfinedEvent{}
			_ = fd
			_ = data
			i.unconfinedHandler(ev)
		}
	}
}
