// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/stable/viewporter/viewporter.xml
//
// viewporter Protocol Copyright:
// Copyright © 2013-2016 Collabora, Ltd.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package viewporter

import (
	"github.com/tri2820/cheese/protocols/client"
)

// WpViewporter: surface cropping and scaling
type WpViewporter struct {
	client.BaseProxy
}

// NewWpViewporter creates a new WpViewporter
func NewWpViewporter(ctx *client.Context) *WpViewporter {
	o := &WpViewporter{}
	ctx.Register(o)
	return o
}

type WpViewporterError uint32

const (
	WpViewporterErrorViewportExists WpViewporterError = 0
)

// Destroy: unbind from the cropping and scaling interface
func (i *WpViewporter) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetViewport: extend surface interface for crop and scale
func (i *WpViewporter) GetViewport(surface *client.WlSurface) (*WpViewport, error) {
	id := NewWpViewport(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// WpViewport: crop and scale interface to a wl_surface
type WpViewport struct {
	client.BaseProxy
}

// NewWpViewport creates a new WpViewport
func NewWpViewport(ctx *client.Context) *WpViewport {
	o := &WpViewport{}
	ctx.Register(o)
	return o
}

type WpViewportError uint32

const (
	WpViewportErrorBadValue    WpViewportError = 0
	WpViewportErrorBadSize     WpViewportError = 1
	WpViewportErrorOutOfBuffer WpViewportError = 2
	WpViewportErrorNoSurface   WpViewportError = 3
)

// Destroy: remove scaling and cropping from the surface
func (i *WpViewport) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSource: set the source rectangle for cropping
func (i *WpViewport) SetSource(x float64, y float64, width float64, height float64) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutFixed(_reqBuf[l:l+4], x)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], y)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], width)
	l += 4
	client.PutFixed(_reqBuf[l:l+4], height)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetDestination: set the surface size for scaling
func (i *WpViewport) SetDestination(width int32, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
