// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/ext-session-lock/ext-session-lock-v1.xml
//
// ext_session_lock_v1 Protocol Copyright:
// Copyright 2021 Isaac Freund
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package ext_session_lock_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ExtSessionLockManagerV1: used to lock the session
type ExtSessionLockManagerV1 struct {
	client.BaseProxy
}

// NewExtSessionLockManagerV1 creates a new ExtSessionLockManagerV1
func NewExtSessionLockManagerV1(ctx *client.Context) *ExtSessionLockManagerV1 {
	o := &ExtSessionLockManagerV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the session lock manager object
func (i *ExtSessionLockManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Lock: attempt to lock the session
func (i *ExtSessionLockManagerV1) Lock() (*ExtSessionLockV1, error) {
	id := NewExtSessionLockV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ExtSessionLockV1: manage lock state and create lock surfaces
type ExtSessionLockV1 struct {
	client.BaseProxy
}

// NewExtSessionLockV1 creates a new ExtSessionLockV1
func NewExtSessionLockV1(ctx *client.Context) *ExtSessionLockV1 {
	o := &ExtSessionLockV1{}
	ctx.Register(o)
	return o
}

type ExtSessionLockV1Error uint32

const (
	ExtSessionLockV1ErrorInvalidDestroy     ExtSessionLockV1Error = 0
	ExtSessionLockV1ErrorInvalidUnlock      ExtSessionLockV1Error = 1
	ExtSessionLockV1ErrorRole               ExtSessionLockV1Error = 2
	ExtSessionLockV1ErrorDuplicateOutput    ExtSessionLockV1Error = 3
	ExtSessionLockV1ErrorAlreadyConstructed ExtSessionLockV1Error = 4
)

// Destroy: destroy the session lock
func (i *ExtSessionLockV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetLockSurface: create a lock surface for a given output
func (i *ExtSessionLockV1) GetLockSurface(surface *client.WlSurface, output *client.WlOutput) (*ExtSessionLockSurfaceV1, error) {
	id := NewExtSessionLockSurfaceV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// UnlockAndDestroy: unlock the session, destroying the object
func (i *ExtSessionLockV1) UnlockAndDestroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtSessionLockV1LockedEvent: session successfully locked
type ExtSessionLockV1LockedEvent struct {
}

type ExtSessionLockV1LockedHandler func(ExtSessionLockV1LockedEvent)

// ExtSessionLockV1FinishedEvent: the session lock object should be destroyed
type ExtSessionLockV1FinishedEvent struct {
}

type ExtSessionLockV1FinishedHandler func(ExtSessionLockV1FinishedEvent)

// ExtSessionLockSurfaceV1: a surface displayed while the session is locked
type ExtSessionLockSurfaceV1 struct {
	client.BaseProxy
}

// NewExtSessionLockSurfaceV1 creates a new ExtSessionLockSurfaceV1
func NewExtSessionLockSurfaceV1(ctx *client.Context) *ExtSessionLockSurfaceV1 {
	o := &ExtSessionLockSurfaceV1{}
	ctx.Register(o)
	return o
}

type ExtSessionLockSurfaceV1Error uint32

const (
	ExtSessionLockSurfaceV1ErrorCommitBeforeFirstAck ExtSessionLockSurfaceV1Error = 0
	ExtSessionLockSurfaceV1ErrorNullBuffer           ExtSessionLockSurfaceV1Error = 1
	ExtSessionLockSurfaceV1ErrorDimensionsMismatch   ExtSessionLockSurfaceV1Error = 2
	ExtSessionLockSurfaceV1ErrorInvalidSerial        ExtSessionLockSurfaceV1Error = 3
)

// Destroy: destroy the lock surface object
func (i *ExtSessionLockSurfaceV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AckConfigure: ack a configure event
func (i *ExtSessionLockSurfaceV1) AckConfigure(serial uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ExtSessionLockSurfaceV1ConfigureEvent: the client should resize its surface
type ExtSessionLockSurfaceV1ConfigureEvent struct {
	Serial uint32
	Width  uint32
	Height uint32
}

type ExtSessionLockSurfaceV1ConfigureHandler func(ExtSessionLockSurfaceV1ConfigureEvent)
