// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/staging/color-management/color-management-v1.xml
//
// color_management_v1 Protocol Copyright:
// Copyright 2019 Sebastian Wick
// Copyright 2019 Erwin Burema
// Copyright 2020 AMD
// Copyright 2020-2024 Collabora, Ltd.
// Copyright 2024 Xaver Hugl
// Copyright 2022-2025 Red Hat, Inc.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package color_management_v1

import (
	"github.com/tri2820/cheese/protocols/client"
	"golang.org/x/sys/unix"
)

// WpColorManagerV1: color manager singleton
type WpColorManagerV1 struct {
	client.BaseProxy
	supportedIntentHandler         WpColorManagerV1SupportedIntentHandler
	supportedFeatureHandler        WpColorManagerV1SupportedFeatureHandler
	supportedTfNamedHandler        WpColorManagerV1SupportedTfNamedHandler
	supportedPrimariesNamedHandler WpColorManagerV1SupportedPrimariesNamedHandler
	doneHandler                    WpColorManagerV1DoneHandler
}

// NewWpColorManagerV1 creates a new WpColorManagerV1
func NewWpColorManagerV1(ctx *client.Context) *WpColorManagerV1 {
	o := &WpColorManagerV1{}
	ctx.Register(o)
	return o
}

type WpColorManagerV1Error uint32

const (
	WpColorManagerV1ErrorUnsupportedFeature WpColorManagerV1Error = 0
	WpColorManagerV1ErrorSurfaceExists      WpColorManagerV1Error = 1
)

// WpColorManagerV1RenderIntent: rendering intents
type WpColorManagerV1RenderIntent uint32

const (
	WpColorManagerV1RenderIntentPerceptual           WpColorManagerV1RenderIntent = 0
	WpColorManagerV1RenderIntentRelative             WpColorManagerV1RenderIntent = 1
	WpColorManagerV1RenderIntentSaturation           WpColorManagerV1RenderIntent = 2
	WpColorManagerV1RenderIntentAbsolute             WpColorManagerV1RenderIntent = 3
	WpColorManagerV1RenderIntentRelativeBpc          WpColorManagerV1RenderIntent = 4
	WpColorManagerV1RenderIntentAbsoluteNoAdaptation WpColorManagerV1RenderIntent = 5
)

// WpColorManagerV1Feature: compositor supported features
type WpColorManagerV1Feature uint32

const (
	WpColorManagerV1FeatureIccV2V4                      WpColorManagerV1Feature = 0
	WpColorManagerV1FeatureParametric                   WpColorManagerV1Feature = 1
	WpColorManagerV1FeatureSetPrimaries                 WpColorManagerV1Feature = 2
	WpColorManagerV1FeatureSetTfPower                   WpColorManagerV1Feature = 3
	WpColorManagerV1FeatureSetLuminances                WpColorManagerV1Feature = 4
	WpColorManagerV1FeatureSetMasteringDisplayPrimaries WpColorManagerV1Feature = 5
	WpColorManagerV1FeatureExtendedTargetVolume         WpColorManagerV1Feature = 6
	WpColorManagerV1FeatureWindowsScrgb                 WpColorManagerV1Feature = 7
)

// WpColorManagerV1Primaries: named color primaries
type WpColorManagerV1Primaries uint32

const (
	WpColorManagerV1PrimariesSrgb        WpColorManagerV1Primaries = 1
	WpColorManagerV1PrimariesPalM        WpColorManagerV1Primaries = 2
	WpColorManagerV1PrimariesPal         WpColorManagerV1Primaries = 3
	WpColorManagerV1PrimariesNtsc        WpColorManagerV1Primaries = 4
	WpColorManagerV1PrimariesGenericFilm WpColorManagerV1Primaries = 5
	WpColorManagerV1PrimariesBt2020      WpColorManagerV1Primaries = 6
	WpColorManagerV1PrimariesCie1931Xyz  WpColorManagerV1Primaries = 7
	WpColorManagerV1PrimariesDciP3       WpColorManagerV1Primaries = 8
	WpColorManagerV1PrimariesDisplayP3   WpColorManagerV1Primaries = 9
	WpColorManagerV1PrimariesAdobeRgb    WpColorManagerV1Primaries = 10
)

// WpColorManagerV1TransferFunction: named transfer functions
type WpColorManagerV1TransferFunction uint32

const (
	WpColorManagerV1TransferFunctionBt1886          WpColorManagerV1TransferFunction = 1
	WpColorManagerV1TransferFunctionGamma22         WpColorManagerV1TransferFunction = 2
	WpColorManagerV1TransferFunctionGamma28         WpColorManagerV1TransferFunction = 3
	WpColorManagerV1TransferFunctionSt240           WpColorManagerV1TransferFunction = 4
	WpColorManagerV1TransferFunctionExtLinear       WpColorManagerV1TransferFunction = 5
	WpColorManagerV1TransferFunctionLog100          WpColorManagerV1TransferFunction = 6
	WpColorManagerV1TransferFunctionLog316          WpColorManagerV1TransferFunction = 7
	WpColorManagerV1TransferFunctionXvycc           WpColorManagerV1TransferFunction = 8
	WpColorManagerV1TransferFunctionSrgb            WpColorManagerV1TransferFunction = 9
	WpColorManagerV1TransferFunctionExtSrgb         WpColorManagerV1TransferFunction = 10
	WpColorManagerV1TransferFunctionSt2084Pq        WpColorManagerV1TransferFunction = 11
	WpColorManagerV1TransferFunctionSt428           WpColorManagerV1TransferFunction = 12
	WpColorManagerV1TransferFunctionHlg             WpColorManagerV1TransferFunction = 13
	WpColorManagerV1TransferFunctionCompoundPower24 WpColorManagerV1TransferFunction = 14
)

// Destroy: destroy the color manager
func (i *WpColorManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetOutput: create a color management interface for a wl_output
func (i *WpColorManagerV1) GetOutput(output *client.WlOutput) (*WpColorManagementOutputV1, error) {
	id := NewWpColorManagementOutputV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetSurface: create a color management interface for a wl_surface
func (i *WpColorManagerV1) GetSurface(surface *client.WlSurface) (*WpColorManagementSurfaceV1, error) {
	id := NewWpColorManagementSurfaceV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetSurfaceFeedback: create a color management feedback interface
func (i *WpColorManagerV1) GetSurfaceFeedback(surface *client.WlSurface) (*WpColorManagementSurfaceFeedbackV1, error) {
	id := NewWpColorManagementSurfaceFeedbackV1(i.Context())
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// CreateIccCreator: make a new ICC-based image description creator object
func (i *WpColorManagerV1) CreateIccCreator() (*WpImageDescriptionCreatorIccV1, error) {
	obj := NewWpImageDescriptionCreatorIccV1(i.Context())
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], obj.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return obj, err
}

// CreateParametricCreator: make a new parametric image description creator object
func (i *WpColorManagerV1) CreateParametricCreator() (*WpImageDescriptionCreatorParamsV1, error) {
	obj := NewWpImageDescriptionCreatorParamsV1(i.Context())
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], obj.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return obj, err
}

// CreateWindowsScrgb: create Windows-scRGB image description object
func (i *WpColorManagerV1) CreateWindowsScrgb() (*WpImageDescriptionV1, error) {
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 6
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// GetImageDescription: create an image description from a reference
func (i *WpColorManagerV1) GetImageDescription(reference *WpImageDescriptionReferenceV1) (*WpImageDescriptionV1, error) {
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 7
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], reference.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// WpColorManagerV1SupportedIntentEvent: supported rendering intent
type WpColorManagerV1SupportedIntentEvent struct {
	RenderIntent uint32
}

type WpColorManagerV1SupportedIntentHandler func(WpColorManagerV1SupportedIntentEvent)

// WpColorManagerV1SupportedFeatureEvent: supported features
type WpColorManagerV1SupportedFeatureEvent struct {
	Feature uint32
}

type WpColorManagerV1SupportedFeatureHandler func(WpColorManagerV1SupportedFeatureEvent)

// WpColorManagerV1SupportedTfNamedEvent: supported named transfer characteristic
type WpColorManagerV1SupportedTfNamedEvent struct {
	Tf uint32
}

type WpColorManagerV1SupportedTfNamedHandler func(WpColorManagerV1SupportedTfNamedEvent)

// WpColorManagerV1SupportedPrimariesNamedEvent: supported named primaries
type WpColorManagerV1SupportedPrimariesNamedEvent struct {
	Primaries uint32
}

type WpColorManagerV1SupportedPrimariesNamedHandler func(WpColorManagerV1SupportedPrimariesNamedEvent)

// WpColorManagerV1DoneEvent: all features have been sent
type WpColorManagerV1DoneEvent struct {
}

type WpColorManagerV1DoneHandler func(WpColorManagerV1DoneEvent)

// SetSupportedIntentHandler sets the handler for the supported_intent event
func (i *WpColorManagerV1) SetSupportedIntentHandler(f WpColorManagerV1SupportedIntentHandler) {
	i.supportedIntentHandler = f
}

// SetSupportedFeatureHandler sets the handler for the supported_feature event
func (i *WpColorManagerV1) SetSupportedFeatureHandler(f WpColorManagerV1SupportedFeatureHandler) {
	i.supportedFeatureHandler = f
}

// SetSupportedTfNamedHandler sets the handler for the supported_tf_named event
func (i *WpColorManagerV1) SetSupportedTfNamedHandler(f WpColorManagerV1SupportedTfNamedHandler) {
	i.supportedTfNamedHandler = f
}

// SetSupportedPrimariesNamedHandler sets the handler for the supported_primaries_named event
func (i *WpColorManagerV1) SetSupportedPrimariesNamedHandler(f WpColorManagerV1SupportedPrimariesNamedHandler) {
	i.supportedPrimariesNamedHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *WpColorManagerV1) SetDoneHandler(f WpColorManagerV1DoneHandler) {
	i.doneHandler = f
}

// Dispatch handles incoming events
func (i *WpColorManagerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // supported_intent
		if i.supportedIntentHandler != nil {
			ev := WpColorManagerV1SupportedIntentEvent{}
			l := 0
			_ = fd
			ev.RenderIntent = client.Uint32(data[l : l+4])
			l += 4
			i.supportedIntentHandler(ev)
		}
	case 1: // supported_feature
		if i.supportedFeatureHandler != nil {
			ev := WpColorManagerV1SupportedFeatureEvent{}
			l := 0
			_ = fd
			ev.Feature = client.Uint32(data[l : l+4])
			l += 4
			i.supportedFeatureHandler(ev)
		}
	case 2: // supported_tf_named
		if i.supportedTfNamedHandler != nil {
			ev := WpColorManagerV1SupportedTfNamedEvent{}
			l := 0
			_ = fd
			ev.Tf = client.Uint32(data[l : l+4])
			l += 4
			i.supportedTfNamedHandler(ev)
		}
	case 3: // supported_primaries_named
		if i.supportedPrimariesNamedHandler != nil {
			ev := WpColorManagerV1SupportedPrimariesNamedEvent{}
			l := 0
			_ = fd
			ev.Primaries = client.Uint32(data[l : l+4])
			l += 4
			i.supportedPrimariesNamedHandler(ev)
		}
	case 4: // done
		if i.doneHandler != nil {
			ev := WpColorManagerV1DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	}
}

// WpColorManagementOutputV1: output color properties
type WpColorManagementOutputV1 struct {
	client.BaseProxy
	imageDescriptionChangedHandler WpColorManagementOutputV1ImageDescriptionChangedHandler
}

// NewWpColorManagementOutputV1 creates a new WpColorManagementOutputV1
func NewWpColorManagementOutputV1(ctx *client.Context) *WpColorManagementOutputV1 {
	o := &WpColorManagementOutputV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the color management output
func (i *WpColorManagementOutputV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetImageDescription: get the image description of the output
func (i *WpColorManagementOutputV1) GetImageDescription() (*WpImageDescriptionV1, error) {
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// WpColorManagementOutputV1ImageDescriptionChangedEvent: image description changed
type WpColorManagementOutputV1ImageDescriptionChangedEvent struct {
}

type WpColorManagementOutputV1ImageDescriptionChangedHandler func(WpColorManagementOutputV1ImageDescriptionChangedEvent)

// SetImageDescriptionChangedHandler sets the handler for the image_description_changed event
func (i *WpColorManagementOutputV1) SetImageDescriptionChangedHandler(f WpColorManagementOutputV1ImageDescriptionChangedHandler) {
	i.imageDescriptionChangedHandler = f
}

// Dispatch handles incoming events
func (i *WpColorManagementOutputV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // image_description_changed
		if i.imageDescriptionChangedHandler != nil {
			ev := WpColorManagementOutputV1ImageDescriptionChangedEvent{}
			_ = fd
			_ = data
			i.imageDescriptionChangedHandler(ev)
		}
	}
}

// WpColorManagementSurfaceV1: color management extension to a surface
type WpColorManagementSurfaceV1 struct {
	client.BaseProxy
}

// NewWpColorManagementSurfaceV1 creates a new WpColorManagementSurfaceV1
func NewWpColorManagementSurfaceV1(ctx *client.Context) *WpColorManagementSurfaceV1 {
	o := &WpColorManagementSurfaceV1{}
	ctx.Register(o)
	return o
}

// WpColorManagementSurfaceV1Error: protocol errors
type WpColorManagementSurfaceV1Error uint32

const (
	WpColorManagementSurfaceV1ErrorRenderIntent     WpColorManagementSurfaceV1Error = 0
	WpColorManagementSurfaceV1ErrorImageDescription WpColorManagementSurfaceV1Error = 1
	WpColorManagementSurfaceV1ErrorInert            WpColorManagementSurfaceV1Error = 2
)

// Destroy: destroy the color management interface for a surface
func (i *WpColorManagementSurfaceV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetImageDescription: set the surface image description
func (i *WpColorManagementSurfaceV1) SetImageDescription(image_description *WpImageDescriptionV1, render_intent uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(render_intent))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// UnsetImageDescription: remove the surface image description
func (i *WpColorManagementSurfaceV1) UnsetImageDescription() error {
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpColorManagementSurfaceFeedbackV1: color management extension to a surface
type WpColorManagementSurfaceFeedbackV1 struct {
	client.BaseProxy
	preferredChangedHandler  WpColorManagementSurfaceFeedbackV1PreferredChangedHandler
	preferredChanged2Handler WpColorManagementSurfaceFeedbackV1PreferredChanged2Handler
}

// NewWpColorManagementSurfaceFeedbackV1 creates a new WpColorManagementSurfaceFeedbackV1
func NewWpColorManagementSurfaceFeedbackV1(ctx *client.Context) *WpColorManagementSurfaceFeedbackV1 {
	o := &WpColorManagementSurfaceFeedbackV1{}
	ctx.Register(o)
	return o
}

// WpColorManagementSurfaceFeedbackV1Error: protocol errors
type WpColorManagementSurfaceFeedbackV1Error uint32

const (
	WpColorManagementSurfaceFeedbackV1ErrorInert              WpColorManagementSurfaceFeedbackV1Error = 0
	WpColorManagementSurfaceFeedbackV1ErrorUnsupportedFeature WpColorManagementSurfaceFeedbackV1Error = 1
)

// Destroy: destroy the color management interface for a surface
func (i *WpColorManagementSurfaceFeedbackV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetPreferred: get the preferred image description
func (i *WpColorManagementSurfaceFeedbackV1) GetPreferred() (*WpImageDescriptionV1, error) {
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// GetPreferredParametric: get the preferred image description
func (i *WpColorManagementSurfaceFeedbackV1) GetPreferredParametric() (*WpImageDescriptionV1, error) {
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// WpColorManagementSurfaceFeedbackV1PreferredChangedEvent: the preferred image description changed (32-bit)
type WpColorManagementSurfaceFeedbackV1PreferredChangedEvent struct {
	Identity uint32
}

type WpColorManagementSurfaceFeedbackV1PreferredChangedHandler func(WpColorManagementSurfaceFeedbackV1PreferredChangedEvent)

// WpColorManagementSurfaceFeedbackV1PreferredChanged2Event: the preferred image description changed
type WpColorManagementSurfaceFeedbackV1PreferredChanged2Event struct {
	IdentityHi uint32
	IdentityLo uint32
}

type WpColorManagementSurfaceFeedbackV1PreferredChanged2Handler func(WpColorManagementSurfaceFeedbackV1PreferredChanged2Event)

// SetPreferredChangedHandler sets the handler for the preferred_changed event
func (i *WpColorManagementSurfaceFeedbackV1) SetPreferredChangedHandler(f WpColorManagementSurfaceFeedbackV1PreferredChangedHandler) {
	i.preferredChangedHandler = f
}

// SetPreferredChanged2Handler sets the handler for the preferred_changed2 event
func (i *WpColorManagementSurfaceFeedbackV1) SetPreferredChanged2Handler(f WpColorManagementSurfaceFeedbackV1PreferredChanged2Handler) {
	i.preferredChanged2Handler = f
}

// Dispatch handles incoming events
func (i *WpColorManagementSurfaceFeedbackV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // preferred_changed
		if i.preferredChangedHandler != nil {
			ev := WpColorManagementSurfaceFeedbackV1PreferredChangedEvent{}
			l := 0
			_ = fd
			ev.Identity = client.Uint32(data[l : l+4])
			l += 4
			i.preferredChangedHandler(ev)
		}
	case 1: // preferred_changed2
		if i.preferredChanged2Handler != nil {
			ev := WpColorManagementSurfaceFeedbackV1PreferredChanged2Event{}
			l := 0
			_ = fd
			ev.IdentityHi = client.Uint32(data[l : l+4])
			l += 4
			ev.IdentityLo = client.Uint32(data[l : l+4])
			l += 4
			i.preferredChanged2Handler(ev)
		}
	}
}

// WpImageDescriptionCreatorIccV1: holder of image description ICC information
type WpImageDescriptionCreatorIccV1 struct {
	client.BaseProxy
}

// NewWpImageDescriptionCreatorIccV1 creates a new WpImageDescriptionCreatorIccV1
func NewWpImageDescriptionCreatorIccV1(ctx *client.Context) *WpImageDescriptionCreatorIccV1 {
	o := &WpImageDescriptionCreatorIccV1{}
	ctx.Register(o)
	return o
}

// WpImageDescriptionCreatorIccV1Error: protocol errors
type WpImageDescriptionCreatorIccV1Error uint32

const (
	WpImageDescriptionCreatorIccV1ErrorIncompleteSet WpImageDescriptionCreatorIccV1Error = 0
	WpImageDescriptionCreatorIccV1ErrorAlreadySet    WpImageDescriptionCreatorIccV1Error = 1
	WpImageDescriptionCreatorIccV1ErrorBadFd         WpImageDescriptionCreatorIccV1Error = 2
	WpImageDescriptionCreatorIccV1ErrorBadSize       WpImageDescriptionCreatorIccV1Error = 3
	WpImageDescriptionCreatorIccV1ErrorOutOfFile     WpImageDescriptionCreatorIccV1Error = 4
)

// Create: Create the image description object from ICC data
func (i *WpImageDescriptionCreatorIccV1) Create() (*WpImageDescriptionV1, error) {
	defer i.Context().Unregister(i)
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// SetIccFile: set the ICC profile file
func (i *WpImageDescriptionCreatorIccV1) SetIccFile(icc_profile uintptr, offset uint32, length uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(offset))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(length))
	l += 4
	oob := unix.UnixRights(int(icc_profile))
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return err
}

// WpImageDescriptionCreatorParamsV1: holder of image description parameters
type WpImageDescriptionCreatorParamsV1 struct {
	client.BaseProxy
}

// NewWpImageDescriptionCreatorParamsV1 creates a new WpImageDescriptionCreatorParamsV1
func NewWpImageDescriptionCreatorParamsV1(ctx *client.Context) *WpImageDescriptionCreatorParamsV1 {
	o := &WpImageDescriptionCreatorParamsV1{}
	ctx.Register(o)
	return o
}

// WpImageDescriptionCreatorParamsV1Error: protocol errors
type WpImageDescriptionCreatorParamsV1Error uint32

const (
	WpImageDescriptionCreatorParamsV1ErrorIncompleteSet         WpImageDescriptionCreatorParamsV1Error = 0
	WpImageDescriptionCreatorParamsV1ErrorAlreadySet            WpImageDescriptionCreatorParamsV1Error = 1
	WpImageDescriptionCreatorParamsV1ErrorUnsupportedFeature    WpImageDescriptionCreatorParamsV1Error = 2
	WpImageDescriptionCreatorParamsV1ErrorInvalidTf             WpImageDescriptionCreatorParamsV1Error = 3
	WpImageDescriptionCreatorParamsV1ErrorInvalidPrimariesNamed WpImageDescriptionCreatorParamsV1Error = 4
	WpImageDescriptionCreatorParamsV1ErrorInvalidLuminance      WpImageDescriptionCreatorParamsV1Error = 5
)

// Create: Create the image description object using params
func (i *WpImageDescriptionCreatorParamsV1) Create() (*WpImageDescriptionV1, error) {
	defer i.Context().Unregister(i)
	image_description := NewWpImageDescriptionV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], image_description.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return image_description, err
}

// SetTfNamed: named transfer characteristic
func (i *WpImageDescriptionCreatorParamsV1) SetTfNamed(tf uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(tf))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetTfPower: transfer characteristic as a power curve
func (i *WpImageDescriptionCreatorParamsV1) SetTfPower(eexp uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(eexp))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPrimariesNamed: named primaries
func (i *WpImageDescriptionCreatorParamsV1) SetPrimariesNamed(primaries uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(primaries))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPrimaries: primaries as chromaticity coordinates
func (i *WpImageDescriptionCreatorParamsV1) SetPrimaries(r_x int32, r_y int32, g_x int32, g_y int32, b_x int32, b_y int32, w_x int32, w_y int32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(r_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(r_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(g_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(g_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(b_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(b_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(w_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(w_y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetLuminances: primary color volume luminance range and reference white
func (i *WpImageDescriptionCreatorParamsV1) SetLuminances(min_lum uint32, max_lum uint32, reference_lum uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(min_lum))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(max_lum))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(reference_lum))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMasteringDisplayPrimaries: mastering display primaries as chromaticity coordinates
func (i *WpImageDescriptionCreatorParamsV1) SetMasteringDisplayPrimaries(r_x int32, r_y int32, g_x int32, g_y int32, b_x int32, b_y int32, w_x int32, w_y int32) error {
	const opcode = 6
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(r_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(r_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(g_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(g_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(b_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(b_y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(w_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(w_y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMasteringLuminance: display mastering luminance range
func (i *WpImageDescriptionCreatorParamsV1) SetMasteringLuminance(min_lum uint32, max_lum uint32) error {
	const opcode = 7
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(min_lum))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(max_lum))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaxCll: maximum content light level
func (i *WpImageDescriptionCreatorParamsV1) SetMaxCll(max_cll uint32) error {
	const opcode = 8
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(max_cll))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetMaxFall: maximum frame-average light level
func (i *WpImageDescriptionCreatorParamsV1) SetMaxFall(max_fall uint32) error {
	const opcode = 9
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(max_fall))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// WpImageDescriptionV1: Colorimetric image description
type WpImageDescriptionV1 struct {
	client.BaseProxy
	failedHandler WpImageDescriptionV1FailedHandler
	readyHandler  WpImageDescriptionV1ReadyHandler
	ready2Handler WpImageDescriptionV1Ready2Handler
}

// NewWpImageDescriptionV1 creates a new WpImageDescriptionV1
func NewWpImageDescriptionV1(ctx *client.Context) *WpImageDescriptionV1 {
	o := &WpImageDescriptionV1{}
	ctx.Register(o)
	return o
}

// WpImageDescriptionV1Error: protocol errors
type WpImageDescriptionV1Error uint32

const (
	WpImageDescriptionV1ErrorNotReady      WpImageDescriptionV1Error = 0
	WpImageDescriptionV1ErrorNoInformation WpImageDescriptionV1Error = 1
)

// WpImageDescriptionV1Cause: generic reason for failure
type WpImageDescriptionV1Cause uint32

const (
	WpImageDescriptionV1CauseLowVersion      WpImageDescriptionV1Cause = 0
	WpImageDescriptionV1CauseUnsupported     WpImageDescriptionV1Cause = 1
	WpImageDescriptionV1CauseOperatingSystem WpImageDescriptionV1Cause = 2
	WpImageDescriptionV1CauseNoOutput        WpImageDescriptionV1Cause = 3
)

// Destroy: destroy the image description
func (i *WpImageDescriptionV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetInformation: get information about the image description
func (i *WpImageDescriptionV1) GetInformation() (*WpImageDescriptionInfoV1, error) {
	information := NewWpImageDescriptionInfoV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], information.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return information, err
}

// WpImageDescriptionV1FailedEvent: graceful error on creating the image description
type WpImageDescriptionV1FailedEvent struct {
	Cause uint32
	Msg   string
}

type WpImageDescriptionV1FailedHandler func(WpImageDescriptionV1FailedEvent)

// WpImageDescriptionV1ReadyEvent: the object is ready to be used (32-bit)
type WpImageDescriptionV1ReadyEvent struct {
	Identity uint32
}

type WpImageDescriptionV1ReadyHandler func(WpImageDescriptionV1ReadyEvent)

// WpImageDescriptionV1Ready2Event: the object is ready to be used
type WpImageDescriptionV1Ready2Event struct {
	IdentityHi uint32
	IdentityLo uint32
}

type WpImageDescriptionV1Ready2Handler func(WpImageDescriptionV1Ready2Event)

// SetFailedHandler sets the handler for the failed event
func (i *WpImageDescriptionV1) SetFailedHandler(f WpImageDescriptionV1FailedHandler) {
	i.failedHandler = f
}

// SetReadyHandler sets the handler for the ready event
func (i *WpImageDescriptionV1) SetReadyHandler(f WpImageDescriptionV1ReadyHandler) {
	i.readyHandler = f
}

// SetReady2Handler sets the handler for the ready2 event
func (i *WpImageDescriptionV1) SetReady2Handler(f WpImageDescriptionV1Ready2Handler) {
	i.ready2Handler = f
}

// Dispatch handles incoming events
func (i *WpImageDescriptionV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // failed
		if i.failedHandler != nil {
			ev := WpImageDescriptionV1FailedEvent{}
			l := 0
			_ = fd
			ev.Cause = client.Uint32(data[l : l+4])
			l += 4
			msgRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			msgLen := client.PaddedLen(msgRawLen)
			ev.Msg = client.String(data[l : l+msgLen])
			l += msgLen
			i.failedHandler(ev)
		}
	case 1: // ready
		if i.readyHandler != nil {
			ev := WpImageDescriptionV1ReadyEvent{}
			l := 0
			_ = fd
			ev.Identity = client.Uint32(data[l : l+4])
			l += 4
			i.readyHandler(ev)
		}
	case 2: // ready2
		if i.ready2Handler != nil {
			ev := WpImageDescriptionV1Ready2Event{}
			l := 0
			_ = fd
			ev.IdentityHi = client.Uint32(data[l : l+4])
			l += 4
			ev.IdentityLo = client.Uint32(data[l : l+4])
			l += 4
			i.ready2Handler(ev)
		}
	}
}

// WpImageDescriptionInfoV1: Colorimetric image description information
type WpImageDescriptionInfoV1 struct {
	client.BaseProxy
	doneHandler            WpImageDescriptionInfoV1DoneHandler
	iccFileHandler         WpImageDescriptionInfoV1IccFileHandler
	primariesHandler       WpImageDescriptionInfoV1PrimariesHandler
	primariesNamedHandler  WpImageDescriptionInfoV1PrimariesNamedHandler
	tfPowerHandler         WpImageDescriptionInfoV1TfPowerHandler
	tfNamedHandler         WpImageDescriptionInfoV1TfNamedHandler
	luminancesHandler      WpImageDescriptionInfoV1LuminancesHandler
	targetPrimariesHandler WpImageDescriptionInfoV1TargetPrimariesHandler
	targetLuminanceHandler WpImageDescriptionInfoV1TargetLuminanceHandler
	targetMaxCllHandler    WpImageDescriptionInfoV1TargetMaxCllHandler
	targetMaxFallHandler   WpImageDescriptionInfoV1TargetMaxFallHandler
}

// NewWpImageDescriptionInfoV1 creates a new WpImageDescriptionInfoV1
func NewWpImageDescriptionInfoV1(ctx *client.Context) *WpImageDescriptionInfoV1 {
	o := &WpImageDescriptionInfoV1{}
	ctx.Register(o)
	return o
}

// WpImageDescriptionInfoV1DoneEvent: end of information
type WpImageDescriptionInfoV1DoneEvent struct {
}

type WpImageDescriptionInfoV1DoneHandler func(WpImageDescriptionInfoV1DoneEvent)

// WpImageDescriptionInfoV1IccFileEvent: ICC profile matching the image description
type WpImageDescriptionInfoV1IccFileEvent struct {
	Icc     uintptr
	IccSize uint32
}

type WpImageDescriptionInfoV1IccFileHandler func(WpImageDescriptionInfoV1IccFileEvent)

// WpImageDescriptionInfoV1PrimariesEvent: primaries as chromaticity coordinates
type WpImageDescriptionInfoV1PrimariesEvent struct {
	RX int32
	RY int32
	GX int32
	GY int32
	BX int32
	BY int32
	WX int32
	WY int32
}

type WpImageDescriptionInfoV1PrimariesHandler func(WpImageDescriptionInfoV1PrimariesEvent)

// WpImageDescriptionInfoV1PrimariesNamedEvent: named primaries
type WpImageDescriptionInfoV1PrimariesNamedEvent struct {
	Primaries uint32
}

type WpImageDescriptionInfoV1PrimariesNamedHandler func(WpImageDescriptionInfoV1PrimariesNamedEvent)

// WpImageDescriptionInfoV1TfPowerEvent: transfer characteristic as a power curve
type WpImageDescriptionInfoV1TfPowerEvent struct {
	Eexp uint32
}

type WpImageDescriptionInfoV1TfPowerHandler func(WpImageDescriptionInfoV1TfPowerEvent)

// WpImageDescriptionInfoV1TfNamedEvent: named transfer characteristic
type WpImageDescriptionInfoV1TfNamedEvent struct {
	Tf uint32
}

type WpImageDescriptionInfoV1TfNamedHandler func(WpImageDescriptionInfoV1TfNamedEvent)

// WpImageDescriptionInfoV1LuminancesEvent: primary color volume luminance range and reference white
type WpImageDescriptionInfoV1LuminancesEvent struct {
	MinLum       uint32
	MaxLum       uint32
	ReferenceLum uint32
}

type WpImageDescriptionInfoV1LuminancesHandler func(WpImageDescriptionInfoV1LuminancesEvent)

// WpImageDescriptionInfoV1TargetPrimariesEvent: target primaries as chromaticity coordinates
type WpImageDescriptionInfoV1TargetPrimariesEvent struct {
	RX int32
	RY int32
	GX int32
	GY int32
	BX int32
	BY int32
	WX int32
	WY int32
}

type WpImageDescriptionInfoV1TargetPrimariesHandler func(WpImageDescriptionInfoV1TargetPrimariesEvent)

// WpImageDescriptionInfoV1TargetLuminanceEvent: target luminance range
type WpImageDescriptionInfoV1TargetLuminanceEvent struct {
	MinLum uint32
	MaxLum uint32
}

type WpImageDescriptionInfoV1TargetLuminanceHandler func(WpImageDescriptionInfoV1TargetLuminanceEvent)

// WpImageDescriptionInfoV1TargetMaxCllEvent: target maximum content light level
type WpImageDescriptionInfoV1TargetMaxCllEvent struct {
	MaxCll uint32
}

type WpImageDescriptionInfoV1TargetMaxCllHandler func(WpImageDescriptionInfoV1TargetMaxCllEvent)

// WpImageDescriptionInfoV1TargetMaxFallEvent: target maximum frame-average light level
type WpImageDescriptionInfoV1TargetMaxFallEvent struct {
	MaxFall uint32
}

type WpImageDescriptionInfoV1TargetMaxFallHandler func(WpImageDescriptionInfoV1TargetMaxFallEvent)

// SetDoneHandler sets the handler for the done event
func (i *WpImageDescriptionInfoV1) SetDoneHandler(f WpImageDescriptionInfoV1DoneHandler) {
	i.doneHandler = f
}

// SetIccFileHandler sets the handler for the icc_file event
func (i *WpImageDescriptionInfoV1) SetIccFileHandler(f WpImageDescriptionInfoV1IccFileHandler) {
	i.iccFileHandler = f
}

// SetPrimariesHandler sets the handler for the primaries event
func (i *WpImageDescriptionInfoV1) SetPrimariesHandler(f WpImageDescriptionInfoV1PrimariesHandler) {
	i.primariesHandler = f
}

// SetPrimariesNamedHandler sets the handler for the primaries_named event
func (i *WpImageDescriptionInfoV1) SetPrimariesNamedHandler(f WpImageDescriptionInfoV1PrimariesNamedHandler) {
	i.primariesNamedHandler = f
}

// SetTfPowerHandler sets the handler for the tf_power event
func (i *WpImageDescriptionInfoV1) SetTfPowerHandler(f WpImageDescriptionInfoV1TfPowerHandler) {
	i.tfPowerHandler = f
}

// SetTfNamedHandler sets the handler for the tf_named event
func (i *WpImageDescriptionInfoV1) SetTfNamedHandler(f WpImageDescriptionInfoV1TfNamedHandler) {
	i.tfNamedHandler = f
}

// SetLuminancesHandler sets the handler for the luminances event
func (i *WpImageDescriptionInfoV1) SetLuminancesHandler(f WpImageDescriptionInfoV1LuminancesHandler) {
	i.luminancesHandler = f
}

// SetTargetPrimariesHandler sets the handler for the target_primaries event
func (i *WpImageDescriptionInfoV1) SetTargetPrimariesHandler(f WpImageDescriptionInfoV1TargetPrimariesHandler) {
	i.targetPrimariesHandler = f
}

// SetTargetLuminanceHandler sets the handler for the target_luminance event
func (i *WpImageDescriptionInfoV1) SetTargetLuminanceHandler(f WpImageDescriptionInfoV1TargetLuminanceHandler) {
	i.targetLuminanceHandler = f
}

// SetTargetMaxCllHandler sets the handler for the target_max_cll event
func (i *WpImageDescriptionInfoV1) SetTargetMaxCllHandler(f WpImageDescriptionInfoV1TargetMaxCllHandler) {
	i.targetMaxCllHandler = f
}

// SetTargetMaxFallHandler sets the handler for the target_max_fall event
func (i *WpImageDescriptionInfoV1) SetTargetMaxFallHandler(f WpImageDescriptionInfoV1TargetMaxFallHandler) {
	i.targetMaxFallHandler = f
}

// Dispatch handles incoming events
func (i *WpImageDescriptionInfoV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // done
		if i.doneHandler != nil {
			ev := WpImageDescriptionInfoV1DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 1: // icc_file
		if i.iccFileHandler != nil {
			ev := WpImageDescriptionInfoV1IccFileEvent{}
			l := 0
			ev.Icc = uintptr(fd)
			ev.IccSize = client.Uint32(data[l : l+4])
			l += 4
			i.iccFileHandler(ev)
		}
	case 2: // primaries
		if i.primariesHandler != nil {
			ev := WpImageDescriptionInfoV1PrimariesEvent{}
			l := 0
			_ = fd
			ev.RX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.RY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.GX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.GY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.BX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.BY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.WX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.WY = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.primariesHandler(ev)
		}
	case 3: // primaries_named
		if i.primariesNamedHandler != nil {
			ev := WpImageDescriptionInfoV1PrimariesNamedEvent{}
			l := 0
			_ = fd
			ev.Primaries = client.Uint32(data[l : l+4])
			l += 4
			i.primariesNamedHandler(ev)
		}
	case 4: // tf_power
		if i.tfPowerHandler != nil {
			ev := WpImageDescriptionInfoV1TfPowerEvent{}
			l := 0
			_ = fd
			ev.Eexp = client.Uint32(data[l : l+4])
			l += 4
			i.tfPowerHandler(ev)
		}
	case 5: // tf_named
		if i.tfNamedHandler != nil {
			ev := WpImageDescriptionInfoV1TfNamedEvent{}
			l := 0
			_ = fd
			ev.Tf = client.Uint32(data[l : l+4])
			l += 4
			i.tfNamedHandler(ev)
		}
	case 6: // luminances
		if i.luminancesHandler != nil {
			ev := WpImageDescriptionInfoV1LuminancesEvent{}
			l := 0
			_ = fd
			ev.MinLum = client.Uint32(data[l : l+4])
			l += 4
			ev.MaxLum = client.Uint32(data[l : l+4])
			l += 4
			ev.ReferenceLum = client.Uint32(data[l : l+4])
			l += 4
			i.luminancesHandler(ev)
		}
	case 7: // target_primaries
		if i.targetPrimariesHandler != nil {
			ev := WpImageDescriptionInfoV1TargetPrimariesEvent{}
			l := 0
			_ = fd
			ev.RX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.RY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.GX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.GY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.BX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.BY = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.WX = int32(client.Uint32(data[l : l+4]))
			l += 4
			ev.WY = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.targetPrimariesHandler(ev)
		}
	case 8: // target_luminance
		if i.targetLuminanceHandler != nil {
			ev := WpImageDescriptionInfoV1TargetLuminanceEvent{}
			l := 0
			_ = fd
			ev.MinLum = client.Uint32(data[l : l+4])
			l += 4
			ev.MaxLum = client.Uint32(data[l : l+4])
			l += 4
			i.targetLuminanceHandler(ev)
		}
	case 9: // target_max_cll
		if i.targetMaxCllHandler != nil {
			ev := WpImageDescriptionInfoV1TargetMaxCllEvent{}
			l := 0
			_ = fd
			ev.MaxCll = client.Uint32(data[l : l+4])
			l += 4
			i.targetMaxCllHandler(ev)
		}
	case 10: // target_max_fall
		if i.targetMaxFallHandler != nil {
			ev := WpImageDescriptionInfoV1TargetMaxFallEvent{}
			l := 0
			_ = fd
			ev.MaxFall = client.Uint32(data[l : l+4])
			l += 4
			i.targetMaxFallHandler(ev)
		}
	}
}

// WpImageDescriptionReferenceV1: Reference to an image description
type WpImageDescriptionReferenceV1 struct {
	client.BaseProxy
}

// NewWpImageDescriptionReferenceV1 creates a new WpImageDescriptionReferenceV1
func NewWpImageDescriptionReferenceV1(ctx *client.Context) *WpImageDescriptionReferenceV1 {
	o := &WpImageDescriptionReferenceV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the reference
func (i *WpImageDescriptionReferenceV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}
