// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/unstable/relative-pointer/relative-pointer-unstable-v1.xml
//
// relative_pointer_unstable_v1 Protocol Copyright:
// Copyright © 2014      Jonas Ådahl
// Copyright © 2015      Red Hat Inc.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package relative_pointer_unstable_v1

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZwpRelativePointerManagerV1: get relative pointer objects
type ZwpRelativePointerManagerV1 struct {
	client.BaseProxy
}

// NewZwpRelativePointerManagerV1 creates a new ZwpRelativePointerManagerV1
func NewZwpRelativePointerManagerV1(ctx *client.Context) *ZwpRelativePointerManagerV1 {
	o := &ZwpRelativePointerManagerV1{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the relative pointer manager object
func (i *ZwpRelativePointerManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetRelativePointer: get a relative pointer object
func (i *ZwpRelativePointerManagerV1) GetRelativePointer(pointer *client.WlPointer) (*ZwpRelativePointerV1, error) {
	id := NewZwpRelativePointerV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ZwpRelativePointerV1: relative pointer object
type ZwpRelativePointerV1 struct {
	client.BaseProxy
	relativeMotionHandler ZwpRelativePointerV1RelativeMotionHandler
}

// NewZwpRelativePointerV1 creates a new ZwpRelativePointerV1
func NewZwpRelativePointerV1(ctx *client.Context) *ZwpRelativePointerV1 {
	o := &ZwpRelativePointerV1{}
	ctx.Register(o)
	return o
}

// Destroy: release the relative pointer object
func (i *ZwpRelativePointerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpRelativePointerV1RelativeMotionEvent: relative pointer motion
type ZwpRelativePointerV1RelativeMotionEvent struct {
	UtimeHi   uint32
	UtimeLo   uint32
	Dx        float64
	Dy        float64
	DxUnaccel float64
	DyUnaccel float64
}

type ZwpRelativePointerV1RelativeMotionHandler func(ZwpRelativePointerV1RelativeMotionEvent)

// SetRelativeMotionHandler sets the handler for the relative_motion event
func (i *ZwpRelativePointerV1) SetRelativeMotionHandler(f ZwpRelativePointerV1RelativeMotionHandler) {
	i.relativeMotionHandler = f
}

// Dispatch handles incoming events
func (i *ZwpRelativePointerV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // relative_motion
		if i.relativeMotionHandler != nil {
			ev := ZwpRelativePointerV1RelativeMotionEvent{}
			l := 0
			_ = fd
			ev.UtimeHi = client.Uint32(data[l : l+4])
			l += 4
			ev.UtimeLo = client.Uint32(data[l : l+4])
			l += 4
			ev.Dx = client.Fixed(data[l : l+4])
			l += 4
			ev.Dy = client.Fixed(data[l : l+4])
			l += 4
			ev.DxUnaccel = client.Fixed(data[l : l+4])
			l += 4
			ev.DyUnaccel = client.Fixed(data[l : l+4])
			l += 4
			i.relativeMotionHandler(ev)
		}
	}
}
