// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/stable/tablet/tablet-v2.xml
//
// tablet_v2 Protocol Copyright:
// Copyright 2014 © Stephen "Lyude" Chandler Paul
// Copyright 2015-2024 © Red Hat, Inc.
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation files
// (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
// The above copyright notice and this permission notice (including the
// next paragraph) shall be included in all copies or substantial
// portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
// BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package tablet_v2

import (
	"github.com/tri2820/cheese/protocols/client"
)

// ZwpTabletManagerV2: controller object for graphic tablet devices
type ZwpTabletManagerV2 struct {
	client.BaseProxy
}

// NewZwpTabletManagerV2 creates a new ZwpTabletManagerV2
func NewZwpTabletManagerV2(ctx *client.Context) *ZwpTabletManagerV2 {
	o := &ZwpTabletManagerV2{}
	ctx.Register(o)
	return o
}

// GetTabletSeat: get the tablet seat
func (i *ZwpTabletManagerV2) GetTabletSeat(seat *client.WlSeat) (*ZwpTabletSeatV2, error) {
	tablet_seat := NewZwpTabletSeatV2(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], tablet_seat.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], seat.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return tablet_seat, err
}

// Destroy: release the memory for the tablet manager object
func (i *ZwpTabletManagerV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletSeatV2: controller object for graphic tablet devices of a seat
type ZwpTabletSeatV2 struct {
	client.BaseProxy
	tabletAddedHandler ZwpTabletSeatV2TabletAddedHandler
	toolAddedHandler   ZwpTabletSeatV2ToolAddedHandler
	padAddedHandler    ZwpTabletSeatV2PadAddedHandler
}

// NewZwpTabletSeatV2 creates a new ZwpTabletSeatV2
func NewZwpTabletSeatV2(ctx *client.Context) *ZwpTabletSeatV2 {
	o := &ZwpTabletSeatV2{}
	ctx.Register(o)
	return o
}

// Destroy: release the memory for the tablet seat object
func (i *ZwpTabletSeatV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletSeatV2TabletAddedEvent: new device notification
type ZwpTabletSeatV2TabletAddedEvent struct {
	Id *ZwpTabletV2
}

type ZwpTabletSeatV2TabletAddedHandler func(ZwpTabletSeatV2TabletAddedEvent)

// ZwpTabletSeatV2ToolAddedEvent: a new tool has been used with a tablet
type ZwpTabletSeatV2ToolAddedEvent struct {
	Id *ZwpTabletToolV2
}

type ZwpTabletSeatV2ToolAddedHandler func(ZwpTabletSeatV2ToolAddedEvent)

// ZwpTabletSeatV2PadAddedEvent: new pad notification
type ZwpTabletSeatV2PadAddedEvent struct {
	Id *ZwpTabletPadV2
}

type ZwpTabletSeatV2PadAddedHandler func(ZwpTabletSeatV2PadAddedEvent)

// SetTabletAddedHandler sets the handler for the tablet_added event
func (i *ZwpTabletSeatV2) SetTabletAddedHandler(f ZwpTabletSeatV2TabletAddedHandler) {
	i.tabletAddedHandler = f
}

// SetToolAddedHandler sets the handler for the tool_added event
func (i *ZwpTabletSeatV2) SetToolAddedHandler(f ZwpTabletSeatV2ToolAddedHandler) {
	i.toolAddedHandler = f
}

// SetPadAddedHandler sets the handler for the pad_added event
func (i *ZwpTabletSeatV2) SetPadAddedHandler(f ZwpTabletSeatV2PadAddedHandler) {
	i.padAddedHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletSeatV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // tablet_added
		if i.tabletAddedHandler != nil {
			ev := ZwpTabletSeatV2TabletAddedEvent{}
			l := 0
			_ = fd
			idID := client.Uint32(data[l : l+4])
			l += 4
			ev.Id = i.Context().GetProxy(idID).(*ZwpTabletV2)
			i.tabletAddedHandler(ev)
		}
	case 1: // tool_added
		if i.toolAddedHandler != nil {
			ev := ZwpTabletSeatV2ToolAddedEvent{}
			l := 0
			_ = fd
			idID := client.Uint32(data[l : l+4])
			l += 4
			ev.Id = i.Context().GetProxy(idID).(*ZwpTabletToolV2)
			i.toolAddedHandler(ev)
		}
	case 2: // pad_added
		if i.padAddedHandler != nil {
			ev := ZwpTabletSeatV2PadAddedEvent{}
			l := 0
			_ = fd
			idID := client.Uint32(data[l : l+4])
			l += 4
			ev.Id = i.Context().GetProxy(idID).(*ZwpTabletPadV2)
			i.padAddedHandler(ev)
		}
	}
}

// ZwpTabletToolV2: a physical tablet tool
type ZwpTabletToolV2 struct {
	client.BaseProxy
	typeHandler            ZwpTabletToolV2TypeHandler
	hardwareSerialHandler  ZwpTabletToolV2HardwareSerialHandler
	hardwareIdWacomHandler ZwpTabletToolV2HardwareIdWacomHandler
	capabilityHandler      ZwpTabletToolV2CapabilityHandler
	doneHandler            ZwpTabletToolV2DoneHandler
	removedHandler         ZwpTabletToolV2RemovedHandler
	proximityInHandler     ZwpTabletToolV2ProximityInHandler
	proximityOutHandler    ZwpTabletToolV2ProximityOutHandler
	downHandler            ZwpTabletToolV2DownHandler
	upHandler              ZwpTabletToolV2UpHandler
	motionHandler          ZwpTabletToolV2MotionHandler
	pressureHandler        ZwpTabletToolV2PressureHandler
	distanceHandler        ZwpTabletToolV2DistanceHandler
	tiltHandler            ZwpTabletToolV2TiltHandler
	rotationHandler        ZwpTabletToolV2RotationHandler
	sliderHandler          ZwpTabletToolV2SliderHandler
	wheelHandler           ZwpTabletToolV2WheelHandler
	buttonHandler          ZwpTabletToolV2ButtonHandler
	frameHandler           ZwpTabletToolV2FrameHandler
}

// NewZwpTabletToolV2 creates a new ZwpTabletToolV2
func NewZwpTabletToolV2(ctx *client.Context) *ZwpTabletToolV2 {
	o := &ZwpTabletToolV2{}
	ctx.Register(o)
	return o
}

// ZwpTabletToolV2Type: a physical tool type
type ZwpTabletToolV2Type uint32

const (
	ZwpTabletToolV2TypePen      ZwpTabletToolV2Type = 0x140
	ZwpTabletToolV2TypeEraser   ZwpTabletToolV2Type = 0x141
	ZwpTabletToolV2TypeBrush    ZwpTabletToolV2Type = 0x142
	ZwpTabletToolV2TypePencil   ZwpTabletToolV2Type = 0x143
	ZwpTabletToolV2TypeAirbrush ZwpTabletToolV2Type = 0x144
	ZwpTabletToolV2TypeFinger   ZwpTabletToolV2Type = 0x145
	ZwpTabletToolV2TypeMouse    ZwpTabletToolV2Type = 0x146
	ZwpTabletToolV2TypeLens     ZwpTabletToolV2Type = 0x147
)

// ZwpTabletToolV2Capability: capability flags for a tool
type ZwpTabletToolV2Capability uint32

const (
	ZwpTabletToolV2CapabilityTilt     ZwpTabletToolV2Capability = 1
	ZwpTabletToolV2CapabilityPressure ZwpTabletToolV2Capability = 2
	ZwpTabletToolV2CapabilityDistance ZwpTabletToolV2Capability = 3
	ZwpTabletToolV2CapabilityRotation ZwpTabletToolV2Capability = 4
	ZwpTabletToolV2CapabilitySlider   ZwpTabletToolV2Capability = 5
	ZwpTabletToolV2CapabilityWheel    ZwpTabletToolV2Capability = 6
)

// ZwpTabletToolV2ButtonState: physical button state
type ZwpTabletToolV2ButtonState uint32

const (
	ZwpTabletToolV2ButtonStateReleased ZwpTabletToolV2ButtonState = 0
	ZwpTabletToolV2ButtonStatePressed  ZwpTabletToolV2ButtonState = 1
)

type ZwpTabletToolV2Error uint32

const (
	ZwpTabletToolV2ErrorRole ZwpTabletToolV2Error = 0
)

// SetCursor: set the tablet tool's surface
func (i *ZwpTabletToolV2) SetCursor(serial uint32, surface *client.WlSurface, hotspot_x int32, hotspot_y int32) error {
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	if surface == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], surface.ID())
		l += 4
	}
	client.PutUint32(_reqBuf[l:l+4], uint32(hotspot_x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(hotspot_y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy: destroy the tool object
func (i *ZwpTabletToolV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletToolV2TypeEvent: tool type
type ZwpTabletToolV2TypeEvent struct {
	ToolType ZwpTabletToolV2Type
}

type ZwpTabletToolV2TypeHandler func(ZwpTabletToolV2TypeEvent)

// ZwpTabletToolV2HardwareSerialEvent: unique hardware serial number of the tool
type ZwpTabletToolV2HardwareSerialEvent struct {
	HardwareSerialHi uint32
	HardwareSerialLo uint32
}

type ZwpTabletToolV2HardwareSerialHandler func(ZwpTabletToolV2HardwareSerialEvent)

// ZwpTabletToolV2HardwareIdWacomEvent: hardware id notification in Wacom's format
type ZwpTabletToolV2HardwareIdWacomEvent struct {
	HardwareIdHi uint32
	HardwareIdLo uint32
}

type ZwpTabletToolV2HardwareIdWacomHandler func(ZwpTabletToolV2HardwareIdWacomEvent)

// ZwpTabletToolV2CapabilityEvent: tool capability notification
type ZwpTabletToolV2CapabilityEvent struct {
	Capability ZwpTabletToolV2Capability
}

type ZwpTabletToolV2CapabilityHandler func(ZwpTabletToolV2CapabilityEvent)

// ZwpTabletToolV2DoneEvent: tool description events sequence complete
type ZwpTabletToolV2DoneEvent struct {
}

type ZwpTabletToolV2DoneHandler func(ZwpTabletToolV2DoneEvent)

// ZwpTabletToolV2RemovedEvent: tool removed
type ZwpTabletToolV2RemovedEvent struct {
}

type ZwpTabletToolV2RemovedHandler func(ZwpTabletToolV2RemovedEvent)

// ZwpTabletToolV2ProximityInEvent: proximity in event
type ZwpTabletToolV2ProximityInEvent struct {
	Serial  uint32
	Tablet  *ZwpTabletV2
	Surface *client.WlSurface
}

type ZwpTabletToolV2ProximityInHandler func(ZwpTabletToolV2ProximityInEvent)

// ZwpTabletToolV2ProximityOutEvent: proximity out event
type ZwpTabletToolV2ProximityOutEvent struct {
}

type ZwpTabletToolV2ProximityOutHandler func(ZwpTabletToolV2ProximityOutEvent)

// ZwpTabletToolV2DownEvent: tablet tool is making contact
type ZwpTabletToolV2DownEvent struct {
	Serial uint32
}

type ZwpTabletToolV2DownHandler func(ZwpTabletToolV2DownEvent)

// ZwpTabletToolV2UpEvent: tablet tool is no longer making contact
type ZwpTabletToolV2UpEvent struct {
}

type ZwpTabletToolV2UpHandler func(ZwpTabletToolV2UpEvent)

// ZwpTabletToolV2MotionEvent: motion event
type ZwpTabletToolV2MotionEvent struct {
	X float64
	Y float64
}

type ZwpTabletToolV2MotionHandler func(ZwpTabletToolV2MotionEvent)

// ZwpTabletToolV2PressureEvent: pressure change event
type ZwpTabletToolV2PressureEvent struct {
	Pressure uint32
}

type ZwpTabletToolV2PressureHandler func(ZwpTabletToolV2PressureEvent)

// ZwpTabletToolV2DistanceEvent: distance change event
type ZwpTabletToolV2DistanceEvent struct {
	Distance uint32
}

type ZwpTabletToolV2DistanceHandler func(ZwpTabletToolV2DistanceEvent)

// ZwpTabletToolV2TiltEvent: tilt change event
type ZwpTabletToolV2TiltEvent struct {
	TiltX float64
	TiltY float64
}

type ZwpTabletToolV2TiltHandler func(ZwpTabletToolV2TiltEvent)

// ZwpTabletToolV2RotationEvent: z-rotation change event
type ZwpTabletToolV2RotationEvent struct {
	Degrees float64
}

type ZwpTabletToolV2RotationHandler func(ZwpTabletToolV2RotationEvent)

// ZwpTabletToolV2SliderEvent: Slider position change event
type ZwpTabletToolV2SliderEvent struct {
	Position int32
}

type ZwpTabletToolV2SliderHandler func(ZwpTabletToolV2SliderEvent)

// ZwpTabletToolV2WheelEvent: Wheel delta event
type ZwpTabletToolV2WheelEvent struct {
	Degrees float64
	Clicks  int32
}

type ZwpTabletToolV2WheelHandler func(ZwpTabletToolV2WheelEvent)

// ZwpTabletToolV2ButtonEvent: button event
type ZwpTabletToolV2ButtonEvent struct {
	Serial uint32
	Button uint32
	State  ZwpTabletToolV2ButtonState
}

type ZwpTabletToolV2ButtonHandler func(ZwpTabletToolV2ButtonEvent)

// ZwpTabletToolV2FrameEvent: frame event
type ZwpTabletToolV2FrameEvent struct {
	Time uint32
}

type ZwpTabletToolV2FrameHandler func(ZwpTabletToolV2FrameEvent)

// SetTypeHandler sets the handler for the type event
func (i *ZwpTabletToolV2) SetTypeHandler(f ZwpTabletToolV2TypeHandler) {
	i.typeHandler = f
}

// SetHardwareSerialHandler sets the handler for the hardware_serial event
func (i *ZwpTabletToolV2) SetHardwareSerialHandler(f ZwpTabletToolV2HardwareSerialHandler) {
	i.hardwareSerialHandler = f
}

// SetHardwareIdWacomHandler sets the handler for the hardware_id_wacom event
func (i *ZwpTabletToolV2) SetHardwareIdWacomHandler(f ZwpTabletToolV2HardwareIdWacomHandler) {
	i.hardwareIdWacomHandler = f
}

// SetCapabilityHandler sets the handler for the capability event
func (i *ZwpTabletToolV2) SetCapabilityHandler(f ZwpTabletToolV2CapabilityHandler) {
	i.capabilityHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ZwpTabletToolV2) SetDoneHandler(f ZwpTabletToolV2DoneHandler) {
	i.doneHandler = f
}

// SetRemovedHandler sets the handler for the removed event
func (i *ZwpTabletToolV2) SetRemovedHandler(f ZwpTabletToolV2RemovedHandler) {
	i.removedHandler = f
}

// SetProximityInHandler sets the handler for the proximity_in event
func (i *ZwpTabletToolV2) SetProximityInHandler(f ZwpTabletToolV2ProximityInHandler) {
	i.proximityInHandler = f
}

// SetProximityOutHandler sets the handler for the proximity_out event
func (i *ZwpTabletToolV2) SetProximityOutHandler(f ZwpTabletToolV2ProximityOutHandler) {
	i.proximityOutHandler = f
}

// SetDownHandler sets the handler for the down event
func (i *ZwpTabletToolV2) SetDownHandler(f ZwpTabletToolV2DownHandler) {
	i.downHandler = f
}

// SetUpHandler sets the handler for the up event
func (i *ZwpTabletToolV2) SetUpHandler(f ZwpTabletToolV2UpHandler) {
	i.upHandler = f
}

// SetMotionHandler sets the handler for the motion event
func (i *ZwpTabletToolV2) SetMotionHandler(f ZwpTabletToolV2MotionHandler) {
	i.motionHandler = f
}

// SetPressureHandler sets the handler for the pressure event
func (i *ZwpTabletToolV2) SetPressureHandler(f ZwpTabletToolV2PressureHandler) {
	i.pressureHandler = f
}

// SetDistanceHandler sets the handler for the distance event
func (i *ZwpTabletToolV2) SetDistanceHandler(f ZwpTabletToolV2DistanceHandler) {
	i.distanceHandler = f
}

// SetTiltHandler sets the handler for the tilt event
func (i *ZwpTabletToolV2) SetTiltHandler(f ZwpTabletToolV2TiltHandler) {
	i.tiltHandler = f
}

// SetRotationHandler sets the handler for the rotation event
func (i *ZwpTabletToolV2) SetRotationHandler(f ZwpTabletToolV2RotationHandler) {
	i.rotationHandler = f
}

// SetSliderHandler sets the handler for the slider event
func (i *ZwpTabletToolV2) SetSliderHandler(f ZwpTabletToolV2SliderHandler) {
	i.sliderHandler = f
}

// SetWheelHandler sets the handler for the wheel event
func (i *ZwpTabletToolV2) SetWheelHandler(f ZwpTabletToolV2WheelHandler) {
	i.wheelHandler = f
}

// SetButtonHandler sets the handler for the button event
func (i *ZwpTabletToolV2) SetButtonHandler(f ZwpTabletToolV2ButtonHandler) {
	i.buttonHandler = f
}

// SetFrameHandler sets the handler for the frame event
func (i *ZwpTabletToolV2) SetFrameHandler(f ZwpTabletToolV2FrameHandler) {
	i.frameHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletToolV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // type
		if i.typeHandler != nil {
			ev := ZwpTabletToolV2TypeEvent{}
			l := 0
			_ = fd
			ev.ToolType = ZwpTabletToolV2Type(client.Uint32(data[l : l+4]))
			l += 4
			i.typeHandler(ev)
		}
	case 1: // hardware_serial
		if i.hardwareSerialHandler != nil {
			ev := ZwpTabletToolV2HardwareSerialEvent{}
			l := 0
			_ = fd
			ev.HardwareSerialHi = client.Uint32(data[l : l+4])
			l += 4
			ev.HardwareSerialLo = client.Uint32(data[l : l+4])
			l += 4
			i.hardwareSerialHandler(ev)
		}
	case 2: // hardware_id_wacom
		if i.hardwareIdWacomHandler != nil {
			ev := ZwpTabletToolV2HardwareIdWacomEvent{}
			l := 0
			_ = fd
			ev.HardwareIdHi = client.Uint32(data[l : l+4])
			l += 4
			ev.HardwareIdLo = client.Uint32(data[l : l+4])
			l += 4
			i.hardwareIdWacomHandler(ev)
		}
	case 3: // capability
		if i.capabilityHandler != nil {
			ev := ZwpTabletToolV2CapabilityEvent{}
			l := 0
			_ = fd
			ev.Capability = ZwpTabletToolV2Capability(client.Uint32(data[l : l+4]))
			l += 4
			i.capabilityHandler(ev)
		}
	case 4: // done
		if i.doneHandler != nil {
			ev := ZwpTabletToolV2DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 5: // removed
		if i.removedHandler != nil {
			ev := ZwpTabletToolV2RemovedEvent{}
			_ = fd
			_ = data
			i.removedHandler(ev)
		}
	case 6: // proximity_in
		if i.proximityInHandler != nil {
			ev := ZwpTabletToolV2ProximityInEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			tabletID := client.Uint32(data[l : l+4])
			l += 4
			ev.Tablet = i.Context().GetProxy(tabletID).(*ZwpTabletV2)
			surfaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Surface = i.Context().GetProxy(surfaceID).(*client.WlSurface)
			i.proximityInHandler(ev)
		}
	case 7: // proximity_out
		if i.proximityOutHandler != nil {
			ev := ZwpTabletToolV2ProximityOutEvent{}
			_ = fd
			_ = data
			i.proximityOutHandler(ev)
		}
	case 8: // down
		if i.downHandler != nil {
			ev := ZwpTabletToolV2DownEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			i.downHandler(ev)
		}
	case 9: // up
		if i.upHandler != nil {
			ev := ZwpTabletToolV2UpEvent{}
			_ = fd
			_ = data
			i.upHandler(ev)
		}
	case 10: // motion
		if i.motionHandler != nil {
			ev := ZwpTabletToolV2MotionEvent{}
			l := 0
			_ = fd
			ev.X = client.Fixed(data[l : l+4])
			l += 4
			ev.Y = client.Fixed(data[l : l+4])
			l += 4
			i.motionHandler(ev)
		}
	case 11: // pressure
		if i.pressureHandler != nil {
			ev := ZwpTabletToolV2PressureEvent{}
			l := 0
			_ = fd
			ev.Pressure = client.Uint32(data[l : l+4])
			l += 4
			i.pressureHandler(ev)
		}
	case 12: // distance
		if i.distanceHandler != nil {
			ev := ZwpTabletToolV2DistanceEvent{}
			l := 0
			_ = fd
			ev.Distance = client.Uint32(data[l : l+4])
			l += 4
			i.distanceHandler(ev)
		}
	case 13: // tilt
		if i.tiltHandler != nil {
			ev := ZwpTabletToolV2TiltEvent{}
			l := 0
			_ = fd
			ev.TiltX = client.Fixed(data[l : l+4])
			l += 4
			ev.TiltY = client.Fixed(data[l : l+4])
			l += 4
			i.tiltHandler(ev)
		}
	case 14: // rotation
		if i.rotationHandler != nil {
			ev := ZwpTabletToolV2RotationEvent{}
			l := 0
			_ = fd
			ev.Degrees = client.Fixed(data[l : l+4])
			l += 4
			i.rotationHandler(ev)
		}
	case 15: // slider
		if i.sliderHandler != nil {
			ev := ZwpTabletToolV2SliderEvent{}
			l := 0
			_ = fd
			ev.Position = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.sliderHandler(ev)
		}
	case 16: // wheel
		if i.wheelHandler != nil {
			ev := ZwpTabletToolV2WheelEvent{}
			l := 0
			_ = fd
			ev.Degrees = client.Fixed(data[l : l+4])
			l += 4
			ev.Clicks = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.wheelHandler(ev)
		}
	case 17: // button
		if i.buttonHandler != nil {
			ev := ZwpTabletToolV2ButtonEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			ev.Button = client.Uint32(data[l : l+4])
			l += 4
			ev.State = ZwpTabletToolV2ButtonState(client.Uint32(data[l : l+4]))
			l += 4
			i.buttonHandler(ev)
		}
	case 18: // frame
		if i.frameHandler != nil {
			ev := ZwpTabletToolV2FrameEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			i.frameHandler(ev)
		}
	}
}

// ZwpTabletV2: graphics tablet device
type ZwpTabletV2 struct {
	client.BaseProxy
	nameHandler    ZwpTabletV2NameHandler
	idHandler      ZwpTabletV2IdHandler
	pathHandler    ZwpTabletV2PathHandler
	doneHandler    ZwpTabletV2DoneHandler
	removedHandler ZwpTabletV2RemovedHandler
	bustypeHandler ZwpTabletV2BustypeHandler
}

// NewZwpTabletV2 creates a new ZwpTabletV2
func NewZwpTabletV2(ctx *client.Context) *ZwpTabletV2 {
	o := &ZwpTabletV2{}
	ctx.Register(o)
	return o
}

// ZwpTabletV2Bustype: bus type
type ZwpTabletV2Bustype uint32

const (
	ZwpTabletV2BustypeUsb       ZwpTabletV2Bustype = 3
	ZwpTabletV2BustypeBluetooth ZwpTabletV2Bustype = 5
	ZwpTabletV2BustypeVirtual   ZwpTabletV2Bustype = 6
	ZwpTabletV2BustypeSerial    ZwpTabletV2Bustype = 17
	ZwpTabletV2BustypeI2C       ZwpTabletV2Bustype = 24
)

// Destroy: destroy the tablet object
func (i *ZwpTabletV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletV2NameEvent: tablet device name
type ZwpTabletV2NameEvent struct {
	Name string
}

type ZwpTabletV2NameHandler func(ZwpTabletV2NameEvent)

// ZwpTabletV2IdEvent: tablet device vendor/product id
type ZwpTabletV2IdEvent struct {
	Vid uint32
	Pid uint32
}

type ZwpTabletV2IdHandler func(ZwpTabletV2IdEvent)

// ZwpTabletV2PathEvent: path to the device
type ZwpTabletV2PathEvent struct {
	Path string
}

type ZwpTabletV2PathHandler func(ZwpTabletV2PathEvent)

// ZwpTabletV2DoneEvent: tablet description events sequence complete
type ZwpTabletV2DoneEvent struct {
}

type ZwpTabletV2DoneHandler func(ZwpTabletV2DoneEvent)

// ZwpTabletV2RemovedEvent: tablet removed event
type ZwpTabletV2RemovedEvent struct {
}

type ZwpTabletV2RemovedHandler func(ZwpTabletV2RemovedEvent)

// ZwpTabletV2BustypeEvent: tablet device bus type
type ZwpTabletV2BustypeEvent struct {
	Bustype ZwpTabletV2Bustype
}

type ZwpTabletV2BustypeHandler func(ZwpTabletV2BustypeEvent)

// SetNameHandler sets the handler for the name event
func (i *ZwpTabletV2) SetNameHandler(f ZwpTabletV2NameHandler) {
	i.nameHandler = f
}

// SetIdHandler sets the handler for the id event
func (i *ZwpTabletV2) SetIdHandler(f ZwpTabletV2IdHandler) {
	i.idHandler = f
}

// SetPathHandler sets the handler for the path event
func (i *ZwpTabletV2) SetPathHandler(f ZwpTabletV2PathHandler) {
	i.pathHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ZwpTabletV2) SetDoneHandler(f ZwpTabletV2DoneHandler) {
	i.doneHandler = f
}

// SetRemovedHandler sets the handler for the removed event
func (i *ZwpTabletV2) SetRemovedHandler(f ZwpTabletV2RemovedHandler) {
	i.removedHandler = f
}

// SetBustypeHandler sets the handler for the bustype event
func (i *ZwpTabletV2) SetBustypeHandler(f ZwpTabletV2BustypeHandler) {
	i.bustypeHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // name
		if i.nameHandler != nil {
			ev := ZwpTabletV2NameEvent{}
			l := 0
			_ = fd
			nameRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			nameLen := client.PaddedLen(nameRawLen)
			ev.Name = client.String(data[l : l+nameLen])
			l += nameLen
			i.nameHandler(ev)
		}
	case 1: // id
		if i.idHandler != nil {
			ev := ZwpTabletV2IdEvent{}
			l := 0
			_ = fd
			ev.Vid = client.Uint32(data[l : l+4])
			l += 4
			ev.Pid = client.Uint32(data[l : l+4])
			l += 4
			i.idHandler(ev)
		}
	case 2: // path
		if i.pathHandler != nil {
			ev := ZwpTabletV2PathEvent{}
			l := 0
			_ = fd
			pathRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			pathLen := client.PaddedLen(pathRawLen)
			ev.Path = client.String(data[l : l+pathLen])
			l += pathLen
			i.pathHandler(ev)
		}
	case 3: // done
		if i.doneHandler != nil {
			ev := ZwpTabletV2DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 4: // removed
		if i.removedHandler != nil {
			ev := ZwpTabletV2RemovedEvent{}
			_ = fd
			_ = data
			i.removedHandler(ev)
		}
	case 5: // bustype
		if i.bustypeHandler != nil {
			ev := ZwpTabletV2BustypeEvent{}
			l := 0
			_ = fd
			ev.Bustype = ZwpTabletV2Bustype(client.Uint32(data[l : l+4]))
			l += 4
			i.bustypeHandler(ev)
		}
	}
}

// ZwpTabletPadRingV2: pad ring
type ZwpTabletPadRingV2 struct {
	client.BaseProxy
	sourceHandler ZwpTabletPadRingV2SourceHandler
	angleHandler  ZwpTabletPadRingV2AngleHandler
	stopHandler   ZwpTabletPadRingV2StopHandler
	frameHandler  ZwpTabletPadRingV2FrameHandler
}

// NewZwpTabletPadRingV2 creates a new ZwpTabletPadRingV2
func NewZwpTabletPadRingV2(ctx *client.Context) *ZwpTabletPadRingV2 {
	o := &ZwpTabletPadRingV2{}
	ctx.Register(o)
	return o
}

// ZwpTabletPadRingV2Source: ring axis source
type ZwpTabletPadRingV2Source uint32

const (
	ZwpTabletPadRingV2SourceFinger ZwpTabletPadRingV2Source = 1
)

// SetFeedback: set compositor feedback
func (i *ZwpTabletPadRingV2) SetFeedback(description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description, descriptionLen)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the ring object
func (i *ZwpTabletPadRingV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadRingV2SourceEvent: ring event source
type ZwpTabletPadRingV2SourceEvent struct {
	Source ZwpTabletPadRingV2Source
}

type ZwpTabletPadRingV2SourceHandler func(ZwpTabletPadRingV2SourceEvent)

// ZwpTabletPadRingV2AngleEvent: angle changed
type ZwpTabletPadRingV2AngleEvent struct {
	Degrees float64
}

type ZwpTabletPadRingV2AngleHandler func(ZwpTabletPadRingV2AngleEvent)

// ZwpTabletPadRingV2StopEvent: interaction stopped
type ZwpTabletPadRingV2StopEvent struct {
}

type ZwpTabletPadRingV2StopHandler func(ZwpTabletPadRingV2StopEvent)

// ZwpTabletPadRingV2FrameEvent: end of a ring event sequence
type ZwpTabletPadRingV2FrameEvent struct {
	Time uint32
}

type ZwpTabletPadRingV2FrameHandler func(ZwpTabletPadRingV2FrameEvent)

// SetSourceHandler sets the handler for the source event
func (i *ZwpTabletPadRingV2) SetSourceHandler(f ZwpTabletPadRingV2SourceHandler) {
	i.sourceHandler = f
}

// SetAngleHandler sets the handler for the angle event
func (i *ZwpTabletPadRingV2) SetAngleHandler(f ZwpTabletPadRingV2AngleHandler) {
	i.angleHandler = f
}

// SetStopHandler sets the handler for the stop event
func (i *ZwpTabletPadRingV2) SetStopHandler(f ZwpTabletPadRingV2StopHandler) {
	i.stopHandler = f
}

// SetFrameHandler sets the handler for the frame event
func (i *ZwpTabletPadRingV2) SetFrameHandler(f ZwpTabletPadRingV2FrameHandler) {
	i.frameHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletPadRingV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // source
		if i.sourceHandler != nil {
			ev := ZwpTabletPadRingV2SourceEvent{}
			l := 0
			_ = fd
			ev.Source = ZwpTabletPadRingV2Source(client.Uint32(data[l : l+4]))
			l += 4
			i.sourceHandler(ev)
		}
	case 1: // angle
		if i.angleHandler != nil {
			ev := ZwpTabletPadRingV2AngleEvent{}
			l := 0
			_ = fd
			ev.Degrees = client.Fixed(data[l : l+4])
			l += 4
			i.angleHandler(ev)
		}
	case 2: // stop
		if i.stopHandler != nil {
			ev := ZwpTabletPadRingV2StopEvent{}
			_ = fd
			_ = data
			i.stopHandler(ev)
		}
	case 3: // frame
		if i.frameHandler != nil {
			ev := ZwpTabletPadRingV2FrameEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			i.frameHandler(ev)
		}
	}
}

// ZwpTabletPadStripV2: pad strip
type ZwpTabletPadStripV2 struct {
	client.BaseProxy
	sourceHandler   ZwpTabletPadStripV2SourceHandler
	positionHandler ZwpTabletPadStripV2PositionHandler
	stopHandler     ZwpTabletPadStripV2StopHandler
	frameHandler    ZwpTabletPadStripV2FrameHandler
}

// NewZwpTabletPadStripV2 creates a new ZwpTabletPadStripV2
func NewZwpTabletPadStripV2(ctx *client.Context) *ZwpTabletPadStripV2 {
	o := &ZwpTabletPadStripV2{}
	ctx.Register(o)
	return o
}

// ZwpTabletPadStripV2Source: strip axis source
type ZwpTabletPadStripV2Source uint32

const (
	ZwpTabletPadStripV2SourceFinger ZwpTabletPadStripV2Source = 1
)

// SetFeedback: set compositor feedback
func (i *ZwpTabletPadStripV2) SetFeedback(description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description, descriptionLen)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the strip object
func (i *ZwpTabletPadStripV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadStripV2SourceEvent: strip event source
type ZwpTabletPadStripV2SourceEvent struct {
	Source ZwpTabletPadStripV2Source
}

type ZwpTabletPadStripV2SourceHandler func(ZwpTabletPadStripV2SourceEvent)

// ZwpTabletPadStripV2PositionEvent: position changed
type ZwpTabletPadStripV2PositionEvent struct {
	Position uint32
}

type ZwpTabletPadStripV2PositionHandler func(ZwpTabletPadStripV2PositionEvent)

// ZwpTabletPadStripV2StopEvent: interaction stopped
type ZwpTabletPadStripV2StopEvent struct {
}

type ZwpTabletPadStripV2StopHandler func(ZwpTabletPadStripV2StopEvent)

// ZwpTabletPadStripV2FrameEvent: end of a strip event sequence
type ZwpTabletPadStripV2FrameEvent struct {
	Time uint32
}

type ZwpTabletPadStripV2FrameHandler func(ZwpTabletPadStripV2FrameEvent)

// SetSourceHandler sets the handler for the source event
func (i *ZwpTabletPadStripV2) SetSourceHandler(f ZwpTabletPadStripV2SourceHandler) {
	i.sourceHandler = f
}

// SetPositionHandler sets the handler for the position event
func (i *ZwpTabletPadStripV2) SetPositionHandler(f ZwpTabletPadStripV2PositionHandler) {
	i.positionHandler = f
}

// SetStopHandler sets the handler for the stop event
func (i *ZwpTabletPadStripV2) SetStopHandler(f ZwpTabletPadStripV2StopHandler) {
	i.stopHandler = f
}

// SetFrameHandler sets the handler for the frame event
func (i *ZwpTabletPadStripV2) SetFrameHandler(f ZwpTabletPadStripV2FrameHandler) {
	i.frameHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletPadStripV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // source
		if i.sourceHandler != nil {
			ev := ZwpTabletPadStripV2SourceEvent{}
			l := 0
			_ = fd
			ev.Source = ZwpTabletPadStripV2Source(client.Uint32(data[l : l+4]))
			l += 4
			i.sourceHandler(ev)
		}
	case 1: // position
		if i.positionHandler != nil {
			ev := ZwpTabletPadStripV2PositionEvent{}
			l := 0
			_ = fd
			ev.Position = client.Uint32(data[l : l+4])
			l += 4
			i.positionHandler(ev)
		}
	case 2: // stop
		if i.stopHandler != nil {
			ev := ZwpTabletPadStripV2StopEvent{}
			_ = fd
			_ = data
			i.stopHandler(ev)
		}
	case 3: // frame
		if i.frameHandler != nil {
			ev := ZwpTabletPadStripV2FrameEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			i.frameHandler(ev)
		}
	}
}

// ZwpTabletPadGroupV2: a set of buttons, rings and strips
type ZwpTabletPadGroupV2 struct {
	client.BaseProxy
	buttonsHandler    ZwpTabletPadGroupV2ButtonsHandler
	ringHandler       ZwpTabletPadGroupV2RingHandler
	stripHandler      ZwpTabletPadGroupV2StripHandler
	modesHandler      ZwpTabletPadGroupV2ModesHandler
	doneHandler       ZwpTabletPadGroupV2DoneHandler
	modeSwitchHandler ZwpTabletPadGroupV2ModeSwitchHandler
	dialHandler       ZwpTabletPadGroupV2DialHandler
}

// NewZwpTabletPadGroupV2 creates a new ZwpTabletPadGroupV2
func NewZwpTabletPadGroupV2(ctx *client.Context) *ZwpTabletPadGroupV2 {
	o := &ZwpTabletPadGroupV2{}
	ctx.Register(o)
	return o
}

// Destroy: destroy the pad object
func (i *ZwpTabletPadGroupV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadGroupV2ButtonsEvent: buttons announced
type ZwpTabletPadGroupV2ButtonsEvent struct {
	Buttons []byte
}

type ZwpTabletPadGroupV2ButtonsHandler func(ZwpTabletPadGroupV2ButtonsEvent)

// ZwpTabletPadGroupV2RingEvent: ring announced
type ZwpTabletPadGroupV2RingEvent struct {
	Ring *ZwpTabletPadRingV2
}

type ZwpTabletPadGroupV2RingHandler func(ZwpTabletPadGroupV2RingEvent)

// ZwpTabletPadGroupV2StripEvent: strip announced
type ZwpTabletPadGroupV2StripEvent struct {
	Strip *ZwpTabletPadStripV2
}

type ZwpTabletPadGroupV2StripHandler func(ZwpTabletPadGroupV2StripEvent)

// ZwpTabletPadGroupV2ModesEvent: mode-switch ability announced
type ZwpTabletPadGroupV2ModesEvent struct {
	Modes uint32
}

type ZwpTabletPadGroupV2ModesHandler func(ZwpTabletPadGroupV2ModesEvent)

// ZwpTabletPadGroupV2DoneEvent: tablet group description events sequence complete
type ZwpTabletPadGroupV2DoneEvent struct {
}

type ZwpTabletPadGroupV2DoneHandler func(ZwpTabletPadGroupV2DoneEvent)

// ZwpTabletPadGroupV2ModeSwitchEvent: mode switch event
type ZwpTabletPadGroupV2ModeSwitchEvent struct {
	Time   uint32
	Serial uint32
	Mode   uint32
}

type ZwpTabletPadGroupV2ModeSwitchHandler func(ZwpTabletPadGroupV2ModeSwitchEvent)

// ZwpTabletPadGroupV2DialEvent: dial announced
type ZwpTabletPadGroupV2DialEvent struct {
	Dial *ZwpTabletPadDialV2
}

type ZwpTabletPadGroupV2DialHandler func(ZwpTabletPadGroupV2DialEvent)

// SetButtonsHandler sets the handler for the buttons event
func (i *ZwpTabletPadGroupV2) SetButtonsHandler(f ZwpTabletPadGroupV2ButtonsHandler) {
	i.buttonsHandler = f
}

// SetRingHandler sets the handler for the ring event
func (i *ZwpTabletPadGroupV2) SetRingHandler(f ZwpTabletPadGroupV2RingHandler) {
	i.ringHandler = f
}

// SetStripHandler sets the handler for the strip event
func (i *ZwpTabletPadGroupV2) SetStripHandler(f ZwpTabletPadGroupV2StripHandler) {
	i.stripHandler = f
}

// SetModesHandler sets the handler for the modes event
func (i *ZwpTabletPadGroupV2) SetModesHandler(f ZwpTabletPadGroupV2ModesHandler) {
	i.modesHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ZwpTabletPadGroupV2) SetDoneHandler(f ZwpTabletPadGroupV2DoneHandler) {
	i.doneHandler = f
}

// SetModeSwitchHandler sets the handler for the mode_switch event
func (i *ZwpTabletPadGroupV2) SetModeSwitchHandler(f ZwpTabletPadGroupV2ModeSwitchHandler) {
	i.modeSwitchHandler = f
}

// SetDialHandler sets the handler for the dial event
func (i *ZwpTabletPadGroupV2) SetDialHandler(f ZwpTabletPadGroupV2DialHandler) {
	i.dialHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletPadGroupV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // buttons
		if i.buttonsHandler != nil {
			ev := ZwpTabletPadGroupV2ButtonsEvent{}
			l := 0
			_ = fd
			buttonsLen := int(client.Uint32(data[l : l+4]))
			l += 4
			ev.Buttons = data[l : l+buttonsLen]
			l += client.PaddedLen(buttonsLen)
			i.buttonsHandler(ev)
		}
	case 1: // ring
		if i.ringHandler != nil {
			ev := ZwpTabletPadGroupV2RingEvent{}
			l := 0
			_ = fd
			ringID := client.Uint32(data[l : l+4])
			l += 4
			ev.Ring = i.Context().GetProxy(ringID).(*ZwpTabletPadRingV2)
			i.ringHandler(ev)
		}
	case 2: // strip
		if i.stripHandler != nil {
			ev := ZwpTabletPadGroupV2StripEvent{}
			l := 0
			_ = fd
			stripID := client.Uint32(data[l : l+4])
			l += 4
			ev.Strip = i.Context().GetProxy(stripID).(*ZwpTabletPadStripV2)
			i.stripHandler(ev)
		}
	case 3: // modes
		if i.modesHandler != nil {
			ev := ZwpTabletPadGroupV2ModesEvent{}
			l := 0
			_ = fd
			ev.Modes = client.Uint32(data[l : l+4])
			l += 4
			i.modesHandler(ev)
		}
	case 4: // done
		if i.doneHandler != nil {
			ev := ZwpTabletPadGroupV2DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 5: // mode_switch
		if i.modeSwitchHandler != nil {
			ev := ZwpTabletPadGroupV2ModeSwitchEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			ev.Mode = client.Uint32(data[l : l+4])
			l += 4
			i.modeSwitchHandler(ev)
		}
	case 6: // dial
		if i.dialHandler != nil {
			ev := ZwpTabletPadGroupV2DialEvent{}
			l := 0
			_ = fd
			dialID := client.Uint32(data[l : l+4])
			l += 4
			ev.Dial = i.Context().GetProxy(dialID).(*ZwpTabletPadDialV2)
			i.dialHandler(ev)
		}
	}
}

// ZwpTabletPadV2: a set of buttons, rings, strips and dials
type ZwpTabletPadV2 struct {
	client.BaseProxy
	groupHandler   ZwpTabletPadV2GroupHandler
	pathHandler    ZwpTabletPadV2PathHandler
	buttonsHandler ZwpTabletPadV2ButtonsHandler
	doneHandler    ZwpTabletPadV2DoneHandler
	buttonHandler  ZwpTabletPadV2ButtonHandler
	enterHandler   ZwpTabletPadV2EnterHandler
	leaveHandler   ZwpTabletPadV2LeaveHandler
	removedHandler ZwpTabletPadV2RemovedHandler
}

// NewZwpTabletPadV2 creates a new ZwpTabletPadV2
func NewZwpTabletPadV2(ctx *client.Context) *ZwpTabletPadV2 {
	o := &ZwpTabletPadV2{}
	ctx.Register(o)
	return o
}

// ZwpTabletPadV2ButtonState: physical button state
type ZwpTabletPadV2ButtonState uint32

const (
	ZwpTabletPadV2ButtonStateReleased ZwpTabletPadV2ButtonState = 0
	ZwpTabletPadV2ButtonStatePressed  ZwpTabletPadV2ButtonState = 1
)

// SetFeedback: set compositor feedback
func (i *ZwpTabletPadV2) SetFeedback(button uint32, description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + 4 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(button))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description, descriptionLen)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the pad object
func (i *ZwpTabletPadV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadV2GroupEvent: group announced
type ZwpTabletPadV2GroupEvent struct {
	PadGroup *ZwpTabletPadGroupV2
}

type ZwpTabletPadV2GroupHandler func(ZwpTabletPadV2GroupEvent)

// ZwpTabletPadV2PathEvent: path to the device
type ZwpTabletPadV2PathEvent struct {
	Path string
}

type ZwpTabletPadV2PathHandler func(ZwpTabletPadV2PathEvent)

// ZwpTabletPadV2ButtonsEvent: buttons announced
type ZwpTabletPadV2ButtonsEvent struct {
	Buttons uint32
}

type ZwpTabletPadV2ButtonsHandler func(ZwpTabletPadV2ButtonsEvent)

// ZwpTabletPadV2DoneEvent: pad description event sequence complete
type ZwpTabletPadV2DoneEvent struct {
}

type ZwpTabletPadV2DoneHandler func(ZwpTabletPadV2DoneEvent)

// ZwpTabletPadV2ButtonEvent: physical button state
type ZwpTabletPadV2ButtonEvent struct {
	Time   uint32
	Button uint32
	State  ZwpTabletPadV2ButtonState
}

type ZwpTabletPadV2ButtonHandler func(ZwpTabletPadV2ButtonEvent)

// ZwpTabletPadV2EnterEvent: enter event
type ZwpTabletPadV2EnterEvent struct {
	Serial  uint32
	Tablet  *ZwpTabletV2
	Surface *client.WlSurface
}

type ZwpTabletPadV2EnterHandler func(ZwpTabletPadV2EnterEvent)

// ZwpTabletPadV2LeaveEvent: leave event
type ZwpTabletPadV2LeaveEvent struct {
	Serial  uint32
	Surface *client.WlSurface
}

type ZwpTabletPadV2LeaveHandler func(ZwpTabletPadV2LeaveEvent)

// ZwpTabletPadV2RemovedEvent: pad removed event
type ZwpTabletPadV2RemovedEvent struct {
}

type ZwpTabletPadV2RemovedHandler func(ZwpTabletPadV2RemovedEvent)

// SetGroupHandler sets the handler for the group event
func (i *ZwpTabletPadV2) SetGroupHandler(f ZwpTabletPadV2GroupHandler) {
	i.groupHandler = f
}

// SetPathHandler sets the handler for the path event
func (i *ZwpTabletPadV2) SetPathHandler(f ZwpTabletPadV2PathHandler) {
	i.pathHandler = f
}

// SetButtonsHandler sets the handler for the buttons event
func (i *ZwpTabletPadV2) SetButtonsHandler(f ZwpTabletPadV2ButtonsHandler) {
	i.buttonsHandler = f
}

// SetDoneHandler sets the handler for the done event
func (i *ZwpTabletPadV2) SetDoneHandler(f ZwpTabletPadV2DoneHandler) {
	i.doneHandler = f
}

// SetButtonHandler sets the handler for the button event
func (i *ZwpTabletPadV2) SetButtonHandler(f ZwpTabletPadV2ButtonHandler) {
	i.buttonHandler = f
}

// SetEnterHandler sets the handler for the enter event
func (i *ZwpTabletPadV2) SetEnterHandler(f ZwpTabletPadV2EnterHandler) {
	i.enterHandler = f
}

// SetLeaveHandler sets the handler for the leave event
func (i *ZwpTabletPadV2) SetLeaveHandler(f ZwpTabletPadV2LeaveHandler) {
	i.leaveHandler = f
}

// SetRemovedHandler sets the handler for the removed event
func (i *ZwpTabletPadV2) SetRemovedHandler(f ZwpTabletPadV2RemovedHandler) {
	i.removedHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletPadV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // group
		if i.groupHandler != nil {
			ev := ZwpTabletPadV2GroupEvent{}
			l := 0
			_ = fd
			pad_groupID := client.Uint32(data[l : l+4])
			l += 4
			ev.PadGroup = i.Context().GetProxy(pad_groupID).(*ZwpTabletPadGroupV2)
			i.groupHandler(ev)
		}
	case 1: // path
		if i.pathHandler != nil {
			ev := ZwpTabletPadV2PathEvent{}
			l := 0
			_ = fd
			pathRawLen := int(client.Uint32(data[l : l+4]))
			l += 4
			pathLen := client.PaddedLen(pathRawLen)
			ev.Path = client.String(data[l : l+pathLen])
			l += pathLen
			i.pathHandler(ev)
		}
	case 2: // buttons
		if i.buttonsHandler != nil {
			ev := ZwpTabletPadV2ButtonsEvent{}
			l := 0
			_ = fd
			ev.Buttons = client.Uint32(data[l : l+4])
			l += 4
			i.buttonsHandler(ev)
		}
	case 3: // done
		if i.doneHandler != nil {
			ev := ZwpTabletPadV2DoneEvent{}
			_ = fd
			_ = data
			i.doneHandler(ev)
		}
	case 4: // button
		if i.buttonHandler != nil {
			ev := ZwpTabletPadV2ButtonEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			ev.Button = client.Uint32(data[l : l+4])
			l += 4
			ev.State = ZwpTabletPadV2ButtonState(client.Uint32(data[l : l+4]))
			l += 4
			i.buttonHandler(ev)
		}
	case 5: // enter
		if i.enterHandler != nil {
			ev := ZwpTabletPadV2EnterEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			tabletID := client.Uint32(data[l : l+4])
			l += 4
			ev.Tablet = i.Context().GetProxy(tabletID).(*ZwpTabletV2)
			surfaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Surface = i.Context().GetProxy(surfaceID).(*client.WlSurface)
			i.enterHandler(ev)
		}
	case 6: // leave
		if i.leaveHandler != nil {
			ev := ZwpTabletPadV2LeaveEvent{}
			l := 0
			_ = fd
			ev.Serial = client.Uint32(data[l : l+4])
			l += 4
			surfaceID := client.Uint32(data[l : l+4])
			l += 4
			ev.Surface = i.Context().GetProxy(surfaceID).(*client.WlSurface)
			i.leaveHandler(ev)
		}
	case 7: // removed
		if i.removedHandler != nil {
			ev := ZwpTabletPadV2RemovedEvent{}
			_ = fd
			_ = data
			i.removedHandler(ev)
		}
	}
}

// ZwpTabletPadDialV2: pad dial
type ZwpTabletPadDialV2 struct {
	client.BaseProxy
	deltaHandler ZwpTabletPadDialV2DeltaHandler
	frameHandler ZwpTabletPadDialV2FrameHandler
}

// NewZwpTabletPadDialV2 creates a new ZwpTabletPadDialV2
func NewZwpTabletPadDialV2(ctx *client.Context) *ZwpTabletPadDialV2 {
	o := &ZwpTabletPadDialV2{}
	ctx.Register(o)
	return o
}

// SetFeedback: set compositor feedback
func (i *ZwpTabletPadDialV2) SetFeedback(description string, serial uint32) error {
	const opcode = 0
	descriptionLen := client.PaddedLen(len(description) + 1)
	_reqBufLen := 8 + (4 + descriptionLen) + 4
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+descriptionLen)], description, descriptionLen)
	l += (4 + descriptionLen)
	client.PutUint32(_reqBuf[l:l+4], uint32(serial))
	l += 4
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// Destroy: destroy the dial object
func (i *ZwpTabletPadDialV2) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpTabletPadDialV2DeltaEvent: delta movement
type ZwpTabletPadDialV2DeltaEvent struct {
	Value120 int32
}

type ZwpTabletPadDialV2DeltaHandler func(ZwpTabletPadDialV2DeltaEvent)

// ZwpTabletPadDialV2FrameEvent: end of a dial event sequence
type ZwpTabletPadDialV2FrameEvent struct {
	Time uint32
}

type ZwpTabletPadDialV2FrameHandler func(ZwpTabletPadDialV2FrameEvent)

// SetDeltaHandler sets the handler for the delta event
func (i *ZwpTabletPadDialV2) SetDeltaHandler(f ZwpTabletPadDialV2DeltaHandler) {
	i.deltaHandler = f
}

// SetFrameHandler sets the handler for the frame event
func (i *ZwpTabletPadDialV2) SetFrameHandler(f ZwpTabletPadDialV2FrameHandler) {
	i.frameHandler = f
}

// Dispatch handles incoming events
func (i *ZwpTabletPadDialV2) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0: // delta
		if i.deltaHandler != nil {
			ev := ZwpTabletPadDialV2DeltaEvent{}
			l := 0
			_ = fd
			ev.Value120 = int32(client.Uint32(data[l : l+4]))
			l += 4
			i.deltaHandler(ev)
		}
	case 1: // frame
		if i.frameHandler != nil {
			ev := ZwpTabletPadDialV2FrameEvent{}
			l := 0
			_ = fd
			ev.Time = client.Uint32(data[l : l+4])
			l += 4
			i.frameHandler(ev)
		}
	}
}
