// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/stable/linux-dmabuf/linux-dmabuf-v1.xml
//
// linux_dmabuf_v1 Protocol Copyright:
// Copyright © 2014, 2015 Collabora, Ltd.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package linux_dmabuf_v1

import (
	"github.com/tri2820/cheese/protocols/client"
	"golang.org/x/sys/unix"
)

// ZwpLinuxDmabufV1: factory for creating dmabuf-based wl_buffers
type ZwpLinuxDmabufV1 struct {
	client.BaseProxy
}

// NewZwpLinuxDmabufV1 creates a new ZwpLinuxDmabufV1
func NewZwpLinuxDmabufV1(ctx *client.Context) *ZwpLinuxDmabufV1 {
	o := &ZwpLinuxDmabufV1{}
	ctx.Register(o)
	return o
}

// Destroy: unbind the factory
func (i *ZwpLinuxDmabufV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreateParams: create a temporary object for buffer parameters
func (i *ZwpLinuxDmabufV1) CreateParams() (*ZwpLinuxBufferParamsV1, error) {
	params_id := NewZwpLinuxBufferParamsV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], params_id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return params_id, err
}

// GetDefaultFeedback: get default feedback
func (i *ZwpLinuxDmabufV1) GetDefaultFeedback() (*ZwpLinuxDmabufFeedbackV1, error) {
	id := NewZwpLinuxDmabufFeedbackV1(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// GetSurfaceFeedback: get feedback for a surface
func (i *ZwpLinuxDmabufV1) GetSurfaceFeedback(surface *client.WlSurface) (*ZwpLinuxDmabufFeedbackV1, error) {
	id := NewZwpLinuxDmabufFeedbackV1(i.Context())
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

// ZwpLinuxDmabufV1FormatEvent: supported buffer format
type ZwpLinuxDmabufV1FormatEvent struct {
	Format uint32
}

type ZwpLinuxDmabufV1FormatHandler func(ZwpLinuxDmabufV1FormatEvent)

// ZwpLinuxDmabufV1ModifierEvent: supported buffer format modifier
type ZwpLinuxDmabufV1ModifierEvent struct {
	Format     uint32
	ModifierHi uint32
	ModifierLo uint32
}

type ZwpLinuxDmabufV1ModifierHandler func(ZwpLinuxDmabufV1ModifierEvent)

// ZwpLinuxBufferParamsV1: parameters for creating a dmabuf-based wl_buffer
type ZwpLinuxBufferParamsV1 struct {
	client.BaseProxy
}

// NewZwpLinuxBufferParamsV1 creates a new ZwpLinuxBufferParamsV1
func NewZwpLinuxBufferParamsV1(ctx *client.Context) *ZwpLinuxBufferParamsV1 {
	o := &ZwpLinuxBufferParamsV1{}
	ctx.Register(o)
	return o
}

type ZwpLinuxBufferParamsV1Error uint32

const (
	ZwpLinuxBufferParamsV1ErrorAlreadyUsed       ZwpLinuxBufferParamsV1Error = 0
	ZwpLinuxBufferParamsV1ErrorPlaneIdx          ZwpLinuxBufferParamsV1Error = 1
	ZwpLinuxBufferParamsV1ErrorPlaneSet          ZwpLinuxBufferParamsV1Error = 2
	ZwpLinuxBufferParamsV1ErrorIncomplete        ZwpLinuxBufferParamsV1Error = 3
	ZwpLinuxBufferParamsV1ErrorInvalidFormat     ZwpLinuxBufferParamsV1Error = 4
	ZwpLinuxBufferParamsV1ErrorInvalidDimensions ZwpLinuxBufferParamsV1Error = 5
	ZwpLinuxBufferParamsV1ErrorOutOfBounds       ZwpLinuxBufferParamsV1Error = 6
	ZwpLinuxBufferParamsV1ErrorInvalidWlBuffer   ZwpLinuxBufferParamsV1Error = 7
)

type ZwpLinuxBufferParamsV1Flags uint32

const (
	ZwpLinuxBufferParamsV1FlagsYInvert     ZwpLinuxBufferParamsV1Flags = 1
	ZwpLinuxBufferParamsV1FlagsInterlaced  ZwpLinuxBufferParamsV1Flags = 2
	ZwpLinuxBufferParamsV1FlagsBottomFirst ZwpLinuxBufferParamsV1Flags = 4
)

// Destroy: delete this object, used or not
func (i *ZwpLinuxBufferParamsV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Add: add a dmabuf to the temporary set
func (i *ZwpLinuxBufferParamsV1) Add(fd uintptr, plane_idx uint32, offset uint32, stride uint32, modifier_hi uint32, modifier_lo uint32) error {
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(plane_idx))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(offset))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(stride))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(modifier_hi))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(modifier_lo))
	l += 4
	oob := unix.UnixRights(int(fd))
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return err
}

// Create: create a wl_buffer from the given dmabufs
func (i *ZwpLinuxBufferParamsV1) Create(width int32, height int32, format uint32, flags uint32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(format))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(flags))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreateImmed: immediately create a wl_buffer from the given dmabufs
func (i *ZwpLinuxBufferParamsV1) CreateImmed(width int32, height int32, format uint32, flags uint32) (*client.WlBuffer, error) {
	buffer_id := client.NewWlBuffer(i.Context())
	const opcode = 3
	const _reqBufLen = 8 + 4 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer_id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(format))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(flags))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return buffer_id, err
}

// ZwpLinuxBufferParamsV1CreatedEvent: buffer creation succeeded
type ZwpLinuxBufferParamsV1CreatedEvent struct {
	Buffer *client.WlBuffer
}

type ZwpLinuxBufferParamsV1CreatedHandler func(ZwpLinuxBufferParamsV1CreatedEvent)

// ZwpLinuxBufferParamsV1FailedEvent: buffer creation failed
type ZwpLinuxBufferParamsV1FailedEvent struct {
}

type ZwpLinuxBufferParamsV1FailedHandler func(ZwpLinuxBufferParamsV1FailedEvent)

// ZwpLinuxDmabufFeedbackV1: dmabuf feedback
type ZwpLinuxDmabufFeedbackV1 struct {
	client.BaseProxy
}

// NewZwpLinuxDmabufFeedbackV1 creates a new ZwpLinuxDmabufFeedbackV1
func NewZwpLinuxDmabufFeedbackV1(ctx *client.Context) *ZwpLinuxDmabufFeedbackV1 {
	o := &ZwpLinuxDmabufFeedbackV1{}
	ctx.Register(o)
	return o
}

type ZwpLinuxDmabufFeedbackV1TrancheFlags uint32

const (
	ZwpLinuxDmabufFeedbackV1TrancheFlagsScanout ZwpLinuxDmabufFeedbackV1TrancheFlags = 1
)

// Destroy: destroy the feedback object
func (i *ZwpLinuxDmabufFeedbackV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// ZwpLinuxDmabufFeedbackV1DoneEvent: all feedback has been sent
type ZwpLinuxDmabufFeedbackV1DoneEvent struct {
}

type ZwpLinuxDmabufFeedbackV1DoneHandler func(ZwpLinuxDmabufFeedbackV1DoneEvent)

// ZwpLinuxDmabufFeedbackV1FormatTableEvent: format and modifier table
type ZwpLinuxDmabufFeedbackV1FormatTableEvent struct {
	Fd   uintptr
	Size uint32
}

type ZwpLinuxDmabufFeedbackV1FormatTableHandler func(ZwpLinuxDmabufFeedbackV1FormatTableEvent)

// ZwpLinuxDmabufFeedbackV1MainDeviceEvent: preferred main device
type ZwpLinuxDmabufFeedbackV1MainDeviceEvent struct {
	Device []byte
}

type ZwpLinuxDmabufFeedbackV1MainDeviceHandler func(ZwpLinuxDmabufFeedbackV1MainDeviceEvent)

// ZwpLinuxDmabufFeedbackV1TrancheDoneEvent: a preference tranche has been sent
type ZwpLinuxDmabufFeedbackV1TrancheDoneEvent struct {
}

type ZwpLinuxDmabufFeedbackV1TrancheDoneHandler func(ZwpLinuxDmabufFeedbackV1TrancheDoneEvent)

// ZwpLinuxDmabufFeedbackV1TrancheTargetDeviceEvent: target device
type ZwpLinuxDmabufFeedbackV1TrancheTargetDeviceEvent struct {
	Device []byte
}

type ZwpLinuxDmabufFeedbackV1TrancheTargetDeviceHandler func(ZwpLinuxDmabufFeedbackV1TrancheTargetDeviceEvent)

// ZwpLinuxDmabufFeedbackV1TrancheFormatsEvent: supported buffer format modifier
type ZwpLinuxDmabufFeedbackV1TrancheFormatsEvent struct {
	Indices []byte
}

type ZwpLinuxDmabufFeedbackV1TrancheFormatsHandler func(ZwpLinuxDmabufFeedbackV1TrancheFormatsEvent)

// ZwpLinuxDmabufFeedbackV1TrancheFlagsEvent: tranche flags
type ZwpLinuxDmabufFeedbackV1TrancheFlagsEvent struct {
	Flags uint32
}

type ZwpLinuxDmabufFeedbackV1TrancheFlagsHandler func(ZwpLinuxDmabufFeedbackV1TrancheFlagsEvent)
