// Generated by cheese wayland-scanner
// Source: /nix/store/kry53h705nfni3nv71sv579iszbv25bw-wayland-protocols-1.47/share/wayland-protocols/stable/presentation-time/presentation-time.xml
//
// presentation_time Protocol Copyright:
// Copyright © 2013-2014 Collabora, Ltd.
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package presentation_time

import (
	"github.com/tri2820/cheese/protocols/client"
)

// WpPresentation: timed presentation related wl_surface requests
type WpPresentation struct {
	client.BaseProxy
}

// NewWpPresentation creates a new WpPresentation
func NewWpPresentation(ctx *client.Context) *WpPresentation {
	o := &WpPresentation{}
	ctx.Register(o)
	return o
}

// WpPresentationError: fatal presentation errors
type WpPresentationError uint32

const (
	WpPresentationErrorInvalidTimestamp WpPresentationError = 0
	WpPresentationErrorInvalidFlag      WpPresentationError = 1
)

// Destroy: unbind from the presentation interface
func (i *WpPresentation) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Feedback: request presentation feedback information
func (i *WpPresentation) Feedback(surface *client.WlSurface) (*WpPresentationFeedback, error) {
	callback := NewWpPresentationFeedback(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:l+4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], callback.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return callback, err
}

// WpPresentationClockIdEvent: clock ID for timestamps
type WpPresentationClockIdEvent struct {
	ClkId uint32
}

type WpPresentationClockIdHandler func(WpPresentationClockIdEvent)

// WpPresentationFeedback: presentation time feedback event
type WpPresentationFeedback struct {
	client.BaseProxy
}

// NewWpPresentationFeedback creates a new WpPresentationFeedback
func NewWpPresentationFeedback(ctx *client.Context) *WpPresentationFeedback {
	o := &WpPresentationFeedback{}
	ctx.Register(o)
	return o
}

// WpPresentationFeedbackKind: bitmask of flags in presented event
type WpPresentationFeedbackKind uint32

const (
	WpPresentationFeedbackKindVsync        WpPresentationFeedbackKind = 0x1
	WpPresentationFeedbackKindHwClock      WpPresentationFeedbackKind = 0x2
	WpPresentationFeedbackKindHwCompletion WpPresentationFeedbackKind = 0x4
	WpPresentationFeedbackKindZeroCopy     WpPresentationFeedbackKind = 0x8
)

// WpPresentationFeedbackSyncOutputEvent: presentation synchronized to this output
type WpPresentationFeedbackSyncOutputEvent struct {
	Output *client.WlOutput
}

type WpPresentationFeedbackSyncOutputHandler func(WpPresentationFeedbackSyncOutputEvent)

// WpPresentationFeedbackPresentedEvent: the content update was displayed
type WpPresentationFeedbackPresentedEvent struct {
	TvSecHi uint32
	TvSecLo uint32
	TvNsec  uint32
	Refresh uint32
	SeqHi   uint32
	SeqLo   uint32
	Flags   uint32
}

type WpPresentationFeedbackPresentedHandler func(WpPresentationFeedbackPresentedEvent)

// WpPresentationFeedbackDiscardedEvent: the content update was not displayed
type WpPresentationFeedbackDiscardedEvent struct {
}

type WpPresentationFeedbackDiscardedHandler func(WpPresentationFeedbackDiscardedEvent)
